-- create "content_node_versions" table
CREATE TABLE "content_node_versions" ("id" uuid NOT NULL, "content_node_id" uuid NOT NULL, "version_number" bigint NOT NULL, "title" character varying NOT NULL, "content_type" character varying NOT NULL, "media_url" character varying NULL, "rich_content" text NULL, "published_by" uuid NOT NULL, "published_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "contentnodeversion_content_node_id_version_number" to table: "content_node_versions"
CREATE UNIQUE INDEX "contentnodeversion_content_node_id_version_number" ON "content_node_versions" ("content_node_id", "version_number");
-- create "learning_paths" table
CREATE TABLE "learning_paths" ("id" uuid NOT NULL, "teacher_id" uuid NOT NULL, "title" character varying NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create "learning_path_items" table
CREATE TABLE "learning_path_items" ("id" uuid NOT NULL, "learning_path_id" uuid NOT NULL, "content_node_id" uuid NOT NULL, "position" bigint NOT NULL, "section_label" character varying NULL, PRIMARY KEY ("id"));
-- create index "learningpathitem_learning_path_id_position" to table: "learning_path_items"
CREATE UNIQUE INDEX "learningpathitem_learning_path_id_position" ON "learning_path_items" ("learning_path_id", "position");
-- create "expanded_contents" table
CREATE TABLE "expanded_contents" ("id" uuid NOT NULL, "content_node_id" uuid NOT NULL, "content_type" character varying NOT NULL, "media_url" character varying NULL, "rich_content" text NULL, "trigger_at_seconds" bigint NULL, "hide_at_seconds" bigint NULL, "trigger_at_paragraph" bigint NULL, "duration_ms" bigint NULL, "caption" character varying NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "expandedcontent_content_node_id" to table: "expanded_contents"
CREATE INDEX "expandedcontent_content_node_id" ON "expanded_contents" ("content_node_id");
-- create "student_learning_states" table
CREATE TABLE "student_learning_states" ("id" uuid NOT NULL, "student_id" uuid NOT NULL, "current_course_enrollment_id" uuid NULL, "current_standalone_path_id" uuid NULL, PRIMARY KEY ("id"));
-- create index "student_learning_states_student_id_key" to table: "student_learning_states"
CREATE UNIQUE INDEX "student_learning_states_student_id_key" ON "student_learning_states" ("student_id");
-- create "student_paths" table
CREATE TABLE "student_paths" ("id" uuid NOT NULL, "student_id" uuid NOT NULL, "source_template_id" uuid NOT NULL, "title" character varying NOT NULL, "assigned_by" uuid NOT NULL, "assigned_at" timestamptz NOT NULL, "archived_at" timestamptz NULL, "source_course_enrollment_id" uuid NULL, "course_checkpoint_position" bigint NULL, PRIMARY KEY ("id"));
-- create "student_path_items" table
CREATE TABLE "student_path_items" ("id" uuid NOT NULL, "student_path_id" uuid NOT NULL, "content_node_id" uuid NOT NULL, "content_node_version_id" uuid NOT NULL, "position" bigint NOT NULL, "section_label" character varying NULL, PRIMARY KEY ("id"));
-- create index "studentpathitem_student_path_id_position" to table: "student_path_items"
CREATE UNIQUE INDEX "studentpathitem_student_path_id_position" ON "student_path_items" ("student_path_id", "position");
-- create "challenges" table
CREATE TABLE "challenges" ("id" uuid NOT NULL, "content_node_id" uuid NOT NULL, "subject_skill_id" uuid NULL, "subject_concept_id" uuid NULL, "pass_threshold" bigint NOT NULL, "time_threshold_ms" bigint NULL, "shuffle_exercises" boolean NOT NULL DEFAULT false, "shuffle_options" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "challenge_content_node_id" to table: "challenges"
CREATE INDEX "challenge_content_node_id" ON "challenges" ("content_node_id");
-- create "exercises" table
CREATE TABLE "exercises" ("id" uuid NOT NULL, "title" character varying NOT NULL, "prompt" text NOT NULL, "exercise_type" character varying NOT NULL, "image_url" character varying NULL, "audio_url" character varying NULL, "estimated_duration_seconds" bigint NULL, "remediation_targets" text NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create "challenge_exercises" table
CREATE TABLE "challenge_exercises" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "challenge_id" uuid NOT NULL, "exercise_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "challenge_exercises_challenges_challenge" FOREIGN KEY ("challenge_id") REFERENCES "challenges" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "challenge_exercises_exercises_exercise" FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "challengeexercise_challenge_id_exercise_id" to table: "challenge_exercises"
CREATE UNIQUE INDEX "challengeexercise_challenge_id_exercise_id" ON "challenge_exercises" ("challenge_id", "exercise_id");
-- create "concepts" table
CREATE TABLE "concepts" ("id" uuid NOT NULL, "name" character varying NOT NULL, "parent_id" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "concepts_concepts_parent" FOREIGN KEY ("parent_id") REFERENCES "concepts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create "content_nodes" table
CREATE TABLE "content_nodes" ("id" uuid NOT NULL, "teacher_id" uuid NOT NULL, "title" character varying NOT NULL, "content_type" character varying NOT NULL, "media_url" character varying NULL, "rich_content" text NULL, "difficulty_level" character varying NOT NULL, "review_state" character varying NOT NULL DEFAULT 'pending', "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create "content_node_concepts" table
CREATE TABLE "content_node_concepts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "content_node_id" uuid NOT NULL, "concept_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "content_node_concepts_concepts_concept" FOREIGN KEY ("concept_id") REFERENCES "concepts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "content_node_concepts_content_nodes_content_node" FOREIGN KEY ("content_node_id") REFERENCES "content_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "contentnodeconcept_content_node_id_concept_id" to table: "content_node_concepts"
CREATE UNIQUE INDEX "contentnodeconcept_content_node_id_concept_id" ON "content_node_concepts" ("content_node_id", "concept_id");
-- create "content_node_exercises" table
CREATE TABLE "content_node_exercises" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "content_node_id" uuid NOT NULL, "exercise_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "content_node_exercises_content_nodes_content_node" FOREIGN KEY ("content_node_id") REFERENCES "content_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "content_node_exercises_exercises_exercise" FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "contentnodeexercise_content_node_id_exercise_id" to table: "content_node_exercises"
CREATE UNIQUE INDEX "contentnodeexercise_content_node_id_exercise_id" ON "content_node_exercises" ("content_node_id", "exercise_id");
-- create "languages" table
CREATE TABLE "languages" ("id" uuid NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "languages_code_key" to table: "languages"
CREATE UNIQUE INDEX "languages_code_key" ON "languages" ("code");
-- create "content_node_languages" table
CREATE TABLE "content_node_languages" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "content_node_id" uuid NOT NULL, "language_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "content_node_languages_content_nodes_content_node" FOREIGN KEY ("content_node_id") REFERENCES "content_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "content_node_languages_languages_language" FOREIGN KEY ("language_id") REFERENCES "languages" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "contentnodelanguage_content_node_id_language_id" to table: "content_node_languages"
CREATE UNIQUE INDEX "contentnodelanguage_content_node_id_language_id" ON "content_node_languages" ("content_node_id", "language_id");
-- create "skills" table
CREATE TABLE "skills" ("id" uuid NOT NULL, "name" character varying NOT NULL, "parent_id" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "skills_skills_parent" FOREIGN KEY ("parent_id") REFERENCES "skills" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create "content_node_skills" table
CREATE TABLE "content_node_skills" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "content_node_id" uuid NOT NULL, "skill_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "content_node_skills_content_nodes_content_node" FOREIGN KEY ("content_node_id") REFERENCES "content_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "content_node_skills_skills_skill" FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "contentnodeskill_content_node_id_skill_id" to table: "content_node_skills"
CREATE UNIQUE INDEX "contentnodeskill_content_node_id_skill_id" ON "content_node_skills" ("content_node_id", "skill_id");
-- create "instruments" table
CREATE TABLE "instruments" ("id" uuid NOT NULL, "name" character varying NOT NULL, "family" character varying NOT NULL, "string_count" bigint NULL, "tuning" jsonb NULL, "key_range_lowest" character varying NULL, "key_range_highest" character varying NULL, PRIMARY KEY ("id"));
-- create "diagrams" table
CREATE TABLE "diagrams" ("id" uuid NOT NULL, "name" character varying NOT NULL, "created_at" timestamptz NOT NULL, "instrument_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "diagrams_instruments_instrument" FOREIGN KEY ("instrument_id") REFERENCES "instruments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create "diagram_concepts" table
CREATE TABLE "diagram_concepts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "diagram_id" uuid NOT NULL, "concept_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "diagram_concepts_concepts_concept" FOREIGN KEY ("concept_id") REFERENCES "concepts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "diagram_concepts_diagrams_diagram" FOREIGN KEY ("diagram_id") REFERENCES "diagrams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "diagramconcept_diagram_id_concept_id" to table: "diagram_concepts"
CREATE UNIQUE INDEX "diagramconcept_diagram_id_concept_id" ON "diagram_concepts" ("diagram_id", "concept_id");
-- create "diagram_skills" table
CREATE TABLE "diagram_skills" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "diagram_id" uuid NOT NULL, "skill_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "diagram_skills_diagrams_diagram" FOREIGN KEY ("diagram_id") REFERENCES "diagrams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "diagram_skills_skills_skill" FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "diagramskill_diagram_id_skill_id" to table: "diagram_skills"
CREATE UNIQUE INDEX "diagramskill_diagram_id_skill_id" ON "diagram_skills" ("diagram_id", "skill_id");
-- create "exercise_concepts" table
CREATE TABLE "exercise_concepts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "exercise_id" uuid NOT NULL, "concept_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "exercise_concepts_concepts_concept" FOREIGN KEY ("concept_id") REFERENCES "concepts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "exercise_concepts_exercises_exercise" FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "exerciseconcept_exercise_id_concept_id" to table: "exercise_concepts"
CREATE UNIQUE INDEX "exerciseconcept_exercise_id_concept_id" ON "exercise_concepts" ("exercise_id", "concept_id");
-- create "exercise_languages" table
CREATE TABLE "exercise_languages" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "exercise_id" uuid NOT NULL, "language_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "exercise_languages_exercises_exercise" FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "exercise_languages_languages_language" FOREIGN KEY ("language_id") REFERENCES "languages" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "exerciselanguage_exercise_id_language_id" to table: "exercise_languages"
CREATE UNIQUE INDEX "exerciselanguage_exercise_id_language_id" ON "exercise_languages" ("exercise_id", "language_id");
-- create "exercise_options" table
CREATE TABLE "exercise_options" ("id" uuid NOT NULL, "is_correct" boolean NOT NULL, "label" character varying NULL, "image_url" character varying NULL, "audio_url" character varying NULL, "region_x" double precision NULL, "region_y" double precision NULL, "region_width" double precision NULL, "region_height" double precision NULL, "region_shape" character varying NULL, "exercise_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "exercise_options_exercises_options" FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "exerciseoption_exercise_id" to table: "exercise_options"
CREATE INDEX "exerciseoption_exercise_id" ON "exercise_options" ("exercise_id");
-- create "exercise_skills" table
CREATE TABLE "exercise_skills" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "exercise_id" uuid NOT NULL, "skill_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "exercise_skills_exercises_exercise" FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "exercise_skills_skills_skill" FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "exerciseskill_exercise_id_skill_id" to table: "exercise_skills"
CREATE UNIQUE INDEX "exerciseskill_exercise_id_skill_id" ON "exercise_skills" ("exercise_id", "skill_id");
-- create "positions" table
CREATE TABLE "positions" ("id" uuid NOT NULL, "ordinal" bigint NOT NULL, "interval" character varying NOT NULL, "note_name" character varying NOT NULL, "sequence_index" bigint NULL, "string_number" bigint NULL, "fret" bigint NULL, "key" character varying NULL, "diagram_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "positions_diagrams_positions" FOREIGN KEY ("diagram_id") REFERENCES "diagrams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "position_diagram_id_ordinal" to table: "positions"
CREATE UNIQUE INDEX "position_diagram_id_ordinal" ON "positions" ("diagram_id", "ordinal");
-- create "users" table
CREATE TABLE "users" ("id" uuid NOT NULL, "clerk_user_id" character varying NOT NULL, "role" character varying NOT NULL, "registered_at" timestamptz NOT NULL, "locale_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "users_languages_locale" FOREIGN KEY ("locale_id") REFERENCES "languages" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "users_clerk_user_id_key" to table: "users"
CREATE UNIQUE INDEX "users_clerk_user_id_key" ON "users" ("clerk_user_id");
