-- modify "diagram_instruments" table
ALTER TABLE "diagram_instruments" ALTER COLUMN "linked_at" DROP DEFAULT;
-- create "knowledge_nodes" table
CREATE TABLE "knowledge_nodes" ("id" uuid NOT NULL, "kind" character varying NOT NULL, "key" character varying NOT NULL, "names" jsonb NOT NULL, "descriptions" jsonb NULL, "parent_id" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "knowledge_nodes_knowledge_nodes_parent" FOREIGN KEY ("parent_id") REFERENCES "knowledge_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "knowledge_nodes_key_key" to table: "knowledge_nodes"
CREATE UNIQUE INDEX "knowledge_nodes_key_key" ON "knowledge_nodes" ("key");
-- modify "content_node_concepts" table
ALTER TABLE "content_node_concepts" DROP CONSTRAINT "content_node_concepts_concepts_concept", ADD CONSTRAINT "content_node_concepts_knowledge_nodes_concept" FOREIGN KEY ("concept_id") REFERENCES "knowledge_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- modify "content_node_skills" table
ALTER TABLE "content_node_skills" DROP CONSTRAINT "content_node_skills_skills_skill", ADD CONSTRAINT "content_node_skills_knowledge_nodes_skill" FOREIGN KEY ("skill_id") REFERENCES "knowledge_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- modify "diagram_concepts" table
ALTER TABLE "diagram_concepts" DROP CONSTRAINT "diagram_concepts_concepts_concept", ADD CONSTRAINT "diagram_concepts_knowledge_nodes_concept" FOREIGN KEY ("concept_id") REFERENCES "knowledge_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- modify "diagram_skills" table
ALTER TABLE "diagram_skills" DROP CONSTRAINT "diagram_skills_skills_skill", ADD CONSTRAINT "diagram_skills_knowledge_nodes_skill" FOREIGN KEY ("skill_id") REFERENCES "knowledge_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- modify "exercise_concepts" table
ALTER TABLE "exercise_concepts" DROP CONSTRAINT "exercise_concepts_concepts_concept", ADD CONSTRAINT "exercise_concepts_knowledge_nodes_concept" FOREIGN KEY ("concept_id") REFERENCES "knowledge_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- create "exercise_instruments" table
CREATE TABLE "exercise_instruments" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "exercise_id" uuid NOT NULL, "instrument_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "exercise_instruments_exercises_exercise" FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "exercise_instruments_instruments_instrument" FOREIGN KEY ("instrument_id") REFERENCES "instruments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "exerciseinstrument_exercise_id_instrument_id" to table: "exercise_instruments"
CREATE UNIQUE INDEX "exerciseinstrument_exercise_id_instrument_id" ON "exercise_instruments" ("exercise_id", "instrument_id");
-- modify "exercise_skills" table
ALTER TABLE "exercise_skills" DROP CONSTRAINT "exercise_skills_skills_skill", ADD CONSTRAINT "exercise_skills_knowledge_nodes_skill" FOREIGN KEY ("skill_id") REFERENCES "knowledge_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- create "knowledge_edges" table
CREATE TABLE "knowledge_edges" ("id" uuid NOT NULL, "type" character varying NOT NULL, "level" character varying NULL, "from_id" uuid NOT NULL, "to_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "knowledge_edges_knowledge_nodes_from" FOREIGN KEY ("from_id") REFERENCES "knowledge_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "knowledge_edges_knowledge_nodes_to" FOREIGN KEY ("to_id") REFERENCES "knowledge_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "knowledgeedge_from_id_to_id_type" to table: "knowledge_edges"
CREATE UNIQUE INDEX "knowledgeedge_from_id_to_id_type" ON "knowledge_edges" ("from_id", "to_id", "type");
-- create index "knowledgeedge_to_id" to table: "knowledge_edges"
CREATE INDEX "knowledgeedge_to_id" ON "knowledge_edges" ("to_id");
-- create "knowledge_node_instruments" table
CREATE TABLE "knowledge_node_instruments" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "linked_at" timestamptz NOT NULL, "knowledge_node_id" uuid NOT NULL, "instrument_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "knowledge_node_instruments_instruments_instrument" FOREIGN KEY ("instrument_id") REFERENCES "instruments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "knowledge_node_instruments_knowledge_nodes_knowledge_node" FOREIGN KEY ("knowledge_node_id") REFERENCES "knowledge_nodes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "knowledgenodeinstrument_knowledge_node_id_instrument_id" to table: "knowledge_node_instruments"
CREATE UNIQUE INDEX "knowledgenodeinstrument_knowledge_node_id_instrument_id" ON "knowledge_node_instruments" ("knowledge_node_id", "instrument_id");
-- drop "skills" and "concepts" tables: knowledge_nodes replaces both, and every link above now points there. No rows are carried over; databases are recreated from empty before this ships.
-- atlas:nolint destructive
DROP TABLE "skills";
-- atlas:nolint destructive
DROP TABLE "concepts";
