// Code generated by ent, DO NOT EDIT.

package contentnodelanguage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldLTE(FieldID, id))
}

// ContentNodeID applies equality check predicate on the "content_node_id" field. It's identical to ContentNodeIDEQ.
func ContentNodeID(v uuid.UUID) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldEQ(FieldContentNodeID, v))
}

// LanguageID applies equality check predicate on the "language_id" field. It's identical to LanguageIDEQ.
func LanguageID(v uuid.UUID) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldEQ(FieldLanguageID, v))
}

// LinkedAt applies equality check predicate on the "linked_at" field. It's identical to LinkedAtEQ.
func LinkedAt(v time.Time) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldEQ(FieldLinkedAt, v))
}

// ContentNodeIDEQ applies the EQ predicate on the "content_node_id" field.
func ContentNodeIDEQ(v uuid.UUID) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldEQ(FieldContentNodeID, v))
}

// ContentNodeIDNEQ applies the NEQ predicate on the "content_node_id" field.
func ContentNodeIDNEQ(v uuid.UUID) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldNEQ(FieldContentNodeID, v))
}

// ContentNodeIDIn applies the In predicate on the "content_node_id" field.
func ContentNodeIDIn(vs ...uuid.UUID) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldIn(FieldContentNodeID, vs...))
}

// ContentNodeIDNotIn applies the NotIn predicate on the "content_node_id" field.
func ContentNodeIDNotIn(vs ...uuid.UUID) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldNotIn(FieldContentNodeID, vs...))
}

// LanguageIDEQ applies the EQ predicate on the "language_id" field.
func LanguageIDEQ(v uuid.UUID) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldEQ(FieldLanguageID, v))
}

// LanguageIDNEQ applies the NEQ predicate on the "language_id" field.
func LanguageIDNEQ(v uuid.UUID) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldNEQ(FieldLanguageID, v))
}

// LanguageIDIn applies the In predicate on the "language_id" field.
func LanguageIDIn(vs ...uuid.UUID) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldIn(FieldLanguageID, vs...))
}

// LanguageIDNotIn applies the NotIn predicate on the "language_id" field.
func LanguageIDNotIn(vs ...uuid.UUID) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldNotIn(FieldLanguageID, vs...))
}

// LinkedAtEQ applies the EQ predicate on the "linked_at" field.
func LinkedAtEQ(v time.Time) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldEQ(FieldLinkedAt, v))
}

// LinkedAtNEQ applies the NEQ predicate on the "linked_at" field.
func LinkedAtNEQ(v time.Time) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldNEQ(FieldLinkedAt, v))
}

// LinkedAtIn applies the In predicate on the "linked_at" field.
func LinkedAtIn(vs ...time.Time) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldIn(FieldLinkedAt, vs...))
}

// LinkedAtNotIn applies the NotIn predicate on the "linked_at" field.
func LinkedAtNotIn(vs ...time.Time) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldNotIn(FieldLinkedAt, vs...))
}

// LinkedAtGT applies the GT predicate on the "linked_at" field.
func LinkedAtGT(v time.Time) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldGT(FieldLinkedAt, v))
}

// LinkedAtGTE applies the GTE predicate on the "linked_at" field.
func LinkedAtGTE(v time.Time) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldGTE(FieldLinkedAt, v))
}

// LinkedAtLT applies the LT predicate on the "linked_at" field.
func LinkedAtLT(v time.Time) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldLT(FieldLinkedAt, v))
}

// LinkedAtLTE applies the LTE predicate on the "linked_at" field.
func LinkedAtLTE(v time.Time) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.FieldLTE(FieldLinkedAt, v))
}

// HasContentNode applies the HasEdge predicate on the "content_node" edge.
func HasContentNode() predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ContentNodeTable, ContentNodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContentNodeWith applies the HasEdge predicate on the "content_node" edge with a given conditions (other predicates).
func HasContentNodeWith(preds ...predicate.ContentNode) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(func(s *sql.Selector) {
		step := newContentNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLanguage applies the HasEdge predicate on the "language" edge.
func HasLanguage() predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, LanguageTable, LanguageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLanguageWith applies the HasEdge predicate on the "language" edge with a given conditions (other predicates).
func HasLanguageWith(preds ...predicate.Language) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(func(s *sql.Selector) {
		step := newLanguageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContentNodeLanguage) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContentNodeLanguage) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContentNodeLanguage) predicate.ContentNodeLanguage {
	return predicate.ContentNodeLanguage(sql.NotPredicates(p))
}
