// Code generated by ent, DO NOT EDIT.

package exerciseinstrument

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the exerciseinstrument type in the database.
	Label = "exercise_instrument"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExerciseID holds the string denoting the exercise_id field in the database.
	FieldExerciseID = "exercise_id"
	// FieldInstrumentID holds the string denoting the instrument_id field in the database.
	FieldInstrumentID = "instrument_id"
	// FieldLinkedAt holds the string denoting the linked_at field in the database.
	FieldLinkedAt = "linked_at"
	// EdgeExercise holds the string denoting the exercise edge name in mutations.
	EdgeExercise = "exercise"
	// EdgeInstrument holds the string denoting the instrument edge name in mutations.
	EdgeInstrument = "instrument"
	// Table holds the table name of the exerciseinstrument in the database.
	Table = "exercise_instruments"
	// ExerciseTable is the table that holds the exercise relation/edge.
	ExerciseTable = "exercise_instruments"
	// ExerciseInverseTable is the table name for the Exercise entity.
	// It exists in this package in order to avoid circular dependency with the "exercise" package.
	ExerciseInverseTable = "exercises"
	// ExerciseColumn is the table column denoting the exercise relation/edge.
	ExerciseColumn = "exercise_id"
	// InstrumentTable is the table that holds the instrument relation/edge.
	InstrumentTable = "exercise_instruments"
	// InstrumentInverseTable is the table name for the Instrument entity.
	// It exists in this package in order to avoid circular dependency with the "instrument" package.
	InstrumentInverseTable = "instruments"
	// InstrumentColumn is the table column denoting the instrument relation/edge.
	InstrumentColumn = "instrument_id"
)

// Columns holds all SQL columns for exerciseinstrument fields.
var Columns = []string{
	FieldID,
	FieldExerciseID,
	FieldInstrumentID,
	FieldLinkedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLinkedAt holds the default value on creation for the "linked_at" field.
	DefaultLinkedAt func() time.Time
)

// OrderOption defines the ordering options for the ExerciseInstrument queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByExerciseID orders the results by the exercise_id field.
func ByExerciseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExerciseID, opts...).ToFunc()
}

// ByInstrumentID orders the results by the instrument_id field.
func ByInstrumentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstrumentID, opts...).ToFunc()
}

// ByLinkedAt orders the results by the linked_at field.
func ByLinkedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkedAt, opts...).ToFunc()
}

// ByExerciseField orders the results by exercise field.
func ByExerciseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExerciseStep(), sql.OrderByField(field, opts...))
	}
}

// ByInstrumentField orders the results by instrument field.
func ByInstrumentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInstrumentStep(), sql.OrderByField(field, opts...))
	}
}
func newExerciseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExerciseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ExerciseTable, ExerciseColumn),
	)
}
func newInstrumentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InstrumentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, InstrumentTable, InstrumentColumn),
	)
}
