// Code generated by ent, DO NOT EDIT.

package voice

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the voice type in the database.
	Label = "voice"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNames holds the string denoting the names field in the database.
	FieldNames = "names"
	// FieldFamily holds the string denoting the family field in the database.
	FieldFamily = "family"
	// FieldPitches holds the string denoting the pitches field in the database.
	FieldPitches = "pitches"
	// FieldAttribution holds the string denoting the attribution field in the database.
	FieldAttribution = "attribution"
	// EdgeInstruments holds the string denoting the instruments edge name in mutations.
	EdgeInstruments = "instruments"
	// Table holds the table name of the voice in the database.
	Table = "voices"
	// InstrumentsTable is the table that holds the instruments relation/edge.
	InstrumentsTable = "instruments"
	// InstrumentsInverseTable is the table name for the Instrument entity.
	// It exists in this package in order to avoid circular dependency with the "instrument" package.
	InstrumentsInverseTable = "instruments"
	// InstrumentsColumn is the table column denoting the instruments relation/edge.
	InstrumentsColumn = "default_voice_id"
)

// Columns holds all SQL columns for voice fields.
var Columns = []string{
	FieldID,
	FieldNames,
	FieldFamily,
	FieldPitches,
	FieldAttribution,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Family defines the type for the "family" enum field.
type Family string

// Family values.
const (
	FamilyFretted  Family = "fretted"
	FamilyKeyboard Family = "keyboard"
)

func (f Family) String() string {
	return string(f)
}

// FamilyValidator is a validator for the "family" field enum values. It is called by the builders before save.
func FamilyValidator(f Family) error {
	switch f {
	case FamilyFretted, FamilyKeyboard:
		return nil
	default:
		return fmt.Errorf("voice: invalid enum value for family field: %q", f)
	}
}

// OrderOption defines the ordering options for the Voice queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFamily orders the results by the family field.
func ByFamily(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFamily, opts...).ToFunc()
}

// ByAttribution orders the results by the attribution field.
func ByAttribution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttribution, opts...).ToFunc()
}

// ByInstrumentsCount orders the results by instruments count.
func ByInstrumentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInstrumentsStep(), opts...)
	}
}

// ByInstruments orders the results by instruments terms.
func ByInstruments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInstrumentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newInstrumentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InstrumentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, InstrumentsTable, InstrumentsColumn),
	)
}
