// Code generated by ent, DO NOT EDIT.

package exerciseskill

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the exerciseskill type in the database.
	Label = "exercise_skill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExerciseID holds the string denoting the exercise_id field in the database.
	FieldExerciseID = "exercise_id"
	// FieldSkillID holds the string denoting the skill_id field in the database.
	FieldSkillID = "skill_id"
	// FieldLinkedAt holds the string denoting the linked_at field in the database.
	FieldLinkedAt = "linked_at"
	// EdgeExercise holds the string denoting the exercise edge name in mutations.
	EdgeExercise = "exercise"
	// EdgeSkill holds the string denoting the skill edge name in mutations.
	EdgeSkill = "skill"
	// Table holds the table name of the exerciseskill in the database.
	Table = "exercise_skills"
	// ExerciseTable is the table that holds the exercise relation/edge.
	ExerciseTable = "exercise_skills"
	// ExerciseInverseTable is the table name for the Exercise entity.
	// It exists in this package in order to avoid circular dependency with the "exercise" package.
	ExerciseInverseTable = "exercises"
	// ExerciseColumn is the table column denoting the exercise relation/edge.
	ExerciseColumn = "exercise_id"
	// SkillTable is the table that holds the skill relation/edge.
	SkillTable = "exercise_skills"
	// SkillInverseTable is the table name for the Skill entity.
	// It exists in this package in order to avoid circular dependency with the "skill" package.
	SkillInverseTable = "skills"
	// SkillColumn is the table column denoting the skill relation/edge.
	SkillColumn = "skill_id"
)

// Columns holds all SQL columns for exerciseskill fields.
var Columns = []string{
	FieldID,
	FieldExerciseID,
	FieldSkillID,
	FieldLinkedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLinkedAt holds the default value on creation for the "linked_at" field.
	DefaultLinkedAt func() time.Time
)

// OrderOption defines the ordering options for the ExerciseSkill queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByExerciseID orders the results by the exercise_id field.
func ByExerciseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExerciseID, opts...).ToFunc()
}

// BySkillID orders the results by the skill_id field.
func BySkillID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillID, opts...).ToFunc()
}

// ByLinkedAt orders the results by the linked_at field.
func ByLinkedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkedAt, opts...).ToFunc()
}

// ByExerciseField orders the results by exercise field.
func ByExerciseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExerciseStep(), sql.OrderByField(field, opts...))
	}
}

// BySkillField orders the results by skill field.
func BySkillField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSkillStep(), sql.OrderByField(field, opts...))
	}
}
func newExerciseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExerciseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ExerciseTable, ExerciseColumn),
	)
}
func newSkillStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SkillInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SkillTable, SkillColumn),
	)
}
