linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gocognit
    - gocyclo
    - misspell
    - exhaustive
    - forbidigo

linters-settings:
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 15
  forbidigo:
    forbid:
      - p: "^fmt\\.Print"
        msg: "use structured logging instead of fmt.Print"

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gocognit
        - gocyclo
