// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChallengesColumns holds the columns for the "challenges" table.
	ChallengesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "content_node_id", Type: field.TypeUUID},
		{Name: "subject_tag", Type: field.TypeString},
		{Name: "pass_threshold", Type: field.TypeInt},
		{Name: "remediation_target_content_node_id", Type: field.TypeUUID, Nullable: true},
		{Name: "shuffle_exercises", Type: field.TypeBool, Default: false},
		{Name: "shuffle_options", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ChallengesTable holds the schema information for the "challenges" table.
	ChallengesTable = &schema.Table{
		Name:       "challenges",
		Columns:    ChallengesColumns,
		PrimaryKey: []*schema.Column{ChallengesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "challenge_content_node_id",
				Unique:  false,
				Columns: []*schema.Column{ChallengesColumns[1]},
			},
		},
	}
	// ContentNodesColumns holds the columns for the "content_nodes" table.
	ContentNodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "teacher_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "content_type", Type: field.TypeEnum, Enums: []string{"video", "article"}},
		{Name: "skill", Type: field.TypeString},
		{Name: "concept", Type: field.TypeString},
		{Name: "difficulty_level", Type: field.TypeEnum, Enums: []string{"beginner", "intermediate", "advanced"}},
		{Name: "review_state", Type: field.TypeEnum, Enums: []string{"pending", "confirmed", "overridden"}, Default: "pending"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ContentNodesTable holds the schema information for the "content_nodes" table.
	ContentNodesTable = &schema.Table{
		Name:       "content_nodes",
		Columns:    ContentNodesColumns,
		PrimaryKey: []*schema.Column{ContentNodesColumns[0]},
	}
	// ExercisesColumns holds the columns for the "exercises" table.
	ExercisesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "prompt", Type: field.TypeString, Size: 2147483647},
		{Name: "exercise_type", Type: field.TypeEnum, Enums: []string{"text_response", "audio_recognition", "image_recognition", "image_choice"}},
		{Name: "skill_tags", Type: field.TypeJSON, Nullable: true},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "audio_url", Type: field.TypeString, Nullable: true},
		{Name: "estimated_duration_seconds", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ExercisesTable holds the schema information for the "exercises" table.
	ExercisesTable = &schema.Table{
		Name:       "exercises",
		Columns:    ExercisesColumns,
		PrimaryKey: []*schema.Column{ExercisesColumns[0]},
	}
	// ExerciseOptionsColumns holds the columns for the "exercise_options" table.
	ExerciseOptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "is_correct", Type: field.TypeBool},
		{Name: "label", Type: field.TypeString, Nullable: true},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "region_x", Type: field.TypeFloat64, Nullable: true},
		{Name: "region_y", Type: field.TypeFloat64, Nullable: true},
		{Name: "region_width", Type: field.TypeFloat64, Nullable: true},
		{Name: "region_height", Type: field.TypeFloat64, Nullable: true},
		{Name: "region_shape", Type: field.TypeEnum, Nullable: true, Enums: []string{"rectangle", "circle"}},
		{Name: "exercise_id", Type: field.TypeUUID},
	}
	// ExerciseOptionsTable holds the schema information for the "exercise_options" table.
	ExerciseOptionsTable = &schema.Table{
		Name:       "exercise_options",
		Columns:    ExerciseOptionsColumns,
		PrimaryKey: []*schema.Column{ExerciseOptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "exercise_options_exercises_options",
				Columns:    []*schema.Column{ExerciseOptionsColumns[9]},
				RefColumns: []*schema.Column{ExercisesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "exerciseoption_exercise_id",
				Unique:  false,
				Columns: []*schema.Column{ExerciseOptionsColumns[9]},
			},
		},
	}
	// ExpandedContentsColumns holds the columns for the "expanded_contents" table.
	ExpandedContentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "content_node_id", Type: field.TypeUUID},
		{Name: "content_type", Type: field.TypeEnum, Enums: []string{"image", "gif"}},
		{Name: "media_url", Type: field.TypeString},
		{Name: "trigger_at_seconds", Type: field.TypeInt, Nullable: true},
		{Name: "hide_at_seconds", Type: field.TypeInt, Nullable: true},
		{Name: "trigger_at_paragraph", Type: field.TypeInt, Nullable: true},
		{Name: "duration_ms", Type: field.TypeInt, Nullable: true},
		{Name: "caption", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ExpandedContentsTable holds the schema information for the "expanded_contents" table.
	ExpandedContentsTable = &schema.Table{
		Name:       "expanded_contents",
		Columns:    ExpandedContentsColumns,
		PrimaryKey: []*schema.Column{ExpandedContentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "expandedcontent_content_node_id",
				Unique:  false,
				Columns: []*schema.Column{ExpandedContentsColumns[1]},
			},
		},
	}
	// LearningPathsColumns holds the columns for the "learning_paths" table.
	LearningPathsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "teacher_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// LearningPathsTable holds the schema information for the "learning_paths" table.
	LearningPathsTable = &schema.Table{
		Name:       "learning_paths",
		Columns:    LearningPathsColumns,
		PrimaryKey: []*schema.Column{LearningPathsColumns[0]},
	}
	// LearningPathItemsColumns holds the columns for the "learning_path_items" table.
	LearningPathItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "learning_path_id", Type: field.TypeUUID},
		{Name: "content_node_id", Type: field.TypeUUID},
		{Name: "position", Type: field.TypeInt},
		{Name: "section_label", Type: field.TypeString, Nullable: true},
	}
	// LearningPathItemsTable holds the schema information for the "learning_path_items" table.
	LearningPathItemsTable = &schema.Table{
		Name:       "learning_path_items",
		Columns:    LearningPathItemsColumns,
		PrimaryKey: []*schema.Column{LearningPathItemsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "learningpathitem_learning_path_id_position",
				Unique:  true,
				Columns: []*schema.Column{LearningPathItemsColumns[1], LearningPathItemsColumns[3]},
			},
		},
	}
	// PathAssignmentsColumns holds the columns for the "path_assignments" table.
	PathAssignmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "student_id", Type: field.TypeUUID, Unique: true},
		{Name: "learning_path_id", Type: field.TypeUUID},
		{Name: "assigned_by", Type: field.TypeUUID},
		{Name: "assigned_at", Type: field.TypeTime},
	}
	// PathAssignmentsTable holds the schema information for the "path_assignments" table.
	PathAssignmentsTable = &schema.Table{
		Name:       "path_assignments",
		Columns:    PathAssignmentsColumns,
		PrimaryKey: []*schema.Column{PathAssignmentsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "clerk_user_id", Type: field.TypeString, Unique: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"student", "teacher", "admin"}},
		{Name: "registered_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// ExerciseChallengesColumns holds the columns for the "exercise_challenges" table.
	ExerciseChallengesColumns = []*schema.Column{
		{Name: "exercise_id", Type: field.TypeUUID},
		{Name: "challenge_id", Type: field.TypeUUID},
	}
	// ExerciseChallengesTable holds the schema information for the "exercise_challenges" table.
	ExerciseChallengesTable = &schema.Table{
		Name:       "exercise_challenges",
		Columns:    ExerciseChallengesColumns,
		PrimaryKey: []*schema.Column{ExerciseChallengesColumns[0], ExerciseChallengesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "exercise_challenges_exercise_id",
				Columns:    []*schema.Column{ExerciseChallengesColumns[0]},
				RefColumns: []*schema.Column{ExercisesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "exercise_challenges_challenge_id",
				Columns:    []*schema.Column{ExerciseChallengesColumns[1]},
				RefColumns: []*schema.Column{ChallengesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ExerciseContentNodesColumns holds the columns for the "exercise_content_nodes" table.
	ExerciseContentNodesColumns = []*schema.Column{
		{Name: "exercise_id", Type: field.TypeUUID},
		{Name: "content_node_id", Type: field.TypeUUID},
	}
	// ExerciseContentNodesTable holds the schema information for the "exercise_content_nodes" table.
	ExerciseContentNodesTable = &schema.Table{
		Name:       "exercise_content_nodes",
		Columns:    ExerciseContentNodesColumns,
		PrimaryKey: []*schema.Column{ExerciseContentNodesColumns[0], ExerciseContentNodesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "exercise_content_nodes_exercise_id",
				Columns:    []*schema.Column{ExerciseContentNodesColumns[0]},
				RefColumns: []*schema.Column{ExercisesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "exercise_content_nodes_content_node_id",
				Columns:    []*schema.Column{ExerciseContentNodesColumns[1]},
				RefColumns: []*schema.Column{ContentNodesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChallengesTable,
		ContentNodesTable,
		ExercisesTable,
		ExerciseOptionsTable,
		ExpandedContentsTable,
		LearningPathsTable,
		LearningPathItemsTable,
		PathAssignmentsTable,
		UsersTable,
		ExerciseChallengesTable,
		ExerciseContentNodesTable,
	}
)

func init() {
	ExerciseOptionsTable.ForeignKeys[0].RefTable = ExercisesTable
	ExerciseChallengesTable.ForeignKeys[0].RefTable = ExercisesTable
	ExerciseChallengesTable.ForeignKeys[1].RefTable = ChallengesTable
	ExerciseContentNodesTable.ForeignKeys[0].RefTable = ExercisesTable
	ExerciseContentNodesTable.ForeignKeys[1].RefTable = ContentNodesTable
}
