// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChallengesColumns holds the columns for the "challenges" table.
	ChallengesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "content_node_id", Type: field.TypeUUID},
		{Name: "subject_skill_id", Type: field.TypeUUID, Nullable: true},
		{Name: "subject_concept_id", Type: field.TypeUUID, Nullable: true},
		{Name: "pass_threshold", Type: field.TypeInt},
		{Name: "time_threshold_ms", Type: field.TypeInt, Nullable: true},
		{Name: "shuffle_exercises", Type: field.TypeBool, Default: false},
		{Name: "shuffle_options", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ChallengesTable holds the schema information for the "challenges" table.
	ChallengesTable = &schema.Table{
		Name:       "challenges",
		Columns:    ChallengesColumns,
		PrimaryKey: []*schema.Column{ChallengesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "challenge_content_node_id",
				Unique:  false,
				Columns: []*schema.Column{ChallengesColumns[1]},
			},
		},
	}
	// ChallengeExercisesColumns holds the columns for the "challenge_exercises" table.
	ChallengeExercisesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "challenge_id", Type: field.TypeUUID},
		{Name: "exercise_id", Type: field.TypeUUID},
	}
	// ChallengeExercisesTable holds the schema information for the "challenge_exercises" table.
	ChallengeExercisesTable = &schema.Table{
		Name:       "challenge_exercises",
		Columns:    ChallengeExercisesColumns,
		PrimaryKey: []*schema.Column{ChallengeExercisesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "challenge_exercises_challenges_challenge",
				Columns:    []*schema.Column{ChallengeExercisesColumns[2]},
				RefColumns: []*schema.Column{ChallengesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "challenge_exercises_exercises_exercise",
				Columns:    []*schema.Column{ChallengeExercisesColumns[3]},
				RefColumns: []*schema.Column{ExercisesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "challengeexercise_challenge_id_exercise_id",
				Unique:  true,
				Columns: []*schema.Column{ChallengeExercisesColumns[2], ChallengeExercisesColumns[3]},
			},
		},
	}
	// ConceptsColumns holds the columns for the "concepts" table.
	ConceptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
	}
	// ConceptsTable holds the schema information for the "concepts" table.
	ConceptsTable = &schema.Table{
		Name:       "concepts",
		Columns:    ConceptsColumns,
		PrimaryKey: []*schema.Column{ConceptsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "concepts_concepts_parent",
				Columns:    []*schema.Column{ConceptsColumns[2]},
				RefColumns: []*schema.Column{ConceptsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ContentNodesColumns holds the columns for the "content_nodes" table.
	ContentNodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "teacher_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "content_type", Type: field.TypeEnum, Enums: []string{"video", "article"}},
		{Name: "difficulty_level", Type: field.TypeEnum, Enums: []string{"beginner", "early_intermediate", "intermediate", "advanced", "expert"}},
		{Name: "review_state", Type: field.TypeEnum, Enums: []string{"pending", "confirmed", "overridden"}, Default: "pending"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ContentNodesTable holds the schema information for the "content_nodes" table.
	ContentNodesTable = &schema.Table{
		Name:       "content_nodes",
		Columns:    ContentNodesColumns,
		PrimaryKey: []*schema.Column{ContentNodesColumns[0]},
	}
	// ContentNodeConceptsColumns holds the columns for the "content_node_concepts" table.
	ContentNodeConceptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "content_node_id", Type: field.TypeUUID},
		{Name: "concept_id", Type: field.TypeUUID},
	}
	// ContentNodeConceptsTable holds the schema information for the "content_node_concepts" table.
	ContentNodeConceptsTable = &schema.Table{
		Name:       "content_node_concepts",
		Columns:    ContentNodeConceptsColumns,
		PrimaryKey: []*schema.Column{ContentNodeConceptsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "content_node_concepts_content_nodes_content_node",
				Columns:    []*schema.Column{ContentNodeConceptsColumns[2]},
				RefColumns: []*schema.Column{ContentNodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "content_node_concepts_concepts_concept",
				Columns:    []*schema.Column{ContentNodeConceptsColumns[3]},
				RefColumns: []*schema.Column{ConceptsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "contentnodeconcept_content_node_id_concept_id",
				Unique:  true,
				Columns: []*schema.Column{ContentNodeConceptsColumns[2], ContentNodeConceptsColumns[3]},
			},
		},
	}
	// ContentNodeExercisesColumns holds the columns for the "content_node_exercises" table.
	ContentNodeExercisesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "content_node_id", Type: field.TypeUUID},
		{Name: "exercise_id", Type: field.TypeUUID},
	}
	// ContentNodeExercisesTable holds the schema information for the "content_node_exercises" table.
	ContentNodeExercisesTable = &schema.Table{
		Name:       "content_node_exercises",
		Columns:    ContentNodeExercisesColumns,
		PrimaryKey: []*schema.Column{ContentNodeExercisesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "content_node_exercises_content_nodes_content_node",
				Columns:    []*schema.Column{ContentNodeExercisesColumns[2]},
				RefColumns: []*schema.Column{ContentNodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "content_node_exercises_exercises_exercise",
				Columns:    []*schema.Column{ContentNodeExercisesColumns[3]},
				RefColumns: []*schema.Column{ExercisesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "contentnodeexercise_content_node_id_exercise_id",
				Unique:  true,
				Columns: []*schema.Column{ContentNodeExercisesColumns[2], ContentNodeExercisesColumns[3]},
			},
		},
	}
	// ContentNodeLanguagesColumns holds the columns for the "content_node_languages" table.
	ContentNodeLanguagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "content_node_id", Type: field.TypeUUID},
		{Name: "language_id", Type: field.TypeUUID},
	}
	// ContentNodeLanguagesTable holds the schema information for the "content_node_languages" table.
	ContentNodeLanguagesTable = &schema.Table{
		Name:       "content_node_languages",
		Columns:    ContentNodeLanguagesColumns,
		PrimaryKey: []*schema.Column{ContentNodeLanguagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "content_node_languages_content_nodes_content_node",
				Columns:    []*schema.Column{ContentNodeLanguagesColumns[2]},
				RefColumns: []*schema.Column{ContentNodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "content_node_languages_languages_language",
				Columns:    []*schema.Column{ContentNodeLanguagesColumns[3]},
				RefColumns: []*schema.Column{LanguagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "contentnodelanguage_content_node_id_language_id",
				Unique:  true,
				Columns: []*schema.Column{ContentNodeLanguagesColumns[2], ContentNodeLanguagesColumns[3]},
			},
		},
	}
	// ContentNodeSkillsColumns holds the columns for the "content_node_skills" table.
	ContentNodeSkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "content_node_id", Type: field.TypeUUID},
		{Name: "skill_id", Type: field.TypeUUID},
	}
	// ContentNodeSkillsTable holds the schema information for the "content_node_skills" table.
	ContentNodeSkillsTable = &schema.Table{
		Name:       "content_node_skills",
		Columns:    ContentNodeSkillsColumns,
		PrimaryKey: []*schema.Column{ContentNodeSkillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "content_node_skills_content_nodes_content_node",
				Columns:    []*schema.Column{ContentNodeSkillsColumns[2]},
				RefColumns: []*schema.Column{ContentNodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "content_node_skills_skills_skill",
				Columns:    []*schema.Column{ContentNodeSkillsColumns[3]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "contentnodeskill_content_node_id_skill_id",
				Unique:  true,
				Columns: []*schema.Column{ContentNodeSkillsColumns[2], ContentNodeSkillsColumns[3]},
			},
		},
	}
	// DiagramsColumns holds the columns for the "diagrams" table.
	DiagramsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "instrument_id", Type: field.TypeUUID},
	}
	// DiagramsTable holds the schema information for the "diagrams" table.
	DiagramsTable = &schema.Table{
		Name:       "diagrams",
		Columns:    DiagramsColumns,
		PrimaryKey: []*schema.Column{DiagramsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "diagrams_instruments_instrument",
				Columns:    []*schema.Column{DiagramsColumns[3]},
				RefColumns: []*schema.Column{InstrumentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DiagramConceptsColumns holds the columns for the "diagram_concepts" table.
	DiagramConceptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "diagram_id", Type: field.TypeUUID},
		{Name: "concept_id", Type: field.TypeUUID},
	}
	// DiagramConceptsTable holds the schema information for the "diagram_concepts" table.
	DiagramConceptsTable = &schema.Table{
		Name:       "diagram_concepts",
		Columns:    DiagramConceptsColumns,
		PrimaryKey: []*schema.Column{DiagramConceptsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "diagram_concepts_diagrams_diagram",
				Columns:    []*schema.Column{DiagramConceptsColumns[2]},
				RefColumns: []*schema.Column{DiagramsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "diagram_concepts_concepts_concept",
				Columns:    []*schema.Column{DiagramConceptsColumns[3]},
				RefColumns: []*schema.Column{ConceptsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "diagramconcept_diagram_id_concept_id",
				Unique:  true,
				Columns: []*schema.Column{DiagramConceptsColumns[2], DiagramConceptsColumns[3]},
			},
		},
	}
	// DiagramSkillsColumns holds the columns for the "diagram_skills" table.
	DiagramSkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "diagram_id", Type: field.TypeUUID},
		{Name: "skill_id", Type: field.TypeUUID},
	}
	// DiagramSkillsTable holds the schema information for the "diagram_skills" table.
	DiagramSkillsTable = &schema.Table{
		Name:       "diagram_skills",
		Columns:    DiagramSkillsColumns,
		PrimaryKey: []*schema.Column{DiagramSkillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "diagram_skills_diagrams_diagram",
				Columns:    []*schema.Column{DiagramSkillsColumns[2]},
				RefColumns: []*schema.Column{DiagramsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "diagram_skills_skills_skill",
				Columns:    []*schema.Column{DiagramSkillsColumns[3]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "diagramskill_diagram_id_skill_id",
				Unique:  true,
				Columns: []*schema.Column{DiagramSkillsColumns[2], DiagramSkillsColumns[3]},
			},
		},
	}
	// ExercisesColumns holds the columns for the "exercises" table.
	ExercisesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "prompt", Type: field.TypeString, Size: 2147483647},
		{Name: "exercise_type", Type: field.TypeEnum, Enums: []string{"text_response", "audio_recognition", "image_recognition", "image_choice", "audio_selection"}},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "audio_url", Type: field.TypeString, Nullable: true},
		{Name: "estimated_duration_seconds", Type: field.TypeInt, Nullable: true},
		{Name: "remediation_targets", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ExercisesTable holds the schema information for the "exercises" table.
	ExercisesTable = &schema.Table{
		Name:       "exercises",
		Columns:    ExercisesColumns,
		PrimaryKey: []*schema.Column{ExercisesColumns[0]},
	}
	// ExerciseConceptsColumns holds the columns for the "exercise_concepts" table.
	ExerciseConceptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "exercise_id", Type: field.TypeUUID},
		{Name: "concept_id", Type: field.TypeUUID},
	}
	// ExerciseConceptsTable holds the schema information for the "exercise_concepts" table.
	ExerciseConceptsTable = &schema.Table{
		Name:       "exercise_concepts",
		Columns:    ExerciseConceptsColumns,
		PrimaryKey: []*schema.Column{ExerciseConceptsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "exercise_concepts_exercises_exercise",
				Columns:    []*schema.Column{ExerciseConceptsColumns[2]},
				RefColumns: []*schema.Column{ExercisesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "exercise_concepts_concepts_concept",
				Columns:    []*schema.Column{ExerciseConceptsColumns[3]},
				RefColumns: []*schema.Column{ConceptsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "exerciseconcept_exercise_id_concept_id",
				Unique:  true,
				Columns: []*schema.Column{ExerciseConceptsColumns[2], ExerciseConceptsColumns[3]},
			},
		},
	}
	// ExerciseLanguagesColumns holds the columns for the "exercise_languages" table.
	ExerciseLanguagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "exercise_id", Type: field.TypeUUID},
		{Name: "language_id", Type: field.TypeUUID},
	}
	// ExerciseLanguagesTable holds the schema information for the "exercise_languages" table.
	ExerciseLanguagesTable = &schema.Table{
		Name:       "exercise_languages",
		Columns:    ExerciseLanguagesColumns,
		PrimaryKey: []*schema.Column{ExerciseLanguagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "exercise_languages_exercises_exercise",
				Columns:    []*schema.Column{ExerciseLanguagesColumns[2]},
				RefColumns: []*schema.Column{ExercisesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "exercise_languages_languages_language",
				Columns:    []*schema.Column{ExerciseLanguagesColumns[3]},
				RefColumns: []*schema.Column{LanguagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "exerciselanguage_exercise_id_language_id",
				Unique:  true,
				Columns: []*schema.Column{ExerciseLanguagesColumns[2], ExerciseLanguagesColumns[3]},
			},
		},
	}
	// ExerciseOptionsColumns holds the columns for the "exercise_options" table.
	ExerciseOptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "is_correct", Type: field.TypeBool},
		{Name: "label", Type: field.TypeString, Nullable: true},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "audio_url", Type: field.TypeString, Nullable: true},
		{Name: "region_x", Type: field.TypeFloat64, Nullable: true},
		{Name: "region_y", Type: field.TypeFloat64, Nullable: true},
		{Name: "region_width", Type: field.TypeFloat64, Nullable: true},
		{Name: "region_height", Type: field.TypeFloat64, Nullable: true},
		{Name: "region_shape", Type: field.TypeEnum, Nullable: true, Enums: []string{"rectangle", "circle"}},
		{Name: "exercise_id", Type: field.TypeUUID},
	}
	// ExerciseOptionsTable holds the schema information for the "exercise_options" table.
	ExerciseOptionsTable = &schema.Table{
		Name:       "exercise_options",
		Columns:    ExerciseOptionsColumns,
		PrimaryKey: []*schema.Column{ExerciseOptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "exercise_options_exercises_options",
				Columns:    []*schema.Column{ExerciseOptionsColumns[10]},
				RefColumns: []*schema.Column{ExercisesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "exerciseoption_exercise_id",
				Unique:  false,
				Columns: []*schema.Column{ExerciseOptionsColumns[10]},
			},
		},
	}
	// ExerciseSkillsColumns holds the columns for the "exercise_skills" table.
	ExerciseSkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "exercise_id", Type: field.TypeUUID},
		{Name: "skill_id", Type: field.TypeUUID},
	}
	// ExerciseSkillsTable holds the schema information for the "exercise_skills" table.
	ExerciseSkillsTable = &schema.Table{
		Name:       "exercise_skills",
		Columns:    ExerciseSkillsColumns,
		PrimaryKey: []*schema.Column{ExerciseSkillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "exercise_skills_exercises_exercise",
				Columns:    []*schema.Column{ExerciseSkillsColumns[2]},
				RefColumns: []*schema.Column{ExercisesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "exercise_skills_skills_skill",
				Columns:    []*schema.Column{ExerciseSkillsColumns[3]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "exerciseskill_exercise_id_skill_id",
				Unique:  true,
				Columns: []*schema.Column{ExerciseSkillsColumns[2], ExerciseSkillsColumns[3]},
			},
		},
	}
	// ExpandedContentsColumns holds the columns for the "expanded_contents" table.
	ExpandedContentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "content_node_id", Type: field.TypeUUID},
		{Name: "content_type", Type: field.TypeEnum, Enums: []string{"image", "gif", "rich_text"}},
		{Name: "media_url", Type: field.TypeString, Nullable: true},
		{Name: "rich_content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "trigger_at_seconds", Type: field.TypeInt, Nullable: true},
		{Name: "hide_at_seconds", Type: field.TypeInt, Nullable: true},
		{Name: "trigger_at_paragraph", Type: field.TypeInt, Nullable: true},
		{Name: "duration_ms", Type: field.TypeInt, Nullable: true},
		{Name: "caption", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ExpandedContentsTable holds the schema information for the "expanded_contents" table.
	ExpandedContentsTable = &schema.Table{
		Name:       "expanded_contents",
		Columns:    ExpandedContentsColumns,
		PrimaryKey: []*schema.Column{ExpandedContentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "expandedcontent_content_node_id",
				Unique:  false,
				Columns: []*schema.Column{ExpandedContentsColumns[1]},
			},
		},
	}
	// InstrumentsColumns holds the columns for the "instruments" table.
	InstrumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "family", Type: field.TypeEnum, Enums: []string{"fretted", "keyboard"}},
		{Name: "string_count", Type: field.TypeInt, Nullable: true},
		{Name: "tuning", Type: field.TypeJSON, Nullable: true},
		{Name: "key_range_lowest", Type: field.TypeString, Nullable: true},
		{Name: "key_range_highest", Type: field.TypeString, Nullable: true},
	}
	// InstrumentsTable holds the schema information for the "instruments" table.
	InstrumentsTable = &schema.Table{
		Name:       "instruments",
		Columns:    InstrumentsColumns,
		PrimaryKey: []*schema.Column{InstrumentsColumns[0]},
	}
	// LanguagesColumns holds the columns for the "languages" table.
	LanguagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// LanguagesTable holds the schema information for the "languages" table.
	LanguagesTable = &schema.Table{
		Name:       "languages",
		Columns:    LanguagesColumns,
		PrimaryKey: []*schema.Column{LanguagesColumns[0]},
	}
	// LearningPathsColumns holds the columns for the "learning_paths" table.
	LearningPathsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "teacher_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// LearningPathsTable holds the schema information for the "learning_paths" table.
	LearningPathsTable = &schema.Table{
		Name:       "learning_paths",
		Columns:    LearningPathsColumns,
		PrimaryKey: []*schema.Column{LearningPathsColumns[0]},
	}
	// LearningPathItemsColumns holds the columns for the "learning_path_items" table.
	LearningPathItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "learning_path_id", Type: field.TypeUUID},
		{Name: "content_node_id", Type: field.TypeUUID},
		{Name: "position", Type: field.TypeInt},
		{Name: "section_label", Type: field.TypeString, Nullable: true},
	}
	// LearningPathItemsTable holds the schema information for the "learning_path_items" table.
	LearningPathItemsTable = &schema.Table{
		Name:       "learning_path_items",
		Columns:    LearningPathItemsColumns,
		PrimaryKey: []*schema.Column{LearningPathItemsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "learningpathitem_learning_path_id_position",
				Unique:  true,
				Columns: []*schema.Column{LearningPathItemsColumns[1], LearningPathItemsColumns[3]},
			},
		},
	}
	// PathAssignmentsColumns holds the columns for the "path_assignments" table.
	PathAssignmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "student_id", Type: field.TypeUUID, Unique: true},
		{Name: "learning_path_id", Type: field.TypeUUID},
		{Name: "assigned_by", Type: field.TypeUUID},
		{Name: "assigned_at", Type: field.TypeTime},
	}
	// PathAssignmentsTable holds the schema information for the "path_assignments" table.
	PathAssignmentsTable = &schema.Table{
		Name:       "path_assignments",
		Columns:    PathAssignmentsColumns,
		PrimaryKey: []*schema.Column{PathAssignmentsColumns[0]},
	}
	// PositionsColumns holds the columns for the "positions" table.
	PositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "ordinal", Type: field.TypeInt},
		{Name: "interval", Type: field.TypeString},
		{Name: "note_name", Type: field.TypeString},
		{Name: "sequence_index", Type: field.TypeInt, Nullable: true},
		{Name: "string_number", Type: field.TypeInt, Nullable: true},
		{Name: "fret", Type: field.TypeInt, Nullable: true},
		{Name: "key", Type: field.TypeString, Nullable: true},
		{Name: "diagram_id", Type: field.TypeUUID},
	}
	// PositionsTable holds the schema information for the "positions" table.
	PositionsTable = &schema.Table{
		Name:       "positions",
		Columns:    PositionsColumns,
		PrimaryKey: []*schema.Column{PositionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "positions_diagrams_positions",
				Columns:    []*schema.Column{PositionsColumns[8]},
				RefColumns: []*schema.Column{DiagramsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "position_diagram_id_ordinal",
				Unique:  true,
				Columns: []*schema.Column{PositionsColumns[8], PositionsColumns[1]},
			},
		},
	}
	// SkillsColumns holds the columns for the "skills" table.
	SkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
	}
	// SkillsTable holds the schema information for the "skills" table.
	SkillsTable = &schema.Table{
		Name:       "skills",
		Columns:    SkillsColumns,
		PrimaryKey: []*schema.Column{SkillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skills_skills_parent",
				Columns:    []*schema.Column{SkillsColumns[2]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "clerk_user_id", Type: field.TypeString, Unique: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"student", "teacher", "admin"}},
		{Name: "registered_at", Type: field.TypeTime},
		{Name: "locale_id", Type: field.TypeUUID},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_languages_locale",
				Columns:    []*schema.Column{UsersColumns[4]},
				RefColumns: []*schema.Column{LanguagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChallengesTable,
		ChallengeExercisesTable,
		ConceptsTable,
		ContentNodesTable,
		ContentNodeConceptsTable,
		ContentNodeExercisesTable,
		ContentNodeLanguagesTable,
		ContentNodeSkillsTable,
		DiagramsTable,
		DiagramConceptsTable,
		DiagramSkillsTable,
		ExercisesTable,
		ExerciseConceptsTable,
		ExerciseLanguagesTable,
		ExerciseOptionsTable,
		ExerciseSkillsTable,
		ExpandedContentsTable,
		InstrumentsTable,
		LanguagesTable,
		LearningPathsTable,
		LearningPathItemsTable,
		PathAssignmentsTable,
		PositionsTable,
		SkillsTable,
		UsersTable,
	}
)

func init() {
	ChallengeExercisesTable.ForeignKeys[0].RefTable = ChallengesTable
	ChallengeExercisesTable.ForeignKeys[1].RefTable = ExercisesTable
	ConceptsTable.ForeignKeys[0].RefTable = ConceptsTable
	ContentNodeConceptsTable.ForeignKeys[0].RefTable = ContentNodesTable
	ContentNodeConceptsTable.ForeignKeys[1].RefTable = ConceptsTable
	ContentNodeExercisesTable.ForeignKeys[0].RefTable = ContentNodesTable
	ContentNodeExercisesTable.ForeignKeys[1].RefTable = ExercisesTable
	ContentNodeLanguagesTable.ForeignKeys[0].RefTable = ContentNodesTable
	ContentNodeLanguagesTable.ForeignKeys[1].RefTable = LanguagesTable
	ContentNodeSkillsTable.ForeignKeys[0].RefTable = ContentNodesTable
	ContentNodeSkillsTable.ForeignKeys[1].RefTable = SkillsTable
	DiagramsTable.ForeignKeys[0].RefTable = InstrumentsTable
	DiagramConceptsTable.ForeignKeys[0].RefTable = DiagramsTable
	DiagramConceptsTable.ForeignKeys[1].RefTable = ConceptsTable
	DiagramSkillsTable.ForeignKeys[0].RefTable = DiagramsTable
	DiagramSkillsTable.ForeignKeys[1].RefTable = SkillsTable
	ExerciseConceptsTable.ForeignKeys[0].RefTable = ExercisesTable
	ExerciseConceptsTable.ForeignKeys[1].RefTable = ConceptsTable
	ExerciseLanguagesTable.ForeignKeys[0].RefTable = ExercisesTable
	ExerciseLanguagesTable.ForeignKeys[1].RefTable = LanguagesTable
	ExerciseOptionsTable.ForeignKeys[0].RefTable = ExercisesTable
	ExerciseSkillsTable.ForeignKeys[0].RefTable = ExercisesTable
	ExerciseSkillsTable.ForeignKeys[1].RefTable = SkillsTable
	PositionsTable.ForeignKeys[0].RefTable = DiagramsTable
	SkillsTable.ForeignKeys[0].RefTable = SkillsTable
	UsersTable.ForeignKeys[0].RefTable = LanguagesTable
}
