// Code generated by ent, DO NOT EDIT.

package exercise

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the exercise type in the database.
	Label = "exercise"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldExerciseType holds the string denoting the exercise_type field in the database.
	FieldExerciseType = "exercise_type"
	// FieldSkillTags holds the string denoting the skill_tags field in the database.
	FieldSkillTags = "skill_tags"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// FieldAudioURL holds the string denoting the audio_url field in the database.
	FieldAudioURL = "audio_url"
	// FieldEstimatedDurationSeconds holds the string denoting the estimated_duration_seconds field in the database.
	FieldEstimatedDurationSeconds = "estimated_duration_seconds"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeChallenges holds the string denoting the challenges edge name in mutations.
	EdgeChallenges = "challenges"
	// EdgeContentNodes holds the string denoting the content_nodes edge name in mutations.
	EdgeContentNodes = "content_nodes"
	// EdgeOptions holds the string denoting the options edge name in mutations.
	EdgeOptions = "options"
	// Table holds the table name of the exercise in the database.
	Table = "exercises"
	// ChallengesTable is the table that holds the challenges relation/edge. The primary key declared below.
	ChallengesTable = "exercise_challenges"
	// ChallengesInverseTable is the table name for the Challenge entity.
	// It exists in this package in order to avoid circular dependency with the "challenge" package.
	ChallengesInverseTable = "challenges"
	// ContentNodesTable is the table that holds the content_nodes relation/edge. The primary key declared below.
	ContentNodesTable = "exercise_content_nodes"
	// ContentNodesInverseTable is the table name for the ContentNode entity.
	// It exists in this package in order to avoid circular dependency with the "contentnode" package.
	ContentNodesInverseTable = "content_nodes"
	// OptionsTable is the table that holds the options relation/edge.
	OptionsTable = "exercise_options"
	// OptionsInverseTable is the table name for the ExerciseOption entity.
	// It exists in this package in order to avoid circular dependency with the "exerciseoption" package.
	OptionsInverseTable = "exercise_options"
	// OptionsColumn is the table column denoting the options relation/edge.
	OptionsColumn = "exercise_id"
)

// Columns holds all SQL columns for exercise fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldPrompt,
	FieldExerciseType,
	FieldSkillTags,
	FieldImageURL,
	FieldAudioURL,
	FieldEstimatedDurationSeconds,
	FieldCreatedAt,
}

var (
	// ChallengesPrimaryKey and ChallengesColumn2 are the table columns denoting the
	// primary key for the challenges relation (M2M).
	ChallengesPrimaryKey = []string{"exercise_id", "challenge_id"}
	// ContentNodesPrimaryKey and ContentNodesColumn2 are the table columns denoting the
	// primary key for the content_nodes relation (M2M).
	ContentNodesPrimaryKey = []string{"exercise_id", "content_node_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ExerciseType defines the type for the "exercise_type" enum field.
type ExerciseType string

// ExerciseType values.
const (
	ExerciseTypeTextResponse     ExerciseType = "text_response"
	ExerciseTypeAudioRecognition ExerciseType = "audio_recognition"
	ExerciseTypeImageRecognition ExerciseType = "image_recognition"
	ExerciseTypeImageChoice      ExerciseType = "image_choice"
)

func (et ExerciseType) String() string {
	return string(et)
}

// ExerciseTypeValidator is a validator for the "exercise_type" field enum values. It is called by the builders before save.
func ExerciseTypeValidator(et ExerciseType) error {
	switch et {
	case ExerciseTypeTextResponse, ExerciseTypeAudioRecognition, ExerciseTypeImageRecognition, ExerciseTypeImageChoice:
		return nil
	default:
		return fmt.Errorf("exercise: invalid enum value for exercise_type field: %q", et)
	}
}

// OrderOption defines the ordering options for the Exercise queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// ByExerciseType orders the results by the exercise_type field.
func ByExerciseType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExerciseType, opts...).ToFunc()
}

// ByImageURL orders the results by the image_url field.
func ByImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageURL, opts...).ToFunc()
}

// ByAudioURL orders the results by the audio_url field.
func ByAudioURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudioURL, opts...).ToFunc()
}

// ByEstimatedDurationSeconds orders the results by the estimated_duration_seconds field.
func ByEstimatedDurationSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedDurationSeconds, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByChallengesCount orders the results by challenges count.
func ByChallengesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChallengesStep(), opts...)
	}
}

// ByChallenges orders the results by challenges terms.
func ByChallenges(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChallengesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByContentNodesCount orders the results by content_nodes count.
func ByContentNodesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newContentNodesStep(), opts...)
	}
}

// ByContentNodes orders the results by content_nodes terms.
func ByContentNodes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContentNodesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOptionsCount orders the results by options count.
func ByOptionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOptionsStep(), opts...)
	}
}

// ByOptions orders the results by options terms.
func ByOptions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOptionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChallengesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChallengesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ChallengesTable, ChallengesPrimaryKey...),
	)
}
func newContentNodesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ContentNodesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ContentNodesTable, ContentNodesPrimaryKey...),
	)
}
func newOptionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OptionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OptionsTable, OptionsColumn),
	)
}
