// Code generated by ent, DO NOT EDIT.

package studentlearningstate

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the studentlearningstate type in the database.
	Label = "student_learning_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStudentID holds the string denoting the student_id field in the database.
	FieldStudentID = "student_id"
	// FieldCurrentCourseEnrollmentID holds the string denoting the current_course_enrollment_id field in the database.
	FieldCurrentCourseEnrollmentID = "current_course_enrollment_id"
	// FieldCurrentStandalonePathID holds the string denoting the current_standalone_path_id field in the database.
	FieldCurrentStandalonePathID = "current_standalone_path_id"
	// Table holds the table name of the studentlearningstate in the database.
	Table = "student_learning_states"
)

// Columns holds all SQL columns for studentlearningstate fields.
var Columns = []string{
	FieldID,
	FieldStudentID,
	FieldCurrentCourseEnrollmentID,
	FieldCurrentStandalonePathID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the StudentLearningState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStudentID orders the results by the student_id field.
func ByStudentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStudentID, opts...).ToFunc()
}

// ByCurrentCourseEnrollmentID orders the results by the current_course_enrollment_id field.
func ByCurrentCourseEnrollmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentCourseEnrollmentID, opts...).ToFunc()
}

// ByCurrentStandalonePathID orders the results by the current_standalone_path_id field.
func ByCurrentStandalonePathID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentStandalonePathID, opts...).ToFunc()
}
