// Code generated by ent, DO NOT EDIT.

package diagramregion

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the diagramregion type in the database.
	Label = "diagram_region"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDiagramID holds the string denoting the diagram_id field in the database.
	FieldDiagramID = "diagram_id"
	// FieldOrdinal holds the string denoting the ordinal field in the database.
	FieldOrdinal = "ordinal"
	// FieldFretStart holds the string denoting the fret_start field in the database.
	FieldFretStart = "fret_start"
	// FieldFretEnd holds the string denoting the fret_end field in the database.
	FieldFretEnd = "fret_end"
	// FieldStringStart holds the string denoting the string_start field in the database.
	FieldStringStart = "string_start"
	// FieldStringEnd holds the string denoting the string_end field in the database.
	FieldStringEnd = "string_end"
	// FieldKeyStart holds the string denoting the key_start field in the database.
	FieldKeyStart = "key_start"
	// FieldKeyEnd holds the string denoting the key_end field in the database.
	FieldKeyEnd = "key_end"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldColor holds the string denoting the color field in the database.
	FieldColor = "color"
	// EdgeDiagram holds the string denoting the diagram edge name in mutations.
	EdgeDiagram = "diagram"
	// Table holds the table name of the diagramregion in the database.
	Table = "diagram_regions"
	// DiagramTable is the table that holds the diagram relation/edge.
	DiagramTable = "diagram_regions"
	// DiagramInverseTable is the table name for the Diagram entity.
	// It exists in this package in order to avoid circular dependency with the "diagram" package.
	DiagramInverseTable = "diagrams"
	// DiagramColumn is the table column denoting the diagram relation/edge.
	DiagramColumn = "diagram_id"
)

// Columns holds all SQL columns for diagramregion fields.
var Columns = []string{
	FieldID,
	FieldDiagramID,
	FieldOrdinal,
	FieldFretStart,
	FieldFretEnd,
	FieldStringStart,
	FieldStringEnd,
	FieldKeyStart,
	FieldKeyEnd,
	FieldDescription,
	FieldColor,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the DiagramRegion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDiagramID orders the results by the diagram_id field.
func ByDiagramID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiagramID, opts...).ToFunc()
}

// ByOrdinal orders the results by the ordinal field.
func ByOrdinal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrdinal, opts...).ToFunc()
}

// ByFretStart orders the results by the fret_start field.
func ByFretStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFretStart, opts...).ToFunc()
}

// ByFretEnd orders the results by the fret_end field.
func ByFretEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFretEnd, opts...).ToFunc()
}

// ByStringStart orders the results by the string_start field.
func ByStringStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStringStart, opts...).ToFunc()
}

// ByStringEnd orders the results by the string_end field.
func ByStringEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStringEnd, opts...).ToFunc()
}

// ByKeyStart orders the results by the key_start field.
func ByKeyStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyStart, opts...).ToFunc()
}

// ByKeyEnd orders the results by the key_end field.
func ByKeyEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyEnd, opts...).ToFunc()
}

// ByColor orders the results by the color field.
func ByColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldColor, opts...).ToFunc()
}

// ByDiagramField orders the results by diagram field.
func ByDiagramField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDiagramStep(), sql.OrderByField(field, opts...))
	}
}
func newDiagramStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DiagramInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DiagramTable, DiagramColumn),
	)
}
