// Code generated by ent, DO NOT EDIT.

package fretboardcellrange

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the fretboardcellrange type in the database.
	Label = "fretboard_cell_range"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSkillID holds the string denoting the skill_id field in the database.
	FieldSkillID = "skill_id"
	// FieldLayoutInstrumentID holds the string denoting the layout_instrument_id field in the database.
	FieldLayoutInstrumentID = "layout_instrument_id"
	// FieldStrings holds the string denoting the strings field in the database.
	FieldStrings = "strings"
	// FieldFromFret holds the string denoting the from_fret field in the database.
	FieldFromFret = "from_fret"
	// FieldToFret holds the string denoting the to_fret field in the database.
	FieldToFret = "to_fret"
	// EdgeSkill holds the string denoting the skill edge name in mutations.
	EdgeSkill = "skill"
	// EdgeLayoutInstrument holds the string denoting the layout_instrument edge name in mutations.
	EdgeLayoutInstrument = "layout_instrument"
	// Table holds the table name of the fretboardcellrange in the database.
	Table = "fretboard_cell_ranges"
	// SkillTable is the table that holds the skill relation/edge.
	SkillTable = "fretboard_cell_ranges"
	// SkillInverseTable is the table name for the KnowledgeNode entity.
	// It exists in this package in order to avoid circular dependency with the "knowledgenode" package.
	SkillInverseTable = "knowledge_nodes"
	// SkillColumn is the table column denoting the skill relation/edge.
	SkillColumn = "skill_id"
	// LayoutInstrumentTable is the table that holds the layout_instrument relation/edge.
	LayoutInstrumentTable = "fretboard_cell_ranges"
	// LayoutInstrumentInverseTable is the table name for the Instrument entity.
	// It exists in this package in order to avoid circular dependency with the "instrument" package.
	LayoutInstrumentInverseTable = "instruments"
	// LayoutInstrumentColumn is the table column denoting the layout_instrument relation/edge.
	LayoutInstrumentColumn = "layout_instrument_id"
)

// Columns holds all SQL columns for fretboardcellrange fields.
var Columns = []string{
	FieldID,
	FieldSkillID,
	FieldLayoutInstrumentID,
	FieldStrings,
	FieldFromFret,
	FieldToFret,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FromFretValidator is a validator for the "from_fret" field. It is called by the builders before save.
	FromFretValidator func(int) error
	// ToFretValidator is a validator for the "to_fret" field. It is called by the builders before save.
	ToFretValidator func(int) error
)

// OrderOption defines the ordering options for the FretboardCellRange queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySkillID orders the results by the skill_id field.
func BySkillID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillID, opts...).ToFunc()
}

// ByLayoutInstrumentID orders the results by the layout_instrument_id field.
func ByLayoutInstrumentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLayoutInstrumentID, opts...).ToFunc()
}

// ByFromFret orders the results by the from_fret field.
func ByFromFret(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromFret, opts...).ToFunc()
}

// ByToFret orders the results by the to_fret field.
func ByToFret(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToFret, opts...).ToFunc()
}

// BySkillField orders the results by skill field.
func BySkillField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSkillStep(), sql.OrderByField(field, opts...))
	}
}

// ByLayoutInstrumentField orders the results by layout_instrument field.
func ByLayoutInstrumentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLayoutInstrumentStep(), sql.OrderByField(field, opts...))
	}
}
func newSkillStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SkillInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SkillTable, SkillColumn),
	)
}
func newLayoutInstrumentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LayoutInstrumentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, LayoutInstrumentTable, LayoutInstrumentColumn),
	)
}
