// Code generated by ent, DO NOT EDIT.

package courseenrollment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLTE(FieldID, id))
}

// StudentID applies equality check predicate on the "student_id" field. It's identical to StudentIDEQ.
func StudentID(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldStudentID, v))
}

// CourseID applies equality check predicate on the "course_id" field. It's identical to CourseIDEQ.
func CourseID(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldCourseID, v))
}

// CourseTitle applies equality check predicate on the "course_title" field. It's identical to CourseTitleEQ.
func CourseTitle(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldCourseTitle, v))
}

// CourseThumbnailURL applies equality check predicate on the "course_thumbnail_url" field. It's identical to CourseThumbnailURLEQ.
func CourseThumbnailURL(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldCourseThumbnailURL, v))
}

// CourseVersionNumber applies equality check predicate on the "course_version_number" field. It's identical to CourseVersionNumberEQ.
func CourseVersionNumber(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldCourseVersionNumber, v))
}

// ActiveCheckpointStudentPathID applies equality check predicate on the "active_checkpoint_student_path_id" field. It's identical to ActiveCheckpointStudentPathIDEQ.
func ActiveCheckpointStudentPathID(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldActiveCheckpointStudentPathID, v))
}

// ActiveCheckpointPosition applies equality check predicate on the "active_checkpoint_position" field. It's identical to ActiveCheckpointPositionEQ.
func ActiveCheckpointPosition(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldActiveCheckpointPosition, v))
}

// EnrolledAt applies equality check predicate on the "enrolled_at" field. It's identical to EnrolledAtEQ.
func EnrolledAt(v time.Time) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldEnrolledAt, v))
}

// StudentIDEQ applies the EQ predicate on the "student_id" field.
func StudentIDEQ(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldStudentID, v))
}

// StudentIDNEQ applies the NEQ predicate on the "student_id" field.
func StudentIDNEQ(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNEQ(FieldStudentID, v))
}

// StudentIDIn applies the In predicate on the "student_id" field.
func StudentIDIn(vs ...uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIn(FieldStudentID, vs...))
}

// StudentIDNotIn applies the NotIn predicate on the "student_id" field.
func StudentIDNotIn(vs ...uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotIn(FieldStudentID, vs...))
}

// StudentIDGT applies the GT predicate on the "student_id" field.
func StudentIDGT(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGT(FieldStudentID, v))
}

// StudentIDGTE applies the GTE predicate on the "student_id" field.
func StudentIDGTE(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGTE(FieldStudentID, v))
}

// StudentIDLT applies the LT predicate on the "student_id" field.
func StudentIDLT(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLT(FieldStudentID, v))
}

// StudentIDLTE applies the LTE predicate on the "student_id" field.
func StudentIDLTE(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLTE(FieldStudentID, v))
}

// CourseIDEQ applies the EQ predicate on the "course_id" field.
func CourseIDEQ(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldCourseID, v))
}

// CourseIDNEQ applies the NEQ predicate on the "course_id" field.
func CourseIDNEQ(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNEQ(FieldCourseID, v))
}

// CourseIDIn applies the In predicate on the "course_id" field.
func CourseIDIn(vs ...uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIn(FieldCourseID, vs...))
}

// CourseIDNotIn applies the NotIn predicate on the "course_id" field.
func CourseIDNotIn(vs ...uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotIn(FieldCourseID, vs...))
}

// CourseIDGT applies the GT predicate on the "course_id" field.
func CourseIDGT(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGT(FieldCourseID, v))
}

// CourseIDGTE applies the GTE predicate on the "course_id" field.
func CourseIDGTE(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGTE(FieldCourseID, v))
}

// CourseIDLT applies the LT predicate on the "course_id" field.
func CourseIDLT(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLT(FieldCourseID, v))
}

// CourseIDLTE applies the LTE predicate on the "course_id" field.
func CourseIDLTE(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLTE(FieldCourseID, v))
}

// CourseTitleEQ applies the EQ predicate on the "course_title" field.
func CourseTitleEQ(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldCourseTitle, v))
}

// CourseTitleNEQ applies the NEQ predicate on the "course_title" field.
func CourseTitleNEQ(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNEQ(FieldCourseTitle, v))
}

// CourseTitleIn applies the In predicate on the "course_title" field.
func CourseTitleIn(vs ...string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIn(FieldCourseTitle, vs...))
}

// CourseTitleNotIn applies the NotIn predicate on the "course_title" field.
func CourseTitleNotIn(vs ...string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotIn(FieldCourseTitle, vs...))
}

// CourseTitleGT applies the GT predicate on the "course_title" field.
func CourseTitleGT(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGT(FieldCourseTitle, v))
}

// CourseTitleGTE applies the GTE predicate on the "course_title" field.
func CourseTitleGTE(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGTE(FieldCourseTitle, v))
}

// CourseTitleLT applies the LT predicate on the "course_title" field.
func CourseTitleLT(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLT(FieldCourseTitle, v))
}

// CourseTitleLTE applies the LTE predicate on the "course_title" field.
func CourseTitleLTE(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLTE(FieldCourseTitle, v))
}

// CourseTitleContains applies the Contains predicate on the "course_title" field.
func CourseTitleContains(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldContains(FieldCourseTitle, v))
}

// CourseTitleHasPrefix applies the HasPrefix predicate on the "course_title" field.
func CourseTitleHasPrefix(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldHasPrefix(FieldCourseTitle, v))
}

// CourseTitleHasSuffix applies the HasSuffix predicate on the "course_title" field.
func CourseTitleHasSuffix(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldHasSuffix(FieldCourseTitle, v))
}

// CourseTitleEqualFold applies the EqualFold predicate on the "course_title" field.
func CourseTitleEqualFold(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEqualFold(FieldCourseTitle, v))
}

// CourseTitleContainsFold applies the ContainsFold predicate on the "course_title" field.
func CourseTitleContainsFold(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldContainsFold(FieldCourseTitle, v))
}

// CourseThumbnailURLEQ applies the EQ predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLEQ(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldCourseThumbnailURL, v))
}

// CourseThumbnailURLNEQ applies the NEQ predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLNEQ(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNEQ(FieldCourseThumbnailURL, v))
}

// CourseThumbnailURLIn applies the In predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLIn(vs ...string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIn(FieldCourseThumbnailURL, vs...))
}

// CourseThumbnailURLNotIn applies the NotIn predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLNotIn(vs ...string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotIn(FieldCourseThumbnailURL, vs...))
}

// CourseThumbnailURLGT applies the GT predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLGT(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGT(FieldCourseThumbnailURL, v))
}

// CourseThumbnailURLGTE applies the GTE predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLGTE(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGTE(FieldCourseThumbnailURL, v))
}

// CourseThumbnailURLLT applies the LT predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLLT(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLT(FieldCourseThumbnailURL, v))
}

// CourseThumbnailURLLTE applies the LTE predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLLTE(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLTE(FieldCourseThumbnailURL, v))
}

// CourseThumbnailURLContains applies the Contains predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLContains(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldContains(FieldCourseThumbnailURL, v))
}

// CourseThumbnailURLHasPrefix applies the HasPrefix predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLHasPrefix(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldHasPrefix(FieldCourseThumbnailURL, v))
}

// CourseThumbnailURLHasSuffix applies the HasSuffix predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLHasSuffix(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldHasSuffix(FieldCourseThumbnailURL, v))
}

// CourseThumbnailURLIsNil applies the IsNil predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLIsNil() predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIsNull(FieldCourseThumbnailURL))
}

// CourseThumbnailURLNotNil applies the NotNil predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLNotNil() predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotNull(FieldCourseThumbnailURL))
}

// CourseThumbnailURLEqualFold applies the EqualFold predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLEqualFold(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEqualFold(FieldCourseThumbnailURL, v))
}

// CourseThumbnailURLContainsFold applies the ContainsFold predicate on the "course_thumbnail_url" field.
func CourseThumbnailURLContainsFold(v string) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldContainsFold(FieldCourseThumbnailURL, v))
}

// CourseVersionNumberEQ applies the EQ predicate on the "course_version_number" field.
func CourseVersionNumberEQ(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldCourseVersionNumber, v))
}

// CourseVersionNumberNEQ applies the NEQ predicate on the "course_version_number" field.
func CourseVersionNumberNEQ(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNEQ(FieldCourseVersionNumber, v))
}

// CourseVersionNumberIn applies the In predicate on the "course_version_number" field.
func CourseVersionNumberIn(vs ...int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIn(FieldCourseVersionNumber, vs...))
}

// CourseVersionNumberNotIn applies the NotIn predicate on the "course_version_number" field.
func CourseVersionNumberNotIn(vs ...int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotIn(FieldCourseVersionNumber, vs...))
}

// CourseVersionNumberGT applies the GT predicate on the "course_version_number" field.
func CourseVersionNumberGT(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGT(FieldCourseVersionNumber, v))
}

// CourseVersionNumberGTE applies the GTE predicate on the "course_version_number" field.
func CourseVersionNumberGTE(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGTE(FieldCourseVersionNumber, v))
}

// CourseVersionNumberLT applies the LT predicate on the "course_version_number" field.
func CourseVersionNumberLT(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLT(FieldCourseVersionNumber, v))
}

// CourseVersionNumberLTE applies the LTE predicate on the "course_version_number" field.
func CourseVersionNumberLTE(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLTE(FieldCourseVersionNumber, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotIn(FieldStatus, vs...))
}

// ActiveCheckpointStudentPathIDEQ applies the EQ predicate on the "active_checkpoint_student_path_id" field.
func ActiveCheckpointStudentPathIDEQ(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldActiveCheckpointStudentPathID, v))
}

// ActiveCheckpointStudentPathIDNEQ applies the NEQ predicate on the "active_checkpoint_student_path_id" field.
func ActiveCheckpointStudentPathIDNEQ(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNEQ(FieldActiveCheckpointStudentPathID, v))
}

// ActiveCheckpointStudentPathIDIn applies the In predicate on the "active_checkpoint_student_path_id" field.
func ActiveCheckpointStudentPathIDIn(vs ...uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIn(FieldActiveCheckpointStudentPathID, vs...))
}

// ActiveCheckpointStudentPathIDNotIn applies the NotIn predicate on the "active_checkpoint_student_path_id" field.
func ActiveCheckpointStudentPathIDNotIn(vs ...uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotIn(FieldActiveCheckpointStudentPathID, vs...))
}

// ActiveCheckpointStudentPathIDGT applies the GT predicate on the "active_checkpoint_student_path_id" field.
func ActiveCheckpointStudentPathIDGT(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGT(FieldActiveCheckpointStudentPathID, v))
}

// ActiveCheckpointStudentPathIDGTE applies the GTE predicate on the "active_checkpoint_student_path_id" field.
func ActiveCheckpointStudentPathIDGTE(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGTE(FieldActiveCheckpointStudentPathID, v))
}

// ActiveCheckpointStudentPathIDLT applies the LT predicate on the "active_checkpoint_student_path_id" field.
func ActiveCheckpointStudentPathIDLT(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLT(FieldActiveCheckpointStudentPathID, v))
}

// ActiveCheckpointStudentPathIDLTE applies the LTE predicate on the "active_checkpoint_student_path_id" field.
func ActiveCheckpointStudentPathIDLTE(v uuid.UUID) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLTE(FieldActiveCheckpointStudentPathID, v))
}

// ActiveCheckpointStudentPathIDIsNil applies the IsNil predicate on the "active_checkpoint_student_path_id" field.
func ActiveCheckpointStudentPathIDIsNil() predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIsNull(FieldActiveCheckpointStudentPathID))
}

// ActiveCheckpointStudentPathIDNotNil applies the NotNil predicate on the "active_checkpoint_student_path_id" field.
func ActiveCheckpointStudentPathIDNotNil() predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotNull(FieldActiveCheckpointStudentPathID))
}

// ActiveCheckpointPositionEQ applies the EQ predicate on the "active_checkpoint_position" field.
func ActiveCheckpointPositionEQ(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldActiveCheckpointPosition, v))
}

// ActiveCheckpointPositionNEQ applies the NEQ predicate on the "active_checkpoint_position" field.
func ActiveCheckpointPositionNEQ(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNEQ(FieldActiveCheckpointPosition, v))
}

// ActiveCheckpointPositionIn applies the In predicate on the "active_checkpoint_position" field.
func ActiveCheckpointPositionIn(vs ...int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIn(FieldActiveCheckpointPosition, vs...))
}

// ActiveCheckpointPositionNotIn applies the NotIn predicate on the "active_checkpoint_position" field.
func ActiveCheckpointPositionNotIn(vs ...int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotIn(FieldActiveCheckpointPosition, vs...))
}

// ActiveCheckpointPositionGT applies the GT predicate on the "active_checkpoint_position" field.
func ActiveCheckpointPositionGT(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGT(FieldActiveCheckpointPosition, v))
}

// ActiveCheckpointPositionGTE applies the GTE predicate on the "active_checkpoint_position" field.
func ActiveCheckpointPositionGTE(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGTE(FieldActiveCheckpointPosition, v))
}

// ActiveCheckpointPositionLT applies the LT predicate on the "active_checkpoint_position" field.
func ActiveCheckpointPositionLT(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLT(FieldActiveCheckpointPosition, v))
}

// ActiveCheckpointPositionLTE applies the LTE predicate on the "active_checkpoint_position" field.
func ActiveCheckpointPositionLTE(v int) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLTE(FieldActiveCheckpointPosition, v))
}

// ActiveCheckpointPositionIsNil applies the IsNil predicate on the "active_checkpoint_position" field.
func ActiveCheckpointPositionIsNil() predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIsNull(FieldActiveCheckpointPosition))
}

// ActiveCheckpointPositionNotNil applies the NotNil predicate on the "active_checkpoint_position" field.
func ActiveCheckpointPositionNotNil() predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotNull(FieldActiveCheckpointPosition))
}

// EnrolledAtEQ applies the EQ predicate on the "enrolled_at" field.
func EnrolledAtEQ(v time.Time) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldEQ(FieldEnrolledAt, v))
}

// EnrolledAtNEQ applies the NEQ predicate on the "enrolled_at" field.
func EnrolledAtNEQ(v time.Time) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNEQ(FieldEnrolledAt, v))
}

// EnrolledAtIn applies the In predicate on the "enrolled_at" field.
func EnrolledAtIn(vs ...time.Time) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldIn(FieldEnrolledAt, vs...))
}

// EnrolledAtNotIn applies the NotIn predicate on the "enrolled_at" field.
func EnrolledAtNotIn(vs ...time.Time) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldNotIn(FieldEnrolledAt, vs...))
}

// EnrolledAtGT applies the GT predicate on the "enrolled_at" field.
func EnrolledAtGT(v time.Time) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGT(FieldEnrolledAt, v))
}

// EnrolledAtGTE applies the GTE predicate on the "enrolled_at" field.
func EnrolledAtGTE(v time.Time) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldGTE(FieldEnrolledAt, v))
}

// EnrolledAtLT applies the LT predicate on the "enrolled_at" field.
func EnrolledAtLT(v time.Time) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLT(FieldEnrolledAt, v))
}

// EnrolledAtLTE applies the LTE predicate on the "enrolled_at" field.
func EnrolledAtLTE(v time.Time) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.FieldLTE(FieldEnrolledAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CourseEnrollment) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CourseEnrollment) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CourseEnrollment) predicate.CourseEnrollment {
	return predicate.CourseEnrollment(sql.NotPredicates(p))
}
