// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/challenge"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/exercise"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/predicate"
)

// ChallengeUpdate is the builder for updating Challenge entities.
type ChallengeUpdate struct {
	config
	hooks    []Hook
	mutation *ChallengeMutation
}

// Where appends a list predicates to the ChallengeUpdate builder.
func (_u *ChallengeUpdate) Where(ps ...predicate.Challenge) *ChallengeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubjectTag sets the "subject_tag" field.
func (_u *ChallengeUpdate) SetSubjectTag(v string) *ChallengeUpdate {
	_u.mutation.SetSubjectTag(v)
	return _u
}

// SetNillableSubjectTag sets the "subject_tag" field if the given value is not nil.
func (_u *ChallengeUpdate) SetNillableSubjectTag(v *string) *ChallengeUpdate {
	if v != nil {
		_u.SetSubjectTag(*v)
	}
	return _u
}

// SetPassThreshold sets the "pass_threshold" field.
func (_u *ChallengeUpdate) SetPassThreshold(v int) *ChallengeUpdate {
	_u.mutation.ResetPassThreshold()
	_u.mutation.SetPassThreshold(v)
	return _u
}

// SetNillablePassThreshold sets the "pass_threshold" field if the given value is not nil.
func (_u *ChallengeUpdate) SetNillablePassThreshold(v *int) *ChallengeUpdate {
	if v != nil {
		_u.SetPassThreshold(*v)
	}
	return _u
}

// AddPassThreshold adds value to the "pass_threshold" field.
func (_u *ChallengeUpdate) AddPassThreshold(v int) *ChallengeUpdate {
	_u.mutation.AddPassThreshold(v)
	return _u
}

// SetRemediationTargetContentNodeID sets the "remediation_target_content_node_id" field.
func (_u *ChallengeUpdate) SetRemediationTargetContentNodeID(v uuid.UUID) *ChallengeUpdate {
	_u.mutation.SetRemediationTargetContentNodeID(v)
	return _u
}

// SetNillableRemediationTargetContentNodeID sets the "remediation_target_content_node_id" field if the given value is not nil.
func (_u *ChallengeUpdate) SetNillableRemediationTargetContentNodeID(v *uuid.UUID) *ChallengeUpdate {
	if v != nil {
		_u.SetRemediationTargetContentNodeID(*v)
	}
	return _u
}

// ClearRemediationTargetContentNodeID clears the value of the "remediation_target_content_node_id" field.
func (_u *ChallengeUpdate) ClearRemediationTargetContentNodeID() *ChallengeUpdate {
	_u.mutation.ClearRemediationTargetContentNodeID()
	return _u
}

// AddExerciseIDs adds the "exercises" edge to the Exercise entity by IDs.
func (_u *ChallengeUpdate) AddExerciseIDs(ids ...uuid.UUID) *ChallengeUpdate {
	_u.mutation.AddExerciseIDs(ids...)
	return _u
}

// AddExercises adds the "exercises" edges to the Exercise entity.
func (_u *ChallengeUpdate) AddExercises(v ...*Exercise) *ChallengeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExerciseIDs(ids...)
}

// Mutation returns the ChallengeMutation object of the builder.
func (_u *ChallengeUpdate) Mutation() *ChallengeMutation {
	return _u.mutation
}

// ClearExercises clears all "exercises" edges to the Exercise entity.
func (_u *ChallengeUpdate) ClearExercises() *ChallengeUpdate {
	_u.mutation.ClearExercises()
	return _u
}

// RemoveExerciseIDs removes the "exercises" edge to Exercise entities by IDs.
func (_u *ChallengeUpdate) RemoveExerciseIDs(ids ...uuid.UUID) *ChallengeUpdate {
	_u.mutation.RemoveExerciseIDs(ids...)
	return _u
}

// RemoveExercises removes "exercises" edges to Exercise entities.
func (_u *ChallengeUpdate) RemoveExercises(v ...*Exercise) *ChallengeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExerciseIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChallengeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChallengeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChallengeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChallengeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ChallengeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(challenge.Table, challenge.Columns, sqlgraph.NewFieldSpec(challenge.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubjectTag(); ok {
		_spec.SetField(challenge.FieldSubjectTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassThreshold(); ok {
		_spec.SetField(challenge.FieldPassThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassThreshold(); ok {
		_spec.AddField(challenge.FieldPassThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RemediationTargetContentNodeID(); ok {
		_spec.SetField(challenge.FieldRemediationTargetContentNodeID, field.TypeUUID, value)
	}
	if _u.mutation.RemediationTargetContentNodeIDCleared() {
		_spec.ClearField(challenge.FieldRemediationTargetContentNodeID, field.TypeUUID)
	}
	if _u.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   challenge.ExercisesTable,
			Columns: challenge.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExercisesIDs(); len(nodes) > 0 && !_u.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   challenge.ExercisesTable,
			Columns: challenge.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExercisesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   challenge.ExercisesTable,
			Columns: challenge.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{challenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChallengeUpdateOne is the builder for updating a single Challenge entity.
type ChallengeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChallengeMutation
}

// SetSubjectTag sets the "subject_tag" field.
func (_u *ChallengeUpdateOne) SetSubjectTag(v string) *ChallengeUpdateOne {
	_u.mutation.SetSubjectTag(v)
	return _u
}

// SetNillableSubjectTag sets the "subject_tag" field if the given value is not nil.
func (_u *ChallengeUpdateOne) SetNillableSubjectTag(v *string) *ChallengeUpdateOne {
	if v != nil {
		_u.SetSubjectTag(*v)
	}
	return _u
}

// SetPassThreshold sets the "pass_threshold" field.
func (_u *ChallengeUpdateOne) SetPassThreshold(v int) *ChallengeUpdateOne {
	_u.mutation.ResetPassThreshold()
	_u.mutation.SetPassThreshold(v)
	return _u
}

// SetNillablePassThreshold sets the "pass_threshold" field if the given value is not nil.
func (_u *ChallengeUpdateOne) SetNillablePassThreshold(v *int) *ChallengeUpdateOne {
	if v != nil {
		_u.SetPassThreshold(*v)
	}
	return _u
}

// AddPassThreshold adds value to the "pass_threshold" field.
func (_u *ChallengeUpdateOne) AddPassThreshold(v int) *ChallengeUpdateOne {
	_u.mutation.AddPassThreshold(v)
	return _u
}

// SetRemediationTargetContentNodeID sets the "remediation_target_content_node_id" field.
func (_u *ChallengeUpdateOne) SetRemediationTargetContentNodeID(v uuid.UUID) *ChallengeUpdateOne {
	_u.mutation.SetRemediationTargetContentNodeID(v)
	return _u
}

// SetNillableRemediationTargetContentNodeID sets the "remediation_target_content_node_id" field if the given value is not nil.
func (_u *ChallengeUpdateOne) SetNillableRemediationTargetContentNodeID(v *uuid.UUID) *ChallengeUpdateOne {
	if v != nil {
		_u.SetRemediationTargetContentNodeID(*v)
	}
	return _u
}

// ClearRemediationTargetContentNodeID clears the value of the "remediation_target_content_node_id" field.
func (_u *ChallengeUpdateOne) ClearRemediationTargetContentNodeID() *ChallengeUpdateOne {
	_u.mutation.ClearRemediationTargetContentNodeID()
	return _u
}

// AddExerciseIDs adds the "exercises" edge to the Exercise entity by IDs.
func (_u *ChallengeUpdateOne) AddExerciseIDs(ids ...uuid.UUID) *ChallengeUpdateOne {
	_u.mutation.AddExerciseIDs(ids...)
	return _u
}

// AddExercises adds the "exercises" edges to the Exercise entity.
func (_u *ChallengeUpdateOne) AddExercises(v ...*Exercise) *ChallengeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExerciseIDs(ids...)
}

// Mutation returns the ChallengeMutation object of the builder.
func (_u *ChallengeUpdateOne) Mutation() *ChallengeMutation {
	return _u.mutation
}

// ClearExercises clears all "exercises" edges to the Exercise entity.
func (_u *ChallengeUpdateOne) ClearExercises() *ChallengeUpdateOne {
	_u.mutation.ClearExercises()
	return _u
}

// RemoveExerciseIDs removes the "exercises" edge to Exercise entities by IDs.
func (_u *ChallengeUpdateOne) RemoveExerciseIDs(ids ...uuid.UUID) *ChallengeUpdateOne {
	_u.mutation.RemoveExerciseIDs(ids...)
	return _u
}

// RemoveExercises removes "exercises" edges to Exercise entities.
func (_u *ChallengeUpdateOne) RemoveExercises(v ...*Exercise) *ChallengeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExerciseIDs(ids...)
}

// Where appends a list predicates to the ChallengeUpdate builder.
func (_u *ChallengeUpdateOne) Where(ps ...predicate.Challenge) *ChallengeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChallengeUpdateOne) Select(field string, fields ...string) *ChallengeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Challenge entity.
func (_u *ChallengeUpdateOne) Save(ctx context.Context) (*Challenge, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChallengeUpdateOne) SaveX(ctx context.Context) *Challenge {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChallengeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChallengeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ChallengeUpdateOne) sqlSave(ctx context.Context) (_node *Challenge, err error) {
	_spec := sqlgraph.NewUpdateSpec(challenge.Table, challenge.Columns, sqlgraph.NewFieldSpec(challenge.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Challenge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, challenge.FieldID)
		for _, f := range fields {
			if !challenge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != challenge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubjectTag(); ok {
		_spec.SetField(challenge.FieldSubjectTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassThreshold(); ok {
		_spec.SetField(challenge.FieldPassThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassThreshold(); ok {
		_spec.AddField(challenge.FieldPassThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RemediationTargetContentNodeID(); ok {
		_spec.SetField(challenge.FieldRemediationTargetContentNodeID, field.TypeUUID, value)
	}
	if _u.mutation.RemediationTargetContentNodeIDCleared() {
		_spec.ClearField(challenge.FieldRemediationTargetContentNodeID, field.TypeUUID)
	}
	if _u.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   challenge.ExercisesTable,
			Columns: challenge.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExercisesIDs(); len(nodes) > 0 && !_u.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   challenge.ExercisesTable,
			Columns: challenge.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExercisesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   challenge.ExercisesTable,
			Columns: challenge.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Challenge{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{challenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
