// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/chorddefinition"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/chordvoicing"
)

// ChordDefinitionCreate is the builder for creating a ChordDefinition entity.
type ChordDefinitionCreate struct {
	config
	mutation *ChordDefinitionMutation
	hooks    []Hook
}

// SetCanonicalSymbol sets the "canonical_symbol" field.
func (_c *ChordDefinitionCreate) SetCanonicalSymbol(v string) *ChordDefinitionCreate {
	_c.mutation.SetCanonicalSymbol(v)
	return _c
}

// SetRoot sets the "root" field.
func (_c *ChordDefinitionCreate) SetRoot(v string) *ChordDefinitionCreate {
	_c.mutation.SetRoot(v)
	return _c
}

// SetRootPitchClass sets the "root_pitch_class" field.
func (_c *ChordDefinitionCreate) SetRootPitchClass(v int) *ChordDefinitionCreate {
	_c.mutation.SetRootPitchClass(v)
	return _c
}

// SetQuality sets the "quality" field.
func (_c *ChordDefinitionCreate) SetQuality(v string) *ChordDefinitionCreate {
	_c.mutation.SetQuality(v)
	return _c
}

// SetFormula sets the "formula" field.
func (_c *ChordDefinitionCreate) SetFormula(v []string) *ChordDefinitionCreate {
	_c.mutation.SetFormula(v)
	return _c
}

// SetOmittable sets the "omittable" field.
func (_c *ChordDefinitionCreate) SetOmittable(v []string) *ChordDefinitionCreate {
	_c.mutation.SetOmittable(v)
	return _c
}

// SetBass sets the "bass" field.
func (_c *ChordDefinitionCreate) SetBass(v string) *ChordDefinitionCreate {
	_c.mutation.SetBass(v)
	return _c
}

// SetNillableBass sets the "bass" field if the given value is not nil.
func (_c *ChordDefinitionCreate) SetNillableBass(v *string) *ChordDefinitionCreate {
	if v != nil {
		_c.SetBass(*v)
	}
	return _c
}

// SetBassPitchClass sets the "bass_pitch_class" field.
func (_c *ChordDefinitionCreate) SetBassPitchClass(v int) *ChordDefinitionCreate {
	_c.mutation.SetBassPitchClass(v)
	return _c
}

// SetNillableBassPitchClass sets the "bass_pitch_class" field if the given value is not nil.
func (_c *ChordDefinitionCreate) SetNillableBassPitchClass(v *int) *ChordDefinitionCreate {
	if v != nil {
		_c.SetBassPitchClass(*v)
	}
	return _c
}

// SetAliases sets the "aliases" field.
func (_c *ChordDefinitionCreate) SetAliases(v []string) *ChordDefinitionCreate {
	_c.mutation.SetAliases(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ChordDefinitionCreate) SetID(v uuid.UUID) *ChordDefinitionCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddVoicingIDs adds the "voicings" edge to the ChordVoicing entity by IDs.
func (_c *ChordDefinitionCreate) AddVoicingIDs(ids ...uuid.UUID) *ChordDefinitionCreate {
	_c.mutation.AddVoicingIDs(ids...)
	return _c
}

// AddVoicings adds the "voicings" edges to the ChordVoicing entity.
func (_c *ChordDefinitionCreate) AddVoicings(v ...*ChordVoicing) *ChordDefinitionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVoicingIDs(ids...)
}

// Mutation returns the ChordDefinitionMutation object of the builder.
func (_c *ChordDefinitionCreate) Mutation() *ChordDefinitionMutation {
	return _c.mutation
}

// Save creates the ChordDefinition in the database.
func (_c *ChordDefinitionCreate) Save(ctx context.Context) (*ChordDefinition, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChordDefinitionCreate) SaveX(ctx context.Context) *ChordDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChordDefinitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChordDefinitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChordDefinitionCreate) check() error {
	if _, ok := _c.mutation.CanonicalSymbol(); !ok {
		return &ValidationError{Name: "canonical_symbol", err: errors.New(`ent: missing required field "ChordDefinition.canonical_symbol"`)}
	}
	if v, ok := _c.mutation.CanonicalSymbol(); ok {
		if err := chorddefinition.CanonicalSymbolValidator(v); err != nil {
			return &ValidationError{Name: "canonical_symbol", err: fmt.Errorf(`ent: validator failed for field "ChordDefinition.canonical_symbol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Root(); !ok {
		return &ValidationError{Name: "root", err: errors.New(`ent: missing required field "ChordDefinition.root"`)}
	}
	if v, ok := _c.mutation.Root(); ok {
		if err := chorddefinition.RootValidator(v); err != nil {
			return &ValidationError{Name: "root", err: fmt.Errorf(`ent: validator failed for field "ChordDefinition.root": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RootPitchClass(); !ok {
		return &ValidationError{Name: "root_pitch_class", err: errors.New(`ent: missing required field "ChordDefinition.root_pitch_class"`)}
	}
	if v, ok := _c.mutation.RootPitchClass(); ok {
		if err := chorddefinition.RootPitchClassValidator(v); err != nil {
			return &ValidationError{Name: "root_pitch_class", err: fmt.Errorf(`ent: validator failed for field "ChordDefinition.root_pitch_class": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quality(); !ok {
		return &ValidationError{Name: "quality", err: errors.New(`ent: missing required field "ChordDefinition.quality"`)}
	}
	if v, ok := _c.mutation.Quality(); ok {
		if err := chorddefinition.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "ChordDefinition.quality": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Formula(); !ok {
		return &ValidationError{Name: "formula", err: errors.New(`ent: missing required field "ChordDefinition.formula"`)}
	}
	if _, ok := _c.mutation.Omittable(); !ok {
		return &ValidationError{Name: "omittable", err: errors.New(`ent: missing required field "ChordDefinition.omittable"`)}
	}
	if v, ok := _c.mutation.Bass(); ok {
		if err := chorddefinition.BassValidator(v); err != nil {
			return &ValidationError{Name: "bass", err: fmt.Errorf(`ent: validator failed for field "ChordDefinition.bass": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BassPitchClass(); ok {
		if err := chorddefinition.BassPitchClassValidator(v); err != nil {
			return &ValidationError{Name: "bass_pitch_class", err: fmt.Errorf(`ent: validator failed for field "ChordDefinition.bass_pitch_class": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Aliases(); !ok {
		return &ValidationError{Name: "aliases", err: errors.New(`ent: missing required field "ChordDefinition.aliases"`)}
	}
	return nil
}

func (_c *ChordDefinitionCreate) sqlSave(ctx context.Context) (*ChordDefinition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChordDefinitionCreate) createSpec() (*ChordDefinition, *sqlgraph.CreateSpec) {
	var (
		_node = &ChordDefinition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chorddefinition.Table, sqlgraph.NewFieldSpec(chorddefinition.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CanonicalSymbol(); ok {
		_spec.SetField(chorddefinition.FieldCanonicalSymbol, field.TypeString, value)
		_node.CanonicalSymbol = value
	}
	if value, ok := _c.mutation.Root(); ok {
		_spec.SetField(chorddefinition.FieldRoot, field.TypeString, value)
		_node.Root = value
	}
	if value, ok := _c.mutation.RootPitchClass(); ok {
		_spec.SetField(chorddefinition.FieldRootPitchClass, field.TypeInt, value)
		_node.RootPitchClass = value
	}
	if value, ok := _c.mutation.Quality(); ok {
		_spec.SetField(chorddefinition.FieldQuality, field.TypeString, value)
		_node.Quality = value
	}
	if value, ok := _c.mutation.Formula(); ok {
		_spec.SetField(chorddefinition.FieldFormula, field.TypeJSON, value)
		_node.Formula = value
	}
	if value, ok := _c.mutation.Omittable(); ok {
		_spec.SetField(chorddefinition.FieldOmittable, field.TypeJSON, value)
		_node.Omittable = value
	}
	if value, ok := _c.mutation.Bass(); ok {
		_spec.SetField(chorddefinition.FieldBass, field.TypeString, value)
		_node.Bass = &value
	}
	if value, ok := _c.mutation.BassPitchClass(); ok {
		_spec.SetField(chorddefinition.FieldBassPitchClass, field.TypeInt, value)
		_node.BassPitchClass = &value
	}
	if value, ok := _c.mutation.Aliases(); ok {
		_spec.SetField(chorddefinition.FieldAliases, field.TypeJSON, value)
		_node.Aliases = value
	}
	if nodes := _c.mutation.VoicingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   chorddefinition.VoicingsTable,
			Columns: []string{chorddefinition.VoicingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chordvoicing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChordDefinitionCreateBulk is the builder for creating many ChordDefinition entities in bulk.
type ChordDefinitionCreateBulk struct {
	config
	err      error
	builders []*ChordDefinitionCreate
}

// Save creates the ChordDefinition entities in the database.
func (_c *ChordDefinitionCreateBulk) Save(ctx context.Context) ([]*ChordDefinition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChordDefinition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChordDefinitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChordDefinitionCreateBulk) SaveX(ctx context.Context) []*ChordDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChordDefinitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChordDefinitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
