// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/concept"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/contentnode"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/contentnodeconcept"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/exercise"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/exerciseconcept"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/predicate"
)

// ConceptUpdate is the builder for updating Concept entities.
type ConceptUpdate struct {
	config
	hooks    []Hook
	mutation *ConceptMutation
}

// Where appends a list predicates to the ConceptUpdate builder.
func (_u *ConceptUpdate) Where(ps ...predicate.Concept) *ConceptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ConceptUpdate) SetName(v string) *ConceptUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ConceptUpdate) SetNillableName(v *string) *ConceptUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *ConceptUpdate) SetParentID(v uuid.UUID) *ConceptUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ConceptUpdate) SetNillableParentID(v *uuid.UUID) *ConceptUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *ConceptUpdate) ClearParentID() *ConceptUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// AddChildIDs adds the "children" edge to the Concept entity by IDs.
func (_u *ConceptUpdate) AddChildIDs(ids ...uuid.UUID) *ConceptUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Concept entity.
func (_u *ConceptUpdate) AddChildren(v ...*Concept) *ConceptUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParent sets the "parent" edge to the Concept entity.
func (_u *ConceptUpdate) SetParent(v *Concept) *ConceptUpdate {
	return _u.SetParentID(v.ID)
}

// AddContentNodeIDs adds the "content_nodes" edge to the ContentNode entity by IDs.
func (_u *ConceptUpdate) AddContentNodeIDs(ids ...uuid.UUID) *ConceptUpdate {
	_u.mutation.AddContentNodeIDs(ids...)
	return _u
}

// AddContentNodes adds the "content_nodes" edges to the ContentNode entity.
func (_u *ConceptUpdate) AddContentNodes(v ...*ContentNode) *ConceptUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContentNodeIDs(ids...)
}

// AddExerciseIDs adds the "exercises" edge to the Exercise entity by IDs.
func (_u *ConceptUpdate) AddExerciseIDs(ids ...uuid.UUID) *ConceptUpdate {
	_u.mutation.AddExerciseIDs(ids...)
	return _u
}

// AddExercises adds the "exercises" edges to the Exercise entity.
func (_u *ConceptUpdate) AddExercises(v ...*Exercise) *ConceptUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExerciseIDs(ids...)
}

// AddContentNodeConceptIDs adds the "content_node_concepts" edge to the ContentNodeConcept entity by IDs.
func (_u *ConceptUpdate) AddContentNodeConceptIDs(ids ...int) *ConceptUpdate {
	_u.mutation.AddContentNodeConceptIDs(ids...)
	return _u
}

// AddContentNodeConcepts adds the "content_node_concepts" edges to the ContentNodeConcept entity.
func (_u *ConceptUpdate) AddContentNodeConcepts(v ...*ContentNodeConcept) *ConceptUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContentNodeConceptIDs(ids...)
}

// AddExerciseConceptIDs adds the "exercise_concepts" edge to the ExerciseConcept entity by IDs.
func (_u *ConceptUpdate) AddExerciseConceptIDs(ids ...int) *ConceptUpdate {
	_u.mutation.AddExerciseConceptIDs(ids...)
	return _u
}

// AddExerciseConcepts adds the "exercise_concepts" edges to the ExerciseConcept entity.
func (_u *ConceptUpdate) AddExerciseConcepts(v ...*ExerciseConcept) *ConceptUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExerciseConceptIDs(ids...)
}

// Mutation returns the ConceptMutation object of the builder.
func (_u *ConceptUpdate) Mutation() *ConceptMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Concept entity.
func (_u *ConceptUpdate) ClearChildren() *ConceptUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Concept entities by IDs.
func (_u *ConceptUpdate) RemoveChildIDs(ids ...uuid.UUID) *ConceptUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Concept entities.
func (_u *ConceptUpdate) RemoveChildren(v ...*Concept) *ConceptUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Concept entity.
func (_u *ConceptUpdate) ClearParent() *ConceptUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearContentNodes clears all "content_nodes" edges to the ContentNode entity.
func (_u *ConceptUpdate) ClearContentNodes() *ConceptUpdate {
	_u.mutation.ClearContentNodes()
	return _u
}

// RemoveContentNodeIDs removes the "content_nodes" edge to ContentNode entities by IDs.
func (_u *ConceptUpdate) RemoveContentNodeIDs(ids ...uuid.UUID) *ConceptUpdate {
	_u.mutation.RemoveContentNodeIDs(ids...)
	return _u
}

// RemoveContentNodes removes "content_nodes" edges to ContentNode entities.
func (_u *ConceptUpdate) RemoveContentNodes(v ...*ContentNode) *ConceptUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContentNodeIDs(ids...)
}

// ClearExercises clears all "exercises" edges to the Exercise entity.
func (_u *ConceptUpdate) ClearExercises() *ConceptUpdate {
	_u.mutation.ClearExercises()
	return _u
}

// RemoveExerciseIDs removes the "exercises" edge to Exercise entities by IDs.
func (_u *ConceptUpdate) RemoveExerciseIDs(ids ...uuid.UUID) *ConceptUpdate {
	_u.mutation.RemoveExerciseIDs(ids...)
	return _u
}

// RemoveExercises removes "exercises" edges to Exercise entities.
func (_u *ConceptUpdate) RemoveExercises(v ...*Exercise) *ConceptUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExerciseIDs(ids...)
}

// ClearContentNodeConcepts clears all "content_node_concepts" edges to the ContentNodeConcept entity.
func (_u *ConceptUpdate) ClearContentNodeConcepts() *ConceptUpdate {
	_u.mutation.ClearContentNodeConcepts()
	return _u
}

// RemoveContentNodeConceptIDs removes the "content_node_concepts" edge to ContentNodeConcept entities by IDs.
func (_u *ConceptUpdate) RemoveContentNodeConceptIDs(ids ...int) *ConceptUpdate {
	_u.mutation.RemoveContentNodeConceptIDs(ids...)
	return _u
}

// RemoveContentNodeConcepts removes "content_node_concepts" edges to ContentNodeConcept entities.
func (_u *ConceptUpdate) RemoveContentNodeConcepts(v ...*ContentNodeConcept) *ConceptUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContentNodeConceptIDs(ids...)
}

// ClearExerciseConcepts clears all "exercise_concepts" edges to the ExerciseConcept entity.
func (_u *ConceptUpdate) ClearExerciseConcepts() *ConceptUpdate {
	_u.mutation.ClearExerciseConcepts()
	return _u
}

// RemoveExerciseConceptIDs removes the "exercise_concepts" edge to ExerciseConcept entities by IDs.
func (_u *ConceptUpdate) RemoveExerciseConceptIDs(ids ...int) *ConceptUpdate {
	_u.mutation.RemoveExerciseConceptIDs(ids...)
	return _u
}

// RemoveExerciseConcepts removes "exercise_concepts" edges to ExerciseConcept entities.
func (_u *ConceptUpdate) RemoveExerciseConcepts(v ...*ExerciseConcept) *ConceptUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExerciseConceptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConceptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConceptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConceptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConceptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ConceptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(concept.Table, concept.Columns, sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(concept.FieldName, field.TypeString, value)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ChildrenTable,
			Columns: []string{concept.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ChildrenTable,
			Columns: []string{concept.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ChildrenTable,
			Columns: []string{concept.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   concept.ParentTable,
			Columns: []string{concept.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   concept.ParentTable,
			Columns: []string{concept.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContentNodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ContentNodesTable,
			Columns: concept.ContentNodesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnode.FieldID, field.TypeUUID),
			},
		}
		createE := &ContentNodeConceptCreate{config: _u.config, mutation: newContentNodeConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContentNodesIDs(); len(nodes) > 0 && !_u.mutation.ContentNodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ContentNodesTable,
			Columns: concept.ContentNodesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ContentNodeConceptCreate{config: _u.config, mutation: newContentNodeConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContentNodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ContentNodesTable,
			Columns: concept.ContentNodesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ContentNodeConceptCreate{config: _u.config, mutation: newContentNodeConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ExercisesTable,
			Columns: concept.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		createE := &ExerciseConceptCreate{config: _u.config, mutation: newExerciseConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExercisesIDs(); len(nodes) > 0 && !_u.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ExercisesTable,
			Columns: concept.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ExerciseConceptCreate{config: _u.config, mutation: newExerciseConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExercisesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ExercisesTable,
			Columns: concept.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ExerciseConceptCreate{config: _u.config, mutation: newExerciseConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContentNodeConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ContentNodeConceptsTable,
			Columns: []string{concept.ContentNodeConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnodeconcept.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContentNodeConceptsIDs(); len(nodes) > 0 && !_u.mutation.ContentNodeConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ContentNodeConceptsTable,
			Columns: []string{concept.ContentNodeConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnodeconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContentNodeConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ContentNodeConceptsTable,
			Columns: []string{concept.ContentNodeConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnodeconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExerciseConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ExerciseConceptsTable,
			Columns: []string{concept.ExerciseConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exerciseconcept.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExerciseConceptsIDs(); len(nodes) > 0 && !_u.mutation.ExerciseConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ExerciseConceptsTable,
			Columns: []string{concept.ExerciseConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exerciseconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExerciseConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ExerciseConceptsTable,
			Columns: []string{concept.ExerciseConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exerciseconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{concept.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConceptUpdateOne is the builder for updating a single Concept entity.
type ConceptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConceptMutation
}

// SetName sets the "name" field.
func (_u *ConceptUpdateOne) SetName(v string) *ConceptUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ConceptUpdateOne) SetNillableName(v *string) *ConceptUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *ConceptUpdateOne) SetParentID(v uuid.UUID) *ConceptUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ConceptUpdateOne) SetNillableParentID(v *uuid.UUID) *ConceptUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *ConceptUpdateOne) ClearParentID() *ConceptUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// AddChildIDs adds the "children" edge to the Concept entity by IDs.
func (_u *ConceptUpdateOne) AddChildIDs(ids ...uuid.UUID) *ConceptUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Concept entity.
func (_u *ConceptUpdateOne) AddChildren(v ...*Concept) *ConceptUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParent sets the "parent" edge to the Concept entity.
func (_u *ConceptUpdateOne) SetParent(v *Concept) *ConceptUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddContentNodeIDs adds the "content_nodes" edge to the ContentNode entity by IDs.
func (_u *ConceptUpdateOne) AddContentNodeIDs(ids ...uuid.UUID) *ConceptUpdateOne {
	_u.mutation.AddContentNodeIDs(ids...)
	return _u
}

// AddContentNodes adds the "content_nodes" edges to the ContentNode entity.
func (_u *ConceptUpdateOne) AddContentNodes(v ...*ContentNode) *ConceptUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContentNodeIDs(ids...)
}

// AddExerciseIDs adds the "exercises" edge to the Exercise entity by IDs.
func (_u *ConceptUpdateOne) AddExerciseIDs(ids ...uuid.UUID) *ConceptUpdateOne {
	_u.mutation.AddExerciseIDs(ids...)
	return _u
}

// AddExercises adds the "exercises" edges to the Exercise entity.
func (_u *ConceptUpdateOne) AddExercises(v ...*Exercise) *ConceptUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExerciseIDs(ids...)
}

// AddContentNodeConceptIDs adds the "content_node_concepts" edge to the ContentNodeConcept entity by IDs.
func (_u *ConceptUpdateOne) AddContentNodeConceptIDs(ids ...int) *ConceptUpdateOne {
	_u.mutation.AddContentNodeConceptIDs(ids...)
	return _u
}

// AddContentNodeConcepts adds the "content_node_concepts" edges to the ContentNodeConcept entity.
func (_u *ConceptUpdateOne) AddContentNodeConcepts(v ...*ContentNodeConcept) *ConceptUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContentNodeConceptIDs(ids...)
}

// AddExerciseConceptIDs adds the "exercise_concepts" edge to the ExerciseConcept entity by IDs.
func (_u *ConceptUpdateOne) AddExerciseConceptIDs(ids ...int) *ConceptUpdateOne {
	_u.mutation.AddExerciseConceptIDs(ids...)
	return _u
}

// AddExerciseConcepts adds the "exercise_concepts" edges to the ExerciseConcept entity.
func (_u *ConceptUpdateOne) AddExerciseConcepts(v ...*ExerciseConcept) *ConceptUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExerciseConceptIDs(ids...)
}

// Mutation returns the ConceptMutation object of the builder.
func (_u *ConceptUpdateOne) Mutation() *ConceptMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Concept entity.
func (_u *ConceptUpdateOne) ClearChildren() *ConceptUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Concept entities by IDs.
func (_u *ConceptUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *ConceptUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Concept entities.
func (_u *ConceptUpdateOne) RemoveChildren(v ...*Concept) *ConceptUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Concept entity.
func (_u *ConceptUpdateOne) ClearParent() *ConceptUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearContentNodes clears all "content_nodes" edges to the ContentNode entity.
func (_u *ConceptUpdateOne) ClearContentNodes() *ConceptUpdateOne {
	_u.mutation.ClearContentNodes()
	return _u
}

// RemoveContentNodeIDs removes the "content_nodes" edge to ContentNode entities by IDs.
func (_u *ConceptUpdateOne) RemoveContentNodeIDs(ids ...uuid.UUID) *ConceptUpdateOne {
	_u.mutation.RemoveContentNodeIDs(ids...)
	return _u
}

// RemoveContentNodes removes "content_nodes" edges to ContentNode entities.
func (_u *ConceptUpdateOne) RemoveContentNodes(v ...*ContentNode) *ConceptUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContentNodeIDs(ids...)
}

// ClearExercises clears all "exercises" edges to the Exercise entity.
func (_u *ConceptUpdateOne) ClearExercises() *ConceptUpdateOne {
	_u.mutation.ClearExercises()
	return _u
}

// RemoveExerciseIDs removes the "exercises" edge to Exercise entities by IDs.
func (_u *ConceptUpdateOne) RemoveExerciseIDs(ids ...uuid.UUID) *ConceptUpdateOne {
	_u.mutation.RemoveExerciseIDs(ids...)
	return _u
}

// RemoveExercises removes "exercises" edges to Exercise entities.
func (_u *ConceptUpdateOne) RemoveExercises(v ...*Exercise) *ConceptUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExerciseIDs(ids...)
}

// ClearContentNodeConcepts clears all "content_node_concepts" edges to the ContentNodeConcept entity.
func (_u *ConceptUpdateOne) ClearContentNodeConcepts() *ConceptUpdateOne {
	_u.mutation.ClearContentNodeConcepts()
	return _u
}

// RemoveContentNodeConceptIDs removes the "content_node_concepts" edge to ContentNodeConcept entities by IDs.
func (_u *ConceptUpdateOne) RemoveContentNodeConceptIDs(ids ...int) *ConceptUpdateOne {
	_u.mutation.RemoveContentNodeConceptIDs(ids...)
	return _u
}

// RemoveContentNodeConcepts removes "content_node_concepts" edges to ContentNodeConcept entities.
func (_u *ConceptUpdateOne) RemoveContentNodeConcepts(v ...*ContentNodeConcept) *ConceptUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContentNodeConceptIDs(ids...)
}

// ClearExerciseConcepts clears all "exercise_concepts" edges to the ExerciseConcept entity.
func (_u *ConceptUpdateOne) ClearExerciseConcepts() *ConceptUpdateOne {
	_u.mutation.ClearExerciseConcepts()
	return _u
}

// RemoveExerciseConceptIDs removes the "exercise_concepts" edge to ExerciseConcept entities by IDs.
func (_u *ConceptUpdateOne) RemoveExerciseConceptIDs(ids ...int) *ConceptUpdateOne {
	_u.mutation.RemoveExerciseConceptIDs(ids...)
	return _u
}

// RemoveExerciseConcepts removes "exercise_concepts" edges to ExerciseConcept entities.
func (_u *ConceptUpdateOne) RemoveExerciseConcepts(v ...*ExerciseConcept) *ConceptUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExerciseConceptIDs(ids...)
}

// Where appends a list predicates to the ConceptUpdate builder.
func (_u *ConceptUpdateOne) Where(ps ...predicate.Concept) *ConceptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConceptUpdateOne) Select(field string, fields ...string) *ConceptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Concept entity.
func (_u *ConceptUpdateOne) Save(ctx context.Context) (*Concept, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConceptUpdateOne) SaveX(ctx context.Context) *Concept {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConceptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConceptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ConceptUpdateOne) sqlSave(ctx context.Context) (_node *Concept, err error) {
	_spec := sqlgraph.NewUpdateSpec(concept.Table, concept.Columns, sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Concept.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, concept.FieldID)
		for _, f := range fields {
			if !concept.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != concept.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(concept.FieldName, field.TypeString, value)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ChildrenTable,
			Columns: []string{concept.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ChildrenTable,
			Columns: []string{concept.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ChildrenTable,
			Columns: []string{concept.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   concept.ParentTable,
			Columns: []string{concept.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   concept.ParentTable,
			Columns: []string{concept.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContentNodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ContentNodesTable,
			Columns: concept.ContentNodesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnode.FieldID, field.TypeUUID),
			},
		}
		createE := &ContentNodeConceptCreate{config: _u.config, mutation: newContentNodeConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContentNodesIDs(); len(nodes) > 0 && !_u.mutation.ContentNodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ContentNodesTable,
			Columns: concept.ContentNodesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ContentNodeConceptCreate{config: _u.config, mutation: newContentNodeConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContentNodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ContentNodesTable,
			Columns: concept.ContentNodesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ContentNodeConceptCreate{config: _u.config, mutation: newContentNodeConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ExercisesTable,
			Columns: concept.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		createE := &ExerciseConceptCreate{config: _u.config, mutation: newExerciseConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExercisesIDs(); len(nodes) > 0 && !_u.mutation.ExercisesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ExercisesTable,
			Columns: concept.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ExerciseConceptCreate{config: _u.config, mutation: newExerciseConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExercisesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ExercisesTable,
			Columns: concept.ExercisesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ExerciseConceptCreate{config: _u.config, mutation: newExerciseConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContentNodeConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ContentNodeConceptsTable,
			Columns: []string{concept.ContentNodeConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnodeconcept.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContentNodeConceptsIDs(); len(nodes) > 0 && !_u.mutation.ContentNodeConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ContentNodeConceptsTable,
			Columns: []string{concept.ContentNodeConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnodeconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContentNodeConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ContentNodeConceptsTable,
			Columns: []string{concept.ContentNodeConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnodeconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExerciseConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ExerciseConceptsTable,
			Columns: []string{concept.ExerciseConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exerciseconcept.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExerciseConceptsIDs(); len(nodes) > 0 && !_u.mutation.ExerciseConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ExerciseConceptsTable,
			Columns: []string{concept.ExerciseConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exerciseconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExerciseConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   concept.ExerciseConceptsTable,
			Columns: []string{concept.ExerciseConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exerciseconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Concept{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{concept.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
