// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/contentnodeexercise"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/predicate"
)

// ContentNodeExerciseDelete is the builder for deleting a ContentNodeExercise entity.
type ContentNodeExerciseDelete struct {
	config
	hooks    []Hook
	mutation *ContentNodeExerciseMutation
}

// Where appends a list predicates to the ContentNodeExerciseDelete builder.
func (_d *ContentNodeExerciseDelete) Where(ps ...predicate.ContentNodeExercise) *ContentNodeExerciseDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ContentNodeExerciseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContentNodeExerciseDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ContentNodeExerciseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(contentnodeexercise.Table, sqlgraph.NewFieldSpec(contentnodeexercise.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ContentNodeExerciseDeleteOne is the builder for deleting a single ContentNodeExercise entity.
type ContentNodeExerciseDeleteOne struct {
	_d *ContentNodeExerciseDelete
}

// Where appends a list predicates to the ContentNodeExerciseDelete builder.
func (_d *ContentNodeExerciseDeleteOne) Where(ps ...predicate.ContentNodeExercise) *ContentNodeExerciseDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ContentNodeExerciseDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{contentnodeexercise.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContentNodeExerciseDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
