// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/contentnode"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/contentnodelanguage"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/language"
)

// ContentNodeLanguageCreate is the builder for creating a ContentNodeLanguage entity.
type ContentNodeLanguageCreate struct {
	config
	mutation *ContentNodeLanguageMutation
	hooks    []Hook
}

// SetContentNodeID sets the "content_node_id" field.
func (_c *ContentNodeLanguageCreate) SetContentNodeID(v uuid.UUID) *ContentNodeLanguageCreate {
	_c.mutation.SetContentNodeID(v)
	return _c
}

// SetLanguageID sets the "language_id" field.
func (_c *ContentNodeLanguageCreate) SetLanguageID(v uuid.UUID) *ContentNodeLanguageCreate {
	_c.mutation.SetLanguageID(v)
	return _c
}

// SetLinkedAt sets the "linked_at" field.
func (_c *ContentNodeLanguageCreate) SetLinkedAt(v time.Time) *ContentNodeLanguageCreate {
	_c.mutation.SetLinkedAt(v)
	return _c
}

// SetNillableLinkedAt sets the "linked_at" field if the given value is not nil.
func (_c *ContentNodeLanguageCreate) SetNillableLinkedAt(v *time.Time) *ContentNodeLanguageCreate {
	if v != nil {
		_c.SetLinkedAt(*v)
	}
	return _c
}

// SetContentNode sets the "content_node" edge to the ContentNode entity.
func (_c *ContentNodeLanguageCreate) SetContentNode(v *ContentNode) *ContentNodeLanguageCreate {
	return _c.SetContentNodeID(v.ID)
}

// SetLanguage sets the "language" edge to the Language entity.
func (_c *ContentNodeLanguageCreate) SetLanguage(v *Language) *ContentNodeLanguageCreate {
	return _c.SetLanguageID(v.ID)
}

// Mutation returns the ContentNodeLanguageMutation object of the builder.
func (_c *ContentNodeLanguageCreate) Mutation() *ContentNodeLanguageMutation {
	return _c.mutation
}

// Save creates the ContentNodeLanguage in the database.
func (_c *ContentNodeLanguageCreate) Save(ctx context.Context) (*ContentNodeLanguage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContentNodeLanguageCreate) SaveX(ctx context.Context) *ContentNodeLanguage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContentNodeLanguageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContentNodeLanguageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContentNodeLanguageCreate) defaults() {
	if _, ok := _c.mutation.LinkedAt(); !ok {
		v := contentnodelanguage.DefaultLinkedAt()
		_c.mutation.SetLinkedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContentNodeLanguageCreate) check() error {
	if _, ok := _c.mutation.ContentNodeID(); !ok {
		return &ValidationError{Name: "content_node_id", err: errors.New(`ent: missing required field "ContentNodeLanguage.content_node_id"`)}
	}
	if _, ok := _c.mutation.LanguageID(); !ok {
		return &ValidationError{Name: "language_id", err: errors.New(`ent: missing required field "ContentNodeLanguage.language_id"`)}
	}
	if _, ok := _c.mutation.LinkedAt(); !ok {
		return &ValidationError{Name: "linked_at", err: errors.New(`ent: missing required field "ContentNodeLanguage.linked_at"`)}
	}
	if len(_c.mutation.ContentNodeIDs()) == 0 {
		return &ValidationError{Name: "content_node", err: errors.New(`ent: missing required edge "ContentNodeLanguage.content_node"`)}
	}
	if len(_c.mutation.LanguageIDs()) == 0 {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required edge "ContentNodeLanguage.language"`)}
	}
	return nil
}

func (_c *ContentNodeLanguageCreate) sqlSave(ctx context.Context) (*ContentNodeLanguage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContentNodeLanguageCreate) createSpec() (*ContentNodeLanguage, *sqlgraph.CreateSpec) {
	var (
		_node = &ContentNodeLanguage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contentnodelanguage.Table, sqlgraph.NewFieldSpec(contentnodelanguage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.LinkedAt(); ok {
		_spec.SetField(contentnodelanguage.FieldLinkedAt, field.TypeTime, value)
		_node.LinkedAt = value
	}
	if nodes := _c.mutation.ContentNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   contentnodelanguage.ContentNodeTable,
			Columns: []string{contentnodelanguage.ContentNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contentnode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ContentNodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LanguageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   contentnodelanguage.LanguageTable,
			Columns: []string{contentnodelanguage.LanguageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(language.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LanguageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ContentNodeLanguageCreateBulk is the builder for creating many ContentNodeLanguage entities in bulk.
type ContentNodeLanguageCreateBulk struct {
	config
	err      error
	builders []*ContentNodeLanguageCreate
}

// Save creates the ContentNodeLanguage entities in the database.
func (_c *ContentNodeLanguageCreateBulk) Save(ctx context.Context) ([]*ContentNodeLanguage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContentNodeLanguage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContentNodeLanguageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContentNodeLanguageCreateBulk) SaveX(ctx context.Context) []*ContentNodeLanguage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContentNodeLanguageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContentNodeLanguageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
