// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/contentnode"
)

// ContentNode is the model entity for the ContentNode schema.
type ContentNode struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TeacherID holds the value of the "teacher_id" field.
	TeacherID uuid.UUID `json:"teacher_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType contentnode.ContentType `json:"content_type,omitempty"`
	// MediaURL holds the value of the "media_url" field.
	MediaURL *string `json:"media_url,omitempty"`
	// RichContent holds the value of the "rich_content" field.
	RichContent *string `json:"rich_content,omitempty"`
	// DifficultyLevel holds the value of the "difficulty_level" field.
	DifficultyLevel contentnode.DifficultyLevel `json:"difficulty_level,omitempty"`
	// ReviewState holds the value of the "review_state" field.
	ReviewState contentnode.ReviewState `json:"review_state,omitempty"`
	// ThumbnailURL holds the value of the "thumbnail_url" field.
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ContentNodeQuery when eager-loading is set.
	Edges        ContentNodeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ContentNodeEdges holds the relations/edges for other nodes in the graph.
type ContentNodeEdges struct {
	// PathExercises holds the value of the path_exercises edge.
	PathExercises []*Exercise `json:"path_exercises,omitempty"`
	// Languages holds the value of the languages edge.
	Languages []*Language `json:"languages,omitempty"`
	// Skills holds the value of the skills edge.
	Skills []*Skill `json:"skills,omitempty"`
	// Concepts holds the value of the concepts edge.
	Concepts []*Concept `json:"concepts,omitempty"`
	// Instruments holds the value of the instruments edge.
	Instruments []*Instrument `json:"instruments,omitempty"`
	// ContentNodeExercises holds the value of the content_node_exercises edge.
	ContentNodeExercises []*ContentNodeExercise `json:"content_node_exercises,omitempty"`
	// ContentNodeLanguages holds the value of the content_node_languages edge.
	ContentNodeLanguages []*ContentNodeLanguage `json:"content_node_languages,omitempty"`
	// ContentNodeSkills holds the value of the content_node_skills edge.
	ContentNodeSkills []*ContentNodeSkill `json:"content_node_skills,omitempty"`
	// ContentNodeConcepts holds the value of the content_node_concepts edge.
	ContentNodeConcepts []*ContentNodeConcept `json:"content_node_concepts,omitempty"`
	// ContentNodeInstruments holds the value of the content_node_instruments edge.
	ContentNodeInstruments []*ContentNodeInstrument `json:"content_node_instruments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [10]bool
}

// PathExercisesOrErr returns the PathExercises value or an error if the edge
// was not loaded in eager-loading.
func (e ContentNodeEdges) PathExercisesOrErr() ([]*Exercise, error) {
	if e.loadedTypes[0] {
		return e.PathExercises, nil
	}
	return nil, &NotLoadedError{edge: "path_exercises"}
}

// LanguagesOrErr returns the Languages value or an error if the edge
// was not loaded in eager-loading.
func (e ContentNodeEdges) LanguagesOrErr() ([]*Language, error) {
	if e.loadedTypes[1] {
		return e.Languages, nil
	}
	return nil, &NotLoadedError{edge: "languages"}
}

// SkillsOrErr returns the Skills value or an error if the edge
// was not loaded in eager-loading.
func (e ContentNodeEdges) SkillsOrErr() ([]*Skill, error) {
	if e.loadedTypes[2] {
		return e.Skills, nil
	}
	return nil, &NotLoadedError{edge: "skills"}
}

// ConceptsOrErr returns the Concepts value or an error if the edge
// was not loaded in eager-loading.
func (e ContentNodeEdges) ConceptsOrErr() ([]*Concept, error) {
	if e.loadedTypes[3] {
		return e.Concepts, nil
	}
	return nil, &NotLoadedError{edge: "concepts"}
}

// InstrumentsOrErr returns the Instruments value or an error if the edge
// was not loaded in eager-loading.
func (e ContentNodeEdges) InstrumentsOrErr() ([]*Instrument, error) {
	if e.loadedTypes[4] {
		return e.Instruments, nil
	}
	return nil, &NotLoadedError{edge: "instruments"}
}

// ContentNodeExercisesOrErr returns the ContentNodeExercises value or an error if the edge
// was not loaded in eager-loading.
func (e ContentNodeEdges) ContentNodeExercisesOrErr() ([]*ContentNodeExercise, error) {
	if e.loadedTypes[5] {
		return e.ContentNodeExercises, nil
	}
	return nil, &NotLoadedError{edge: "content_node_exercises"}
}

// ContentNodeLanguagesOrErr returns the ContentNodeLanguages value or an error if the edge
// was not loaded in eager-loading.
func (e ContentNodeEdges) ContentNodeLanguagesOrErr() ([]*ContentNodeLanguage, error) {
	if e.loadedTypes[6] {
		return e.ContentNodeLanguages, nil
	}
	return nil, &NotLoadedError{edge: "content_node_languages"}
}

// ContentNodeSkillsOrErr returns the ContentNodeSkills value or an error if the edge
// was not loaded in eager-loading.
func (e ContentNodeEdges) ContentNodeSkillsOrErr() ([]*ContentNodeSkill, error) {
	if e.loadedTypes[7] {
		return e.ContentNodeSkills, nil
	}
	return nil, &NotLoadedError{edge: "content_node_skills"}
}

// ContentNodeConceptsOrErr returns the ContentNodeConcepts value or an error if the edge
// was not loaded in eager-loading.
func (e ContentNodeEdges) ContentNodeConceptsOrErr() ([]*ContentNodeConcept, error) {
	if e.loadedTypes[8] {
		return e.ContentNodeConcepts, nil
	}
	return nil, &NotLoadedError{edge: "content_node_concepts"}
}

// ContentNodeInstrumentsOrErr returns the ContentNodeInstruments value or an error if the edge
// was not loaded in eager-loading.
func (e ContentNodeEdges) ContentNodeInstrumentsOrErr() ([]*ContentNodeInstrument, error) {
	if e.loadedTypes[9] {
		return e.ContentNodeInstruments, nil
	}
	return nil, &NotLoadedError{edge: "content_node_instruments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContentNode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contentnode.FieldTitle, contentnode.FieldContentType, contentnode.FieldMediaURL, contentnode.FieldRichContent, contentnode.FieldDifficultyLevel, contentnode.FieldReviewState, contentnode.FieldThumbnailURL:
			values[i] = new(sql.NullString)
		case contentnode.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case contentnode.FieldID, contentnode.FieldTeacherID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContentNode fields.
func (_m *ContentNode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contentnode.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case contentnode.FieldTeacherID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field teacher_id", values[i])
			} else if value != nil {
				_m.TeacherID = *value
			}
		case contentnode.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case contentnode.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = contentnode.ContentType(value.String)
			}
		case contentnode.FieldMediaURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_url", values[i])
			} else if value.Valid {
				_m.MediaURL = new(string)
				*_m.MediaURL = value.String
			}
		case contentnode.FieldRichContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rich_content", values[i])
			} else if value.Valid {
				_m.RichContent = new(string)
				*_m.RichContent = value.String
			}
		case contentnode.FieldDifficultyLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field difficulty_level", values[i])
			} else if value.Valid {
				_m.DifficultyLevel = contentnode.DifficultyLevel(value.String)
			}
		case contentnode.FieldReviewState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_state", values[i])
			} else if value.Valid {
				_m.ReviewState = contentnode.ReviewState(value.String)
			}
		case contentnode.FieldThumbnailURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail_url", values[i])
			} else if value.Valid {
				_m.ThumbnailURL = new(string)
				*_m.ThumbnailURL = value.String
			}
		case contentnode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContentNode.
// This includes values selected through modifiers, order, etc.
func (_m *ContentNode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPathExercises queries the "path_exercises" edge of the ContentNode entity.
func (_m *ContentNode) QueryPathExercises() *ExerciseQuery {
	return NewContentNodeClient(_m.config).QueryPathExercises(_m)
}

// QueryLanguages queries the "languages" edge of the ContentNode entity.
func (_m *ContentNode) QueryLanguages() *LanguageQuery {
	return NewContentNodeClient(_m.config).QueryLanguages(_m)
}

// QuerySkills queries the "skills" edge of the ContentNode entity.
func (_m *ContentNode) QuerySkills() *SkillQuery {
	return NewContentNodeClient(_m.config).QuerySkills(_m)
}

// QueryConcepts queries the "concepts" edge of the ContentNode entity.
func (_m *ContentNode) QueryConcepts() *ConceptQuery {
	return NewContentNodeClient(_m.config).QueryConcepts(_m)
}

// QueryInstruments queries the "instruments" edge of the ContentNode entity.
func (_m *ContentNode) QueryInstruments() *InstrumentQuery {
	return NewContentNodeClient(_m.config).QueryInstruments(_m)
}

// QueryContentNodeExercises queries the "content_node_exercises" edge of the ContentNode entity.
func (_m *ContentNode) QueryContentNodeExercises() *ContentNodeExerciseQuery {
	return NewContentNodeClient(_m.config).QueryContentNodeExercises(_m)
}

// QueryContentNodeLanguages queries the "content_node_languages" edge of the ContentNode entity.
func (_m *ContentNode) QueryContentNodeLanguages() *ContentNodeLanguageQuery {
	return NewContentNodeClient(_m.config).QueryContentNodeLanguages(_m)
}

// QueryContentNodeSkills queries the "content_node_skills" edge of the ContentNode entity.
func (_m *ContentNode) QueryContentNodeSkills() *ContentNodeSkillQuery {
	return NewContentNodeClient(_m.config).QueryContentNodeSkills(_m)
}

// QueryContentNodeConcepts queries the "content_node_concepts" edge of the ContentNode entity.
func (_m *ContentNode) QueryContentNodeConcepts() *ContentNodeConceptQuery {
	return NewContentNodeClient(_m.config).QueryContentNodeConcepts(_m)
}

// QueryContentNodeInstruments queries the "content_node_instruments" edge of the ContentNode entity.
func (_m *ContentNode) QueryContentNodeInstruments() *ContentNodeInstrumentQuery {
	return NewContentNodeClient(_m.config).QueryContentNodeInstruments(_m)
}

// Update returns a builder for updating this ContentNode.
// Note that you need to call ContentNode.Unwrap() before calling this method if this ContentNode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContentNode) Update() *ContentNodeUpdateOne {
	return NewContentNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContentNode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContentNode) Unwrap() *ContentNode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContentNode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContentNode) String() string {
	var builder strings.Builder
	builder.WriteString("ContentNode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("teacher_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeacherID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContentType))
	builder.WriteString(", ")
	if v := _m.MediaURL; v != nil {
		builder.WriteString("media_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RichContent; v != nil {
		builder.WriteString("rich_content=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("difficulty_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.DifficultyLevel))
	builder.WriteString(", ")
	builder.WriteString("review_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewState))
	builder.WriteString(", ")
	if v := _m.ThumbnailURL; v != nil {
		builder.WriteString("thumbnail_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ContentNodes is a parsable slice of ContentNode.
type ContentNodes []*ContentNode
