// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/coursecheckpoint"
)

// CourseCheckpointCreate is the builder for creating a CourseCheckpoint entity.
type CourseCheckpointCreate struct {
	config
	mutation *CourseCheckpointMutation
	hooks    []Hook
}

// SetCourseID sets the "course_id" field.
func (_c *CourseCheckpointCreate) SetCourseID(v uuid.UUID) *CourseCheckpointCreate {
	_c.mutation.SetCourseID(v)
	return _c
}

// SetLearningPathID sets the "learning_path_id" field.
func (_c *CourseCheckpointCreate) SetLearningPathID(v uuid.UUID) *CourseCheckpointCreate {
	_c.mutation.SetLearningPathID(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *CourseCheckpointCreate) SetPosition(v int) *CourseCheckpointCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *CourseCheckpointCreate) SetTitle(v string) *CourseCheckpointCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *CourseCheckpointCreate) SetNillableTitle(v *string) *CourseCheckpointCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CourseCheckpointCreate) SetID(v uuid.UUID) *CourseCheckpointCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CourseCheckpointCreate) SetNillableID(v *uuid.UUID) *CourseCheckpointCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CourseCheckpointMutation object of the builder.
func (_c *CourseCheckpointCreate) Mutation() *CourseCheckpointMutation {
	return _c.mutation
}

// Save creates the CourseCheckpoint in the database.
func (_c *CourseCheckpointCreate) Save(ctx context.Context) (*CourseCheckpoint, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CourseCheckpointCreate) SaveX(ctx context.Context) *CourseCheckpoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseCheckpointCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseCheckpointCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CourseCheckpointCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := coursecheckpoint.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CourseCheckpointCreate) check() error {
	if _, ok := _c.mutation.CourseID(); !ok {
		return &ValidationError{Name: "course_id", err: errors.New(`ent: missing required field "CourseCheckpoint.course_id"`)}
	}
	if _, ok := _c.mutation.LearningPathID(); !ok {
		return &ValidationError{Name: "learning_path_id", err: errors.New(`ent: missing required field "CourseCheckpoint.learning_path_id"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "CourseCheckpoint.position"`)}
	}
	return nil
}

func (_c *CourseCheckpointCreate) sqlSave(ctx context.Context) (*CourseCheckpoint, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CourseCheckpointCreate) createSpec() (*CourseCheckpoint, *sqlgraph.CreateSpec) {
	var (
		_node = &CourseCheckpoint{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(coursecheckpoint.Table, sqlgraph.NewFieldSpec(coursecheckpoint.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CourseID(); ok {
		_spec.SetField(coursecheckpoint.FieldCourseID, field.TypeUUID, value)
		_node.CourseID = value
	}
	if value, ok := _c.mutation.LearningPathID(); ok {
		_spec.SetField(coursecheckpoint.FieldLearningPathID, field.TypeUUID, value)
		_node.LearningPathID = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(coursecheckpoint.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(coursecheckpoint.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	return _node, _spec
}

// CourseCheckpointCreateBulk is the builder for creating many CourseCheckpoint entities in bulk.
type CourseCheckpointCreateBulk struct {
	config
	err      error
	builders []*CourseCheckpointCreate
}

// Save creates the CourseCheckpoint entities in the database.
func (_c *CourseCheckpointCreateBulk) Save(ctx context.Context) ([]*CourseCheckpoint, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CourseCheckpoint, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseCheckpointMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CourseCheckpointCreateBulk) SaveX(ctx context.Context) []*CourseCheckpoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseCheckpointCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseCheckpointCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
