// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/courseversion"
)

// CourseVersion is the model entity for the CourseVersion schema.
type CourseVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CourseID holds the value of the "course_id" field.
	CourseID uuid.UUID `json:"course_id,omitempty"`
	// VersionNumber holds the value of the "version_number" field.
	VersionNumber int `json:"version_number,omitempty"`
	// TitleSnapshot holds the value of the "title_snapshot" field.
	TitleSnapshot string `json:"title_snapshot,omitempty"`
	// SummarySnapshot holds the value of the "summary_snapshot" field.
	SummarySnapshot string `json:"summary_snapshot,omitempty"`
	// LevelSnapshot holds the value of the "level_snapshot" field.
	LevelSnapshot courseversion.LevelSnapshot `json:"level_snapshot,omitempty"`
	// LanguageSnapshot holds the value of the "language_snapshot" field.
	LanguageSnapshot string `json:"language_snapshot,omitempty"`
	// InstrumentIdsSnapshot holds the value of the "instrument_ids_snapshot" field.
	InstrumentIdsSnapshot []string `json:"instrument_ids_snapshot,omitempty"`
	// AvailableForNewEnrollments holds the value of the "available_for_new_enrollments" field.
	AvailableForNewEnrollments bool `json:"available_for_new_enrollments,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt  time.Time `json:"published_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CourseVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case courseversion.FieldInstrumentIdsSnapshot:
			values[i] = new([]byte)
		case courseversion.FieldAvailableForNewEnrollments:
			values[i] = new(sql.NullBool)
		case courseversion.FieldVersionNumber:
			values[i] = new(sql.NullInt64)
		case courseversion.FieldTitleSnapshot, courseversion.FieldSummarySnapshot, courseversion.FieldLevelSnapshot, courseversion.FieldLanguageSnapshot:
			values[i] = new(sql.NullString)
		case courseversion.FieldPublishedAt:
			values[i] = new(sql.NullTime)
		case courseversion.FieldID, courseversion.FieldCourseID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CourseVersion fields.
func (_m *CourseVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case courseversion.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case courseversion.FieldCourseID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field course_id", values[i])
			} else if value != nil {
				_m.CourseID = *value
			}
		case courseversion.FieldVersionNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version_number", values[i])
			} else if value.Valid {
				_m.VersionNumber = int(value.Int64)
			}
		case courseversion.FieldTitleSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_snapshot", values[i])
			} else if value.Valid {
				_m.TitleSnapshot = value.String
			}
		case courseversion.FieldSummarySnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary_snapshot", values[i])
			} else if value.Valid {
				_m.SummarySnapshot = value.String
			}
		case courseversion.FieldLevelSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level_snapshot", values[i])
			} else if value.Valid {
				_m.LevelSnapshot = courseversion.LevelSnapshot(value.String)
			}
		case courseversion.FieldLanguageSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language_snapshot", values[i])
			} else if value.Valid {
				_m.LanguageSnapshot = value.String
			}
		case courseversion.FieldInstrumentIdsSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field instrument_ids_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.InstrumentIdsSnapshot); err != nil {
					return fmt.Errorf("unmarshal field instrument_ids_snapshot: %w", err)
				}
			}
		case courseversion.FieldAvailableForNewEnrollments:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field available_for_new_enrollments", values[i])
			} else if value.Valid {
				_m.AvailableForNewEnrollments = value.Bool
			}
		case courseversion.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CourseVersion.
// This includes values selected through modifiers, order, etc.
func (_m *CourseVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CourseVersion.
// Note that you need to call CourseVersion.Unwrap() before calling this method if this CourseVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CourseVersion) Update() *CourseVersionUpdateOne {
	return NewCourseVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CourseVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CourseVersion) Unwrap() *CourseVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CourseVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CourseVersion) String() string {
	var builder strings.Builder
	builder.WriteString("CourseVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("course_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CourseID))
	builder.WriteString(", ")
	builder.WriteString("version_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.VersionNumber))
	builder.WriteString(", ")
	builder.WriteString("title_snapshot=")
	builder.WriteString(_m.TitleSnapshot)
	builder.WriteString(", ")
	builder.WriteString("summary_snapshot=")
	builder.WriteString(_m.SummarySnapshot)
	builder.WriteString(", ")
	builder.WriteString("level_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.LevelSnapshot))
	builder.WriteString(", ")
	builder.WriteString("language_snapshot=")
	builder.WriteString(_m.LanguageSnapshot)
	builder.WriteString(", ")
	builder.WriteString("instrument_ids_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstrumentIdsSnapshot))
	builder.WriteString(", ")
	builder.WriteString("available_for_new_enrollments=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvailableForNewEnrollments))
	builder.WriteString(", ")
	builder.WriteString("published_at=")
	builder.WriteString(_m.PublishedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CourseVersions is a parsable slice of CourseVersion.
type CourseVersions []*CourseVersion
