// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/concept"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/diagram"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/diagramconcept"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/diagramskill"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/position"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/predicate"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/skill"
)

// DiagramUpdate is the builder for updating Diagram entities.
type DiagramUpdate struct {
	config
	hooks    []Hook
	mutation *DiagramMutation
}

// Where appends a list predicates to the DiagramUpdate builder.
func (_u *DiagramUpdate) Where(ps ...predicate.Diagram) *DiagramUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DiagramUpdate) SetName(v string) *DiagramUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DiagramUpdate) SetNillableName(v *string) *DiagramUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRootNote sets the "root_note" field.
func (_u *DiagramUpdate) SetRootNote(v string) *DiagramUpdate {
	_u.mutation.SetRootNote(v)
	return _u
}

// SetNillableRootNote sets the "root_note" field if the given value is not nil.
func (_u *DiagramUpdate) SetNillableRootNote(v *string) *DiagramUpdate {
	if v != nil {
		_u.SetRootNote(*v)
	}
	return _u
}

// ClearRootNote clears the value of the "root_note" field.
func (_u *DiagramUpdate) ClearRootNote() *DiagramUpdate {
	_u.mutation.ClearRootNote()
	return _u
}

// SetLabelDisplay sets the "label_display" field.
func (_u *DiagramUpdate) SetLabelDisplay(v diagram.LabelDisplay) *DiagramUpdate {
	_u.mutation.SetLabelDisplay(v)
	return _u
}

// SetNillableLabelDisplay sets the "label_display" field if the given value is not nil.
func (_u *DiagramUpdate) SetNillableLabelDisplay(v *diagram.LabelDisplay) *DiagramUpdate {
	if v != nil {
		_u.SetLabelDisplay(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *DiagramUpdate) SetColor(v string) *DiagramUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *DiagramUpdate) SetNillableColor(v *string) *DiagramUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *DiagramUpdate) ClearColor() *DiagramUpdate {
	_u.mutation.ClearColor()
	return _u
}

// AddPositionIDs adds the "positions" edge to the Position entity by IDs.
func (_u *DiagramUpdate) AddPositionIDs(ids ...uuid.UUID) *DiagramUpdate {
	_u.mutation.AddPositionIDs(ids...)
	return _u
}

// AddPositions adds the "positions" edges to the Position entity.
func (_u *DiagramUpdate) AddPositions(v ...*Position) *DiagramUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPositionIDs(ids...)
}

// AddSkillIDs adds the "skills" edge to the Skill entity by IDs.
func (_u *DiagramUpdate) AddSkillIDs(ids ...uuid.UUID) *DiagramUpdate {
	_u.mutation.AddSkillIDs(ids...)
	return _u
}

// AddSkills adds the "skills" edges to the Skill entity.
func (_u *DiagramUpdate) AddSkills(v ...*Skill) *DiagramUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSkillIDs(ids...)
}

// AddConceptIDs adds the "concepts" edge to the Concept entity by IDs.
func (_u *DiagramUpdate) AddConceptIDs(ids ...uuid.UUID) *DiagramUpdate {
	_u.mutation.AddConceptIDs(ids...)
	return _u
}

// AddConcepts adds the "concepts" edges to the Concept entity.
func (_u *DiagramUpdate) AddConcepts(v ...*Concept) *DiagramUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConceptIDs(ids...)
}

// AddDiagramSkillIDs adds the "diagram_skills" edge to the DiagramSkill entity by IDs.
func (_u *DiagramUpdate) AddDiagramSkillIDs(ids ...int) *DiagramUpdate {
	_u.mutation.AddDiagramSkillIDs(ids...)
	return _u
}

// AddDiagramSkills adds the "diagram_skills" edges to the DiagramSkill entity.
func (_u *DiagramUpdate) AddDiagramSkills(v ...*DiagramSkill) *DiagramUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDiagramSkillIDs(ids...)
}

// AddDiagramConceptIDs adds the "diagram_concepts" edge to the DiagramConcept entity by IDs.
func (_u *DiagramUpdate) AddDiagramConceptIDs(ids ...int) *DiagramUpdate {
	_u.mutation.AddDiagramConceptIDs(ids...)
	return _u
}

// AddDiagramConcepts adds the "diagram_concepts" edges to the DiagramConcept entity.
func (_u *DiagramUpdate) AddDiagramConcepts(v ...*DiagramConcept) *DiagramUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDiagramConceptIDs(ids...)
}

// Mutation returns the DiagramMutation object of the builder.
func (_u *DiagramUpdate) Mutation() *DiagramMutation {
	return _u.mutation
}

// ClearPositions clears all "positions" edges to the Position entity.
func (_u *DiagramUpdate) ClearPositions() *DiagramUpdate {
	_u.mutation.ClearPositions()
	return _u
}

// RemovePositionIDs removes the "positions" edge to Position entities by IDs.
func (_u *DiagramUpdate) RemovePositionIDs(ids ...uuid.UUID) *DiagramUpdate {
	_u.mutation.RemovePositionIDs(ids...)
	return _u
}

// RemovePositions removes "positions" edges to Position entities.
func (_u *DiagramUpdate) RemovePositions(v ...*Position) *DiagramUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePositionIDs(ids...)
}

// ClearSkills clears all "skills" edges to the Skill entity.
func (_u *DiagramUpdate) ClearSkills() *DiagramUpdate {
	_u.mutation.ClearSkills()
	return _u
}

// RemoveSkillIDs removes the "skills" edge to Skill entities by IDs.
func (_u *DiagramUpdate) RemoveSkillIDs(ids ...uuid.UUID) *DiagramUpdate {
	_u.mutation.RemoveSkillIDs(ids...)
	return _u
}

// RemoveSkills removes "skills" edges to Skill entities.
func (_u *DiagramUpdate) RemoveSkills(v ...*Skill) *DiagramUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSkillIDs(ids...)
}

// ClearConcepts clears all "concepts" edges to the Concept entity.
func (_u *DiagramUpdate) ClearConcepts() *DiagramUpdate {
	_u.mutation.ClearConcepts()
	return _u
}

// RemoveConceptIDs removes the "concepts" edge to Concept entities by IDs.
func (_u *DiagramUpdate) RemoveConceptIDs(ids ...uuid.UUID) *DiagramUpdate {
	_u.mutation.RemoveConceptIDs(ids...)
	return _u
}

// RemoveConcepts removes "concepts" edges to Concept entities.
func (_u *DiagramUpdate) RemoveConcepts(v ...*Concept) *DiagramUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConceptIDs(ids...)
}

// ClearDiagramSkills clears all "diagram_skills" edges to the DiagramSkill entity.
func (_u *DiagramUpdate) ClearDiagramSkills() *DiagramUpdate {
	_u.mutation.ClearDiagramSkills()
	return _u
}

// RemoveDiagramSkillIDs removes the "diagram_skills" edge to DiagramSkill entities by IDs.
func (_u *DiagramUpdate) RemoveDiagramSkillIDs(ids ...int) *DiagramUpdate {
	_u.mutation.RemoveDiagramSkillIDs(ids...)
	return _u
}

// RemoveDiagramSkills removes "diagram_skills" edges to DiagramSkill entities.
func (_u *DiagramUpdate) RemoveDiagramSkills(v ...*DiagramSkill) *DiagramUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDiagramSkillIDs(ids...)
}

// ClearDiagramConcepts clears all "diagram_concepts" edges to the DiagramConcept entity.
func (_u *DiagramUpdate) ClearDiagramConcepts() *DiagramUpdate {
	_u.mutation.ClearDiagramConcepts()
	return _u
}

// RemoveDiagramConceptIDs removes the "diagram_concepts" edge to DiagramConcept entities by IDs.
func (_u *DiagramUpdate) RemoveDiagramConceptIDs(ids ...int) *DiagramUpdate {
	_u.mutation.RemoveDiagramConceptIDs(ids...)
	return _u
}

// RemoveDiagramConcepts removes "diagram_concepts" edges to DiagramConcept entities.
func (_u *DiagramUpdate) RemoveDiagramConcepts(v ...*DiagramConcept) *DiagramUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDiagramConceptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiagramUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiagramUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiagramUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiagramUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiagramUpdate) check() error {
	if v, ok := _u.mutation.LabelDisplay(); ok {
		if err := diagram.LabelDisplayValidator(v); err != nil {
			return &ValidationError{Name: "label_display", err: fmt.Errorf(`ent: validator failed for field "Diagram.label_display": %w`, err)}
		}
	}
	if _u.mutation.InstrumentCleared() && len(_u.mutation.InstrumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Diagram.instrument"`)
	}
	return nil
}

func (_u *DiagramUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(diagram.Table, diagram.Columns, sqlgraph.NewFieldSpec(diagram.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(diagram.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootNote(); ok {
		_spec.SetField(diagram.FieldRootNote, field.TypeString, value)
	}
	if _u.mutation.RootNoteCleared() {
		_spec.ClearField(diagram.FieldRootNote, field.TypeString)
	}
	if value, ok := _u.mutation.LabelDisplay(); ok {
		_spec.SetField(diagram.FieldLabelDisplay, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(diagram.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(diagram.FieldColor, field.TypeString)
	}
	if _u.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagram.PositionsTable,
			Columns: []string{diagram.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPositionsIDs(); len(nodes) > 0 && !_u.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagram.PositionsTable,
			Columns: []string{diagram.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PositionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagram.PositionsTable,
			Columns: []string{diagram.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.SkillsTable,
			Columns: diagram.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		createE := &DiagramSkillCreate{config: _u.config, mutation: newDiagramSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !_u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.SkillsTable,
			Columns: diagram.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &DiagramSkillCreate{config: _u.config, mutation: newDiagramSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.SkillsTable,
			Columns: diagram.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &DiagramSkillCreate{config: _u.config, mutation: newDiagramSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.ConceptsTable,
			Columns: diagram.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		createE := &DiagramConceptCreate{config: _u.config, mutation: newDiagramConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConceptsIDs(); len(nodes) > 0 && !_u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.ConceptsTable,
			Columns: diagram.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &DiagramConceptCreate{config: _u.config, mutation: newDiagramConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.ConceptsTable,
			Columns: diagram.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &DiagramConceptCreate{config: _u.config, mutation: newDiagramConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DiagramSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramSkillsTable,
			Columns: []string{diagram.DiagramSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramskill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDiagramSkillsIDs(); len(nodes) > 0 && !_u.mutation.DiagramSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramSkillsTable,
			Columns: []string{diagram.DiagramSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramskill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiagramSkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramSkillsTable,
			Columns: []string{diagram.DiagramSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramskill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DiagramConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramConceptsTable,
			Columns: []string{diagram.DiagramConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramconcept.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDiagramConceptsIDs(); len(nodes) > 0 && !_u.mutation.DiagramConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramConceptsTable,
			Columns: []string{diagram.DiagramConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiagramConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramConceptsTable,
			Columns: []string{diagram.DiagramConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diagram.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiagramUpdateOne is the builder for updating a single Diagram entity.
type DiagramUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiagramMutation
}

// SetName sets the "name" field.
func (_u *DiagramUpdateOne) SetName(v string) *DiagramUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DiagramUpdateOne) SetNillableName(v *string) *DiagramUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRootNote sets the "root_note" field.
func (_u *DiagramUpdateOne) SetRootNote(v string) *DiagramUpdateOne {
	_u.mutation.SetRootNote(v)
	return _u
}

// SetNillableRootNote sets the "root_note" field if the given value is not nil.
func (_u *DiagramUpdateOne) SetNillableRootNote(v *string) *DiagramUpdateOne {
	if v != nil {
		_u.SetRootNote(*v)
	}
	return _u
}

// ClearRootNote clears the value of the "root_note" field.
func (_u *DiagramUpdateOne) ClearRootNote() *DiagramUpdateOne {
	_u.mutation.ClearRootNote()
	return _u
}

// SetLabelDisplay sets the "label_display" field.
func (_u *DiagramUpdateOne) SetLabelDisplay(v diagram.LabelDisplay) *DiagramUpdateOne {
	_u.mutation.SetLabelDisplay(v)
	return _u
}

// SetNillableLabelDisplay sets the "label_display" field if the given value is not nil.
func (_u *DiagramUpdateOne) SetNillableLabelDisplay(v *diagram.LabelDisplay) *DiagramUpdateOne {
	if v != nil {
		_u.SetLabelDisplay(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *DiagramUpdateOne) SetColor(v string) *DiagramUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *DiagramUpdateOne) SetNillableColor(v *string) *DiagramUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *DiagramUpdateOne) ClearColor() *DiagramUpdateOne {
	_u.mutation.ClearColor()
	return _u
}

// AddPositionIDs adds the "positions" edge to the Position entity by IDs.
func (_u *DiagramUpdateOne) AddPositionIDs(ids ...uuid.UUID) *DiagramUpdateOne {
	_u.mutation.AddPositionIDs(ids...)
	return _u
}

// AddPositions adds the "positions" edges to the Position entity.
func (_u *DiagramUpdateOne) AddPositions(v ...*Position) *DiagramUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPositionIDs(ids...)
}

// AddSkillIDs adds the "skills" edge to the Skill entity by IDs.
func (_u *DiagramUpdateOne) AddSkillIDs(ids ...uuid.UUID) *DiagramUpdateOne {
	_u.mutation.AddSkillIDs(ids...)
	return _u
}

// AddSkills adds the "skills" edges to the Skill entity.
func (_u *DiagramUpdateOne) AddSkills(v ...*Skill) *DiagramUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSkillIDs(ids...)
}

// AddConceptIDs adds the "concepts" edge to the Concept entity by IDs.
func (_u *DiagramUpdateOne) AddConceptIDs(ids ...uuid.UUID) *DiagramUpdateOne {
	_u.mutation.AddConceptIDs(ids...)
	return _u
}

// AddConcepts adds the "concepts" edges to the Concept entity.
func (_u *DiagramUpdateOne) AddConcepts(v ...*Concept) *DiagramUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConceptIDs(ids...)
}

// AddDiagramSkillIDs adds the "diagram_skills" edge to the DiagramSkill entity by IDs.
func (_u *DiagramUpdateOne) AddDiagramSkillIDs(ids ...int) *DiagramUpdateOne {
	_u.mutation.AddDiagramSkillIDs(ids...)
	return _u
}

// AddDiagramSkills adds the "diagram_skills" edges to the DiagramSkill entity.
func (_u *DiagramUpdateOne) AddDiagramSkills(v ...*DiagramSkill) *DiagramUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDiagramSkillIDs(ids...)
}

// AddDiagramConceptIDs adds the "diagram_concepts" edge to the DiagramConcept entity by IDs.
func (_u *DiagramUpdateOne) AddDiagramConceptIDs(ids ...int) *DiagramUpdateOne {
	_u.mutation.AddDiagramConceptIDs(ids...)
	return _u
}

// AddDiagramConcepts adds the "diagram_concepts" edges to the DiagramConcept entity.
func (_u *DiagramUpdateOne) AddDiagramConcepts(v ...*DiagramConcept) *DiagramUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDiagramConceptIDs(ids...)
}

// Mutation returns the DiagramMutation object of the builder.
func (_u *DiagramUpdateOne) Mutation() *DiagramMutation {
	return _u.mutation
}

// ClearPositions clears all "positions" edges to the Position entity.
func (_u *DiagramUpdateOne) ClearPositions() *DiagramUpdateOne {
	_u.mutation.ClearPositions()
	return _u
}

// RemovePositionIDs removes the "positions" edge to Position entities by IDs.
func (_u *DiagramUpdateOne) RemovePositionIDs(ids ...uuid.UUID) *DiagramUpdateOne {
	_u.mutation.RemovePositionIDs(ids...)
	return _u
}

// RemovePositions removes "positions" edges to Position entities.
func (_u *DiagramUpdateOne) RemovePositions(v ...*Position) *DiagramUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePositionIDs(ids...)
}

// ClearSkills clears all "skills" edges to the Skill entity.
func (_u *DiagramUpdateOne) ClearSkills() *DiagramUpdateOne {
	_u.mutation.ClearSkills()
	return _u
}

// RemoveSkillIDs removes the "skills" edge to Skill entities by IDs.
func (_u *DiagramUpdateOne) RemoveSkillIDs(ids ...uuid.UUID) *DiagramUpdateOne {
	_u.mutation.RemoveSkillIDs(ids...)
	return _u
}

// RemoveSkills removes "skills" edges to Skill entities.
func (_u *DiagramUpdateOne) RemoveSkills(v ...*Skill) *DiagramUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSkillIDs(ids...)
}

// ClearConcepts clears all "concepts" edges to the Concept entity.
func (_u *DiagramUpdateOne) ClearConcepts() *DiagramUpdateOne {
	_u.mutation.ClearConcepts()
	return _u
}

// RemoveConceptIDs removes the "concepts" edge to Concept entities by IDs.
func (_u *DiagramUpdateOne) RemoveConceptIDs(ids ...uuid.UUID) *DiagramUpdateOne {
	_u.mutation.RemoveConceptIDs(ids...)
	return _u
}

// RemoveConcepts removes "concepts" edges to Concept entities.
func (_u *DiagramUpdateOne) RemoveConcepts(v ...*Concept) *DiagramUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConceptIDs(ids...)
}

// ClearDiagramSkills clears all "diagram_skills" edges to the DiagramSkill entity.
func (_u *DiagramUpdateOne) ClearDiagramSkills() *DiagramUpdateOne {
	_u.mutation.ClearDiagramSkills()
	return _u
}

// RemoveDiagramSkillIDs removes the "diagram_skills" edge to DiagramSkill entities by IDs.
func (_u *DiagramUpdateOne) RemoveDiagramSkillIDs(ids ...int) *DiagramUpdateOne {
	_u.mutation.RemoveDiagramSkillIDs(ids...)
	return _u
}

// RemoveDiagramSkills removes "diagram_skills" edges to DiagramSkill entities.
func (_u *DiagramUpdateOne) RemoveDiagramSkills(v ...*DiagramSkill) *DiagramUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDiagramSkillIDs(ids...)
}

// ClearDiagramConcepts clears all "diagram_concepts" edges to the DiagramConcept entity.
func (_u *DiagramUpdateOne) ClearDiagramConcepts() *DiagramUpdateOne {
	_u.mutation.ClearDiagramConcepts()
	return _u
}

// RemoveDiagramConceptIDs removes the "diagram_concepts" edge to DiagramConcept entities by IDs.
func (_u *DiagramUpdateOne) RemoveDiagramConceptIDs(ids ...int) *DiagramUpdateOne {
	_u.mutation.RemoveDiagramConceptIDs(ids...)
	return _u
}

// RemoveDiagramConcepts removes "diagram_concepts" edges to DiagramConcept entities.
func (_u *DiagramUpdateOne) RemoveDiagramConcepts(v ...*DiagramConcept) *DiagramUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDiagramConceptIDs(ids...)
}

// Where appends a list predicates to the DiagramUpdate builder.
func (_u *DiagramUpdateOne) Where(ps ...predicate.Diagram) *DiagramUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiagramUpdateOne) Select(field string, fields ...string) *DiagramUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Diagram entity.
func (_u *DiagramUpdateOne) Save(ctx context.Context) (*Diagram, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiagramUpdateOne) SaveX(ctx context.Context) *Diagram {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiagramUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiagramUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiagramUpdateOne) check() error {
	if v, ok := _u.mutation.LabelDisplay(); ok {
		if err := diagram.LabelDisplayValidator(v); err != nil {
			return &ValidationError{Name: "label_display", err: fmt.Errorf(`ent: validator failed for field "Diagram.label_display": %w`, err)}
		}
	}
	if _u.mutation.InstrumentCleared() && len(_u.mutation.InstrumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Diagram.instrument"`)
	}
	return nil
}

func (_u *DiagramUpdateOne) sqlSave(ctx context.Context) (_node *Diagram, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(diagram.Table, diagram.Columns, sqlgraph.NewFieldSpec(diagram.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Diagram.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, diagram.FieldID)
		for _, f := range fields {
			if !diagram.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != diagram.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(diagram.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootNote(); ok {
		_spec.SetField(diagram.FieldRootNote, field.TypeString, value)
	}
	if _u.mutation.RootNoteCleared() {
		_spec.ClearField(diagram.FieldRootNote, field.TypeString)
	}
	if value, ok := _u.mutation.LabelDisplay(); ok {
		_spec.SetField(diagram.FieldLabelDisplay, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(diagram.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(diagram.FieldColor, field.TypeString)
	}
	if _u.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagram.PositionsTable,
			Columns: []string{diagram.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPositionsIDs(); len(nodes) > 0 && !_u.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagram.PositionsTable,
			Columns: []string{diagram.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PositionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagram.PositionsTable,
			Columns: []string{diagram.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.SkillsTable,
			Columns: diagram.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		createE := &DiagramSkillCreate{config: _u.config, mutation: newDiagramSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !_u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.SkillsTable,
			Columns: diagram.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &DiagramSkillCreate{config: _u.config, mutation: newDiagramSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.SkillsTable,
			Columns: diagram.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &DiagramSkillCreate{config: _u.config, mutation: newDiagramSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.ConceptsTable,
			Columns: diagram.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		createE := &DiagramConceptCreate{config: _u.config, mutation: newDiagramConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConceptsIDs(); len(nodes) > 0 && !_u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.ConceptsTable,
			Columns: diagram.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &DiagramConceptCreate{config: _u.config, mutation: newDiagramConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   diagram.ConceptsTable,
			Columns: diagram.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &DiagramConceptCreate{config: _u.config, mutation: newDiagramConceptMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DiagramSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramSkillsTable,
			Columns: []string{diagram.DiagramSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramskill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDiagramSkillsIDs(); len(nodes) > 0 && !_u.mutation.DiagramSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramSkillsTable,
			Columns: []string{diagram.DiagramSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramskill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiagramSkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramSkillsTable,
			Columns: []string{diagram.DiagramSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramskill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DiagramConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramConceptsTable,
			Columns: []string{diagram.DiagramConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramconcept.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDiagramConceptsIDs(); len(nodes) > 0 && !_u.mutation.DiagramConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramConceptsTable,
			Columns: []string{diagram.DiagramConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiagramConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagram.DiagramConceptsTable,
			Columns: []string{diagram.DiagramConceptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramconcept.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Diagram{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diagram.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
