// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/concept"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/diagram"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/diagramconcept"
)

// DiagramConceptCreate is the builder for creating a DiagramConcept entity.
type DiagramConceptCreate struct {
	config
	mutation *DiagramConceptMutation
	hooks    []Hook
}

// SetDiagramID sets the "diagram_id" field.
func (_c *DiagramConceptCreate) SetDiagramID(v uuid.UUID) *DiagramConceptCreate {
	_c.mutation.SetDiagramID(v)
	return _c
}

// SetConceptID sets the "concept_id" field.
func (_c *DiagramConceptCreate) SetConceptID(v uuid.UUID) *DiagramConceptCreate {
	_c.mutation.SetConceptID(v)
	return _c
}

// SetLinkedAt sets the "linked_at" field.
func (_c *DiagramConceptCreate) SetLinkedAt(v time.Time) *DiagramConceptCreate {
	_c.mutation.SetLinkedAt(v)
	return _c
}

// SetNillableLinkedAt sets the "linked_at" field if the given value is not nil.
func (_c *DiagramConceptCreate) SetNillableLinkedAt(v *time.Time) *DiagramConceptCreate {
	if v != nil {
		_c.SetLinkedAt(*v)
	}
	return _c
}

// SetDiagram sets the "diagram" edge to the Diagram entity.
func (_c *DiagramConceptCreate) SetDiagram(v *Diagram) *DiagramConceptCreate {
	return _c.SetDiagramID(v.ID)
}

// SetConcept sets the "concept" edge to the Concept entity.
func (_c *DiagramConceptCreate) SetConcept(v *Concept) *DiagramConceptCreate {
	return _c.SetConceptID(v.ID)
}

// Mutation returns the DiagramConceptMutation object of the builder.
func (_c *DiagramConceptCreate) Mutation() *DiagramConceptMutation {
	return _c.mutation
}

// Save creates the DiagramConcept in the database.
func (_c *DiagramConceptCreate) Save(ctx context.Context) (*DiagramConcept, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiagramConceptCreate) SaveX(ctx context.Context) *DiagramConcept {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiagramConceptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiagramConceptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DiagramConceptCreate) defaults() {
	if _, ok := _c.mutation.LinkedAt(); !ok {
		v := diagramconcept.DefaultLinkedAt()
		_c.mutation.SetLinkedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiagramConceptCreate) check() error {
	if _, ok := _c.mutation.DiagramID(); !ok {
		return &ValidationError{Name: "diagram_id", err: errors.New(`ent: missing required field "DiagramConcept.diagram_id"`)}
	}
	if _, ok := _c.mutation.ConceptID(); !ok {
		return &ValidationError{Name: "concept_id", err: errors.New(`ent: missing required field "DiagramConcept.concept_id"`)}
	}
	if _, ok := _c.mutation.LinkedAt(); !ok {
		return &ValidationError{Name: "linked_at", err: errors.New(`ent: missing required field "DiagramConcept.linked_at"`)}
	}
	if len(_c.mutation.DiagramIDs()) == 0 {
		return &ValidationError{Name: "diagram", err: errors.New(`ent: missing required edge "DiagramConcept.diagram"`)}
	}
	if len(_c.mutation.ConceptIDs()) == 0 {
		return &ValidationError{Name: "concept", err: errors.New(`ent: missing required edge "DiagramConcept.concept"`)}
	}
	return nil
}

func (_c *DiagramConceptCreate) sqlSave(ctx context.Context) (*DiagramConcept, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiagramConceptCreate) createSpec() (*DiagramConcept, *sqlgraph.CreateSpec) {
	var (
		_node = &DiagramConcept{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(diagramconcept.Table, sqlgraph.NewFieldSpec(diagramconcept.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.LinkedAt(); ok {
		_spec.SetField(diagramconcept.FieldLinkedAt, field.TypeTime, value)
		_node.LinkedAt = value
	}
	if nodes := _c.mutation.DiagramIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diagramconcept.DiagramTable,
			Columns: []string{diagramconcept.DiagramColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagram.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DiagramID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConceptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diagramconcept.ConceptTable,
			Columns: []string{diagramconcept.ConceptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConceptID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DiagramConceptCreateBulk is the builder for creating many DiagramConcept entities in bulk.
type DiagramConceptCreateBulk struct {
	config
	err      error
	builders []*DiagramConceptCreate
}

// Save creates the DiagramConcept entities in the database.
func (_c *DiagramConceptCreateBulk) Save(ctx context.Context) ([]*DiagramConcept, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiagramConcept, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiagramConceptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiagramConceptCreateBulk) SaveX(ctx context.Context) []*DiagramConcept {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiagramConceptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiagramConceptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
