// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/diagramshape"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/diagramshapefamily"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/predicate"
)

// DiagramShapeFamilyUpdate is the builder for updating DiagramShapeFamily entities.
type DiagramShapeFamilyUpdate struct {
	config
	hooks    []Hook
	mutation *DiagramShapeFamilyMutation
}

// Where appends a list predicates to the DiagramShapeFamilyUpdate builder.
func (_u *DiagramShapeFamilyUpdate) Where(ps ...predicate.DiagramShapeFamily) *DiagramShapeFamilyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// AddShapeIDs adds the "shapes" edge to the DiagramShape entity by IDs.
func (_u *DiagramShapeFamilyUpdate) AddShapeIDs(ids ...uuid.UUID) *DiagramShapeFamilyUpdate {
	_u.mutation.AddShapeIDs(ids...)
	return _u
}

// AddShapes adds the "shapes" edges to the DiagramShape entity.
func (_u *DiagramShapeFamilyUpdate) AddShapes(v ...*DiagramShape) *DiagramShapeFamilyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShapeIDs(ids...)
}

// Mutation returns the DiagramShapeFamilyMutation object of the builder.
func (_u *DiagramShapeFamilyUpdate) Mutation() *DiagramShapeFamilyMutation {
	return _u.mutation
}

// ClearShapes clears all "shapes" edges to the DiagramShape entity.
func (_u *DiagramShapeFamilyUpdate) ClearShapes() *DiagramShapeFamilyUpdate {
	_u.mutation.ClearShapes()
	return _u
}

// RemoveShapeIDs removes the "shapes" edge to DiagramShape entities by IDs.
func (_u *DiagramShapeFamilyUpdate) RemoveShapeIDs(ids ...uuid.UUID) *DiagramShapeFamilyUpdate {
	_u.mutation.RemoveShapeIDs(ids...)
	return _u
}

// RemoveShapes removes "shapes" edges to DiagramShape entities.
func (_u *DiagramShapeFamilyUpdate) RemoveShapes(v ...*DiagramShape) *DiagramShapeFamilyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShapeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiagramShapeFamilyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiagramShapeFamilyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiagramShapeFamilyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiagramShapeFamilyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DiagramShapeFamilyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(diagramshapefamily.Table, diagramshapefamily.Columns, sqlgraph.NewFieldSpec(diagramshapefamily.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ShapesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagramshapefamily.ShapesTable,
			Columns: []string{diagramshapefamily.ShapesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramshape.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedShapesIDs(); len(nodes) > 0 && !_u.mutation.ShapesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagramshapefamily.ShapesTable,
			Columns: []string{diagramshapefamily.ShapesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramshape.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShapesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagramshapefamily.ShapesTable,
			Columns: []string{diagramshapefamily.ShapesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramshape.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diagramshapefamily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiagramShapeFamilyUpdateOne is the builder for updating a single DiagramShapeFamily entity.
type DiagramShapeFamilyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiagramShapeFamilyMutation
}

// AddShapeIDs adds the "shapes" edge to the DiagramShape entity by IDs.
func (_u *DiagramShapeFamilyUpdateOne) AddShapeIDs(ids ...uuid.UUID) *DiagramShapeFamilyUpdateOne {
	_u.mutation.AddShapeIDs(ids...)
	return _u
}

// AddShapes adds the "shapes" edges to the DiagramShape entity.
func (_u *DiagramShapeFamilyUpdateOne) AddShapes(v ...*DiagramShape) *DiagramShapeFamilyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShapeIDs(ids...)
}

// Mutation returns the DiagramShapeFamilyMutation object of the builder.
func (_u *DiagramShapeFamilyUpdateOne) Mutation() *DiagramShapeFamilyMutation {
	return _u.mutation
}

// ClearShapes clears all "shapes" edges to the DiagramShape entity.
func (_u *DiagramShapeFamilyUpdateOne) ClearShapes() *DiagramShapeFamilyUpdateOne {
	_u.mutation.ClearShapes()
	return _u
}

// RemoveShapeIDs removes the "shapes" edge to DiagramShape entities by IDs.
func (_u *DiagramShapeFamilyUpdateOne) RemoveShapeIDs(ids ...uuid.UUID) *DiagramShapeFamilyUpdateOne {
	_u.mutation.RemoveShapeIDs(ids...)
	return _u
}

// RemoveShapes removes "shapes" edges to DiagramShape entities.
func (_u *DiagramShapeFamilyUpdateOne) RemoveShapes(v ...*DiagramShape) *DiagramShapeFamilyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShapeIDs(ids...)
}

// Where appends a list predicates to the DiagramShapeFamilyUpdate builder.
func (_u *DiagramShapeFamilyUpdateOne) Where(ps ...predicate.DiagramShapeFamily) *DiagramShapeFamilyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiagramShapeFamilyUpdateOne) Select(field string, fields ...string) *DiagramShapeFamilyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DiagramShapeFamily entity.
func (_u *DiagramShapeFamilyUpdateOne) Save(ctx context.Context) (*DiagramShapeFamily, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiagramShapeFamilyUpdateOne) SaveX(ctx context.Context) *DiagramShapeFamily {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiagramShapeFamilyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiagramShapeFamilyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DiagramShapeFamilyUpdateOne) sqlSave(ctx context.Context) (_node *DiagramShapeFamily, err error) {
	_spec := sqlgraph.NewUpdateSpec(diagramshapefamily.Table, diagramshapefamily.Columns, sqlgraph.NewFieldSpec(diagramshapefamily.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DiagramShapeFamily.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, diagramshapefamily.FieldID)
		for _, f := range fields {
			if !diagramshapefamily.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != diagramshapefamily.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ShapesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagramshapefamily.ShapesTable,
			Columns: []string{diagramshapefamily.ShapesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramshape.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedShapesIDs(); len(nodes) > 0 && !_u.mutation.ShapesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagramshapefamily.ShapesTable,
			Columns: []string{diagramshapefamily.ShapesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramshape.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShapesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   diagramshapefamily.ShapesTable,
			Columns: []string{diagramshapefamily.ShapesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagramshape.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DiagramShapeFamily{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diagramshapefamily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
