// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/drilltemplate"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/drillthreshold"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/predicate"
)

// DrillTemplateUpdate is the builder for updating DrillTemplate entities.
type DrillTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *DrillTemplateMutation
}

// Where appends a list predicates to the DrillTemplateUpdate builder.
func (_u *DrillTemplateUpdate) Where(ps ...predicate.DrillTemplate) *DrillTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNames sets the "names" field.
func (_u *DrillTemplateUpdate) SetNames(v map[string]string) *DrillTemplateUpdate {
	_u.mutation.SetNames(v)
	return _u
}

// AddThresholdIDs adds the "thresholds" edge to the DrillThreshold entity by IDs.
func (_u *DrillTemplateUpdate) AddThresholdIDs(ids ...uuid.UUID) *DrillTemplateUpdate {
	_u.mutation.AddThresholdIDs(ids...)
	return _u
}

// AddThresholds adds the "thresholds" edges to the DrillThreshold entity.
func (_u *DrillTemplateUpdate) AddThresholds(v ...*DrillThreshold) *DrillTemplateUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddThresholdIDs(ids...)
}

// Mutation returns the DrillTemplateMutation object of the builder.
func (_u *DrillTemplateUpdate) Mutation() *DrillTemplateMutation {
	return _u.mutation
}

// ClearThresholds clears all "thresholds" edges to the DrillThreshold entity.
func (_u *DrillTemplateUpdate) ClearThresholds() *DrillTemplateUpdate {
	_u.mutation.ClearThresholds()
	return _u
}

// RemoveThresholdIDs removes the "thresholds" edge to DrillThreshold entities by IDs.
func (_u *DrillTemplateUpdate) RemoveThresholdIDs(ids ...uuid.UUID) *DrillTemplateUpdate {
	_u.mutation.RemoveThresholdIDs(ids...)
	return _u
}

// RemoveThresholds removes "thresholds" edges to DrillThreshold entities.
func (_u *DrillTemplateUpdate) RemoveThresholds(v ...*DrillThreshold) *DrillTemplateUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveThresholdIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DrillTemplateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DrillTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DrillTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DrillTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DrillTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(drilltemplate.Table, drilltemplate.Columns, sqlgraph.NewFieldSpec(drilltemplate.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Names(); ok {
		_spec.SetField(drilltemplate.FieldNames, field.TypeJSON, value)
	}
	if _u.mutation.ThresholdsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   drilltemplate.ThresholdsTable,
			Columns: []string{drilltemplate.ThresholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drillthreshold.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedThresholdsIDs(); len(nodes) > 0 && !_u.mutation.ThresholdsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   drilltemplate.ThresholdsTable,
			Columns: []string{drilltemplate.ThresholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drillthreshold.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThresholdsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   drilltemplate.ThresholdsTable,
			Columns: []string{drilltemplate.ThresholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drillthreshold.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drilltemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DrillTemplateUpdateOne is the builder for updating a single DrillTemplate entity.
type DrillTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DrillTemplateMutation
}

// SetNames sets the "names" field.
func (_u *DrillTemplateUpdateOne) SetNames(v map[string]string) *DrillTemplateUpdateOne {
	_u.mutation.SetNames(v)
	return _u
}

// AddThresholdIDs adds the "thresholds" edge to the DrillThreshold entity by IDs.
func (_u *DrillTemplateUpdateOne) AddThresholdIDs(ids ...uuid.UUID) *DrillTemplateUpdateOne {
	_u.mutation.AddThresholdIDs(ids...)
	return _u
}

// AddThresholds adds the "thresholds" edges to the DrillThreshold entity.
func (_u *DrillTemplateUpdateOne) AddThresholds(v ...*DrillThreshold) *DrillTemplateUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddThresholdIDs(ids...)
}

// Mutation returns the DrillTemplateMutation object of the builder.
func (_u *DrillTemplateUpdateOne) Mutation() *DrillTemplateMutation {
	return _u.mutation
}

// ClearThresholds clears all "thresholds" edges to the DrillThreshold entity.
func (_u *DrillTemplateUpdateOne) ClearThresholds() *DrillTemplateUpdateOne {
	_u.mutation.ClearThresholds()
	return _u
}

// RemoveThresholdIDs removes the "thresholds" edge to DrillThreshold entities by IDs.
func (_u *DrillTemplateUpdateOne) RemoveThresholdIDs(ids ...uuid.UUID) *DrillTemplateUpdateOne {
	_u.mutation.RemoveThresholdIDs(ids...)
	return _u
}

// RemoveThresholds removes "thresholds" edges to DrillThreshold entities.
func (_u *DrillTemplateUpdateOne) RemoveThresholds(v ...*DrillThreshold) *DrillTemplateUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveThresholdIDs(ids...)
}

// Where appends a list predicates to the DrillTemplateUpdate builder.
func (_u *DrillTemplateUpdateOne) Where(ps ...predicate.DrillTemplate) *DrillTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DrillTemplateUpdateOne) Select(field string, fields ...string) *DrillTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DrillTemplate entity.
func (_u *DrillTemplateUpdateOne) Save(ctx context.Context) (*DrillTemplate, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DrillTemplateUpdateOne) SaveX(ctx context.Context) *DrillTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DrillTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DrillTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DrillTemplateUpdateOne) sqlSave(ctx context.Context) (_node *DrillTemplate, err error) {
	_spec := sqlgraph.NewUpdateSpec(drilltemplate.Table, drilltemplate.Columns, sqlgraph.NewFieldSpec(drilltemplate.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DrillTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, drilltemplate.FieldID)
		for _, f := range fields {
			if !drilltemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != drilltemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Names(); ok {
		_spec.SetField(drilltemplate.FieldNames, field.TypeJSON, value)
	}
	if _u.mutation.ThresholdsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   drilltemplate.ThresholdsTable,
			Columns: []string{drilltemplate.ThresholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drillthreshold.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedThresholdsIDs(); len(nodes) > 0 && !_u.mutation.ThresholdsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   drilltemplate.ThresholdsTable,
			Columns: []string{drilltemplate.ThresholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drillthreshold.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThresholdsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   drilltemplate.ThresholdsTable,
			Columns: []string{drilltemplate.ThresholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drillthreshold.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DrillTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drilltemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
