// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/exercise"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/exerciseinstrument"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/instrument"
)

// ExerciseInstrumentCreate is the builder for creating a ExerciseInstrument entity.
type ExerciseInstrumentCreate struct {
	config
	mutation *ExerciseInstrumentMutation
	hooks    []Hook
}

// SetExerciseID sets the "exercise_id" field.
func (_c *ExerciseInstrumentCreate) SetExerciseID(v uuid.UUID) *ExerciseInstrumentCreate {
	_c.mutation.SetExerciseID(v)
	return _c
}

// SetInstrumentID sets the "instrument_id" field.
func (_c *ExerciseInstrumentCreate) SetInstrumentID(v uuid.UUID) *ExerciseInstrumentCreate {
	_c.mutation.SetInstrumentID(v)
	return _c
}

// SetLinkedAt sets the "linked_at" field.
func (_c *ExerciseInstrumentCreate) SetLinkedAt(v time.Time) *ExerciseInstrumentCreate {
	_c.mutation.SetLinkedAt(v)
	return _c
}

// SetNillableLinkedAt sets the "linked_at" field if the given value is not nil.
func (_c *ExerciseInstrumentCreate) SetNillableLinkedAt(v *time.Time) *ExerciseInstrumentCreate {
	if v != nil {
		_c.SetLinkedAt(*v)
	}
	return _c
}

// SetExercise sets the "exercise" edge to the Exercise entity.
func (_c *ExerciseInstrumentCreate) SetExercise(v *Exercise) *ExerciseInstrumentCreate {
	return _c.SetExerciseID(v.ID)
}

// SetInstrument sets the "instrument" edge to the Instrument entity.
func (_c *ExerciseInstrumentCreate) SetInstrument(v *Instrument) *ExerciseInstrumentCreate {
	return _c.SetInstrumentID(v.ID)
}

// Mutation returns the ExerciseInstrumentMutation object of the builder.
func (_c *ExerciseInstrumentCreate) Mutation() *ExerciseInstrumentMutation {
	return _c.mutation
}

// Save creates the ExerciseInstrument in the database.
func (_c *ExerciseInstrumentCreate) Save(ctx context.Context) (*ExerciseInstrument, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExerciseInstrumentCreate) SaveX(ctx context.Context) *ExerciseInstrument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExerciseInstrumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExerciseInstrumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExerciseInstrumentCreate) defaults() {
	if _, ok := _c.mutation.LinkedAt(); !ok {
		v := exerciseinstrument.DefaultLinkedAt()
		_c.mutation.SetLinkedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExerciseInstrumentCreate) check() error {
	if _, ok := _c.mutation.ExerciseID(); !ok {
		return &ValidationError{Name: "exercise_id", err: errors.New(`ent: missing required field "ExerciseInstrument.exercise_id"`)}
	}
	if _, ok := _c.mutation.InstrumentID(); !ok {
		return &ValidationError{Name: "instrument_id", err: errors.New(`ent: missing required field "ExerciseInstrument.instrument_id"`)}
	}
	if _, ok := _c.mutation.LinkedAt(); !ok {
		return &ValidationError{Name: "linked_at", err: errors.New(`ent: missing required field "ExerciseInstrument.linked_at"`)}
	}
	if len(_c.mutation.ExerciseIDs()) == 0 {
		return &ValidationError{Name: "exercise", err: errors.New(`ent: missing required edge "ExerciseInstrument.exercise"`)}
	}
	if len(_c.mutation.InstrumentIDs()) == 0 {
		return &ValidationError{Name: "instrument", err: errors.New(`ent: missing required edge "ExerciseInstrument.instrument"`)}
	}
	return nil
}

func (_c *ExerciseInstrumentCreate) sqlSave(ctx context.Context) (*ExerciseInstrument, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExerciseInstrumentCreate) createSpec() (*ExerciseInstrument, *sqlgraph.CreateSpec) {
	var (
		_node = &ExerciseInstrument{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exerciseinstrument.Table, sqlgraph.NewFieldSpec(exerciseinstrument.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.LinkedAt(); ok {
		_spec.SetField(exerciseinstrument.FieldLinkedAt, field.TypeTime, value)
		_node.LinkedAt = value
	}
	if nodes := _c.mutation.ExerciseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   exerciseinstrument.ExerciseTable,
			Columns: []string{exerciseinstrument.ExerciseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ExerciseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InstrumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   exerciseinstrument.InstrumentTable,
			Columns: []string{exerciseinstrument.InstrumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InstrumentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExerciseInstrumentCreateBulk is the builder for creating many ExerciseInstrument entities in bulk.
type ExerciseInstrumentCreateBulk struct {
	config
	err      error
	builders []*ExerciseInstrumentCreate
}

// Save creates the ExerciseInstrument entities in the database.
func (_c *ExerciseInstrumentCreateBulk) Save(ctx context.Context) ([]*ExerciseInstrument, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExerciseInstrument, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExerciseInstrumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExerciseInstrumentCreateBulk) SaveX(ctx context.Context) []*ExerciseInstrument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExerciseInstrumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExerciseInstrumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
