// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/instrument"
)

// Instrument is the model entity for the Instrument schema.
type Instrument struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Names holds the value of the "names" field.
	Names map[string]string `json:"names,omitempty"`
	// Family holds the value of the "family" field.
	Family instrument.Family `json:"family,omitempty"`
	// StringCount holds the value of the "string_count" field.
	StringCount *int `json:"string_count,omitempty"`
	// Tuning holds the value of the "tuning" field.
	Tuning []string `json:"tuning,omitempty"`
	// KeyRangeLowest holds the value of the "key_range_lowest" field.
	KeyRangeLowest *string `json:"key_range_lowest,omitempty"`
	// KeyRangeHighest holds the value of the "key_range_highest" field.
	KeyRangeHighest *string `json:"key_range_highest,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InstrumentQuery when eager-loading is set.
	Edges        InstrumentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InstrumentEdges holds the relations/edges for other nodes in the graph.
type InstrumentEdges struct {
	// Diagrams holds the value of the diagrams edge.
	Diagrams []*Diagram `json:"diagrams,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DiagramsOrErr returns the Diagrams value or an error if the edge
// was not loaded in eager-loading.
func (e InstrumentEdges) DiagramsOrErr() ([]*Diagram, error) {
	if e.loadedTypes[0] {
		return e.Diagrams, nil
	}
	return nil, &NotLoadedError{edge: "diagrams"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Instrument) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case instrument.FieldNames, instrument.FieldTuning:
			values[i] = new([]byte)
		case instrument.FieldStringCount:
			values[i] = new(sql.NullInt64)
		case instrument.FieldFamily, instrument.FieldKeyRangeLowest, instrument.FieldKeyRangeHighest:
			values[i] = new(sql.NullString)
		case instrument.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Instrument fields.
func (_m *Instrument) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case instrument.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case instrument.FieldNames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field names", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Names); err != nil {
					return fmt.Errorf("unmarshal field names: %w", err)
				}
			}
		case instrument.FieldFamily:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field family", values[i])
			} else if value.Valid {
				_m.Family = instrument.Family(value.String)
			}
		case instrument.FieldStringCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field string_count", values[i])
			} else if value.Valid {
				_m.StringCount = new(int)
				*_m.StringCount = int(value.Int64)
			}
		case instrument.FieldTuning:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tuning", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tuning); err != nil {
					return fmt.Errorf("unmarshal field tuning: %w", err)
				}
			}
		case instrument.FieldKeyRangeLowest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_range_lowest", values[i])
			} else if value.Valid {
				_m.KeyRangeLowest = new(string)
				*_m.KeyRangeLowest = value.String
			}
		case instrument.FieldKeyRangeHighest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_range_highest", values[i])
			} else if value.Valid {
				_m.KeyRangeHighest = new(string)
				*_m.KeyRangeHighest = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Instrument.
// This includes values selected through modifiers, order, etc.
func (_m *Instrument) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDiagrams queries the "diagrams" edge of the Instrument entity.
func (_m *Instrument) QueryDiagrams() *DiagramQuery {
	return NewInstrumentClient(_m.config).QueryDiagrams(_m)
}

// Update returns a builder for updating this Instrument.
// Note that you need to call Instrument.Unwrap() before calling this method if this Instrument
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Instrument) Update() *InstrumentUpdateOne {
	return NewInstrumentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Instrument entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Instrument) Unwrap() *Instrument {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Instrument is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Instrument) String() string {
	var builder strings.Builder
	builder.WriteString("Instrument(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("names=")
	builder.WriteString(fmt.Sprintf("%v", _m.Names))
	builder.WriteString(", ")
	builder.WriteString("family=")
	builder.WriteString(fmt.Sprintf("%v", _m.Family))
	builder.WriteString(", ")
	if v := _m.StringCount; v != nil {
		builder.WriteString("string_count=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("tuning=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tuning))
	builder.WriteString(", ")
	if v := _m.KeyRangeLowest; v != nil {
		builder.WriteString("key_range_lowest=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.KeyRangeHighest; v != nil {
		builder.WriteString("key_range_highest=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Instruments is a parsable slice of Instrument.
type Instruments []*Instrument
