// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/knowledgeedge"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/knowledgenode"
)

// KnowledgeEdgeCreate is the builder for creating a KnowledgeEdge entity.
type KnowledgeEdgeCreate struct {
	config
	mutation *KnowledgeEdgeMutation
	hooks    []Hook
}

// SetFromID sets the "from_id" field.
func (_c *KnowledgeEdgeCreate) SetFromID(v uuid.UUID) *KnowledgeEdgeCreate {
	_c.mutation.SetFromID(v)
	return _c
}

// SetToID sets the "to_id" field.
func (_c *KnowledgeEdgeCreate) SetToID(v uuid.UUID) *KnowledgeEdgeCreate {
	_c.mutation.SetToID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *KnowledgeEdgeCreate) SetType(v knowledgeedge.Type) *KnowledgeEdgeCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *KnowledgeEdgeCreate) SetLevel(v knowledgeedge.Level) *KnowledgeEdgeCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_c *KnowledgeEdgeCreate) SetNillableLevel(v *knowledgeedge.Level) *KnowledgeEdgeCreate {
	if v != nil {
		_c.SetLevel(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *KnowledgeEdgeCreate) SetID(v uuid.UUID) *KnowledgeEdgeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *KnowledgeEdgeCreate) SetNillableID(v *uuid.UUID) *KnowledgeEdgeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetFrom sets the "from" edge to the KnowledgeNode entity.
func (_c *KnowledgeEdgeCreate) SetFrom(v *KnowledgeNode) *KnowledgeEdgeCreate {
	return _c.SetFromID(v.ID)
}

// SetTo sets the "to" edge to the KnowledgeNode entity.
func (_c *KnowledgeEdgeCreate) SetTo(v *KnowledgeNode) *KnowledgeEdgeCreate {
	return _c.SetToID(v.ID)
}

// Mutation returns the KnowledgeEdgeMutation object of the builder.
func (_c *KnowledgeEdgeCreate) Mutation() *KnowledgeEdgeMutation {
	return _c.mutation
}

// Save creates the KnowledgeEdge in the database.
func (_c *KnowledgeEdgeCreate) Save(ctx context.Context) (*KnowledgeEdge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KnowledgeEdgeCreate) SaveX(ctx context.Context) *KnowledgeEdge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeEdgeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeEdgeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KnowledgeEdgeCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := knowledgeedge.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KnowledgeEdgeCreate) check() error {
	if _, ok := _c.mutation.FromID(); !ok {
		return &ValidationError{Name: "from_id", err: errors.New(`ent: missing required field "KnowledgeEdge.from_id"`)}
	}
	if _, ok := _c.mutation.ToID(); !ok {
		return &ValidationError{Name: "to_id", err: errors.New(`ent: missing required field "KnowledgeEdge.to_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "KnowledgeEdge.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := knowledgeedge.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "KnowledgeEdge.type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Level(); ok {
		if err := knowledgeedge.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "KnowledgeEdge.level": %w`, err)}
		}
	}
	if len(_c.mutation.FromIDs()) == 0 {
		return &ValidationError{Name: "from", err: errors.New(`ent: missing required edge "KnowledgeEdge.from"`)}
	}
	if len(_c.mutation.ToIDs()) == 0 {
		return &ValidationError{Name: "to", err: errors.New(`ent: missing required edge "KnowledgeEdge.to"`)}
	}
	return nil
}

func (_c *KnowledgeEdgeCreate) sqlSave(ctx context.Context) (*KnowledgeEdge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KnowledgeEdgeCreate) createSpec() (*KnowledgeEdge, *sqlgraph.CreateSpec) {
	var (
		_node = &KnowledgeEdge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(knowledgeedge.Table, sqlgraph.NewFieldSpec(knowledgeedge.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(knowledgeedge.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(knowledgeedge.FieldLevel, field.TypeEnum, value)
		_node.Level = &value
	}
	if nodes := _c.mutation.FromIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgeedge.FromTable,
			Columns: []string{knowledgeedge.FromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgenode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FromID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   knowledgeedge.ToTable,
			Columns: []string{knowledgeedge.ToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgenode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ToID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// KnowledgeEdgeCreateBulk is the builder for creating many KnowledgeEdge entities in bulk.
type KnowledgeEdgeCreateBulk struct {
	config
	err      error
	builders []*KnowledgeEdgeCreate
}

// Save creates the KnowledgeEdge entities in the database.
func (_c *KnowledgeEdgeCreateBulk) Save(ctx context.Context) ([]*KnowledgeEdge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*KnowledgeEdge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KnowledgeEdgeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KnowledgeEdgeCreateBulk) SaveX(ctx context.Context) []*KnowledgeEdge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeEdgeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeEdgeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
