// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/learningpathitem"
)

// LearningPathItem is the model entity for the LearningPathItem schema.
type LearningPathItem struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// LearningPathID holds the value of the "learning_path_id" field.
	LearningPathID uuid.UUID `json:"learning_path_id,omitempty"`
	// ContentNodeID holds the value of the "content_node_id" field.
	ContentNodeID uuid.UUID `json:"content_node_id,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// SectionLabel holds the value of the "section_label" field.
	SectionLabel *string `json:"section_label,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LearningPathItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case learningpathitem.FieldPosition:
			values[i] = new(sql.NullInt64)
		case learningpathitem.FieldSectionLabel:
			values[i] = new(sql.NullString)
		case learningpathitem.FieldID, learningpathitem.FieldLearningPathID, learningpathitem.FieldContentNodeID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LearningPathItem fields.
func (_m *LearningPathItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case learningpathitem.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case learningpathitem.FieldLearningPathID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field learning_path_id", values[i])
			} else if value != nil {
				_m.LearningPathID = *value
			}
		case learningpathitem.FieldContentNodeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field content_node_id", values[i])
			} else if value != nil {
				_m.ContentNodeID = *value
			}
		case learningpathitem.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case learningpathitem.FieldSectionLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field section_label", values[i])
			} else if value.Valid {
				_m.SectionLabel = new(string)
				*_m.SectionLabel = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LearningPathItem.
// This includes values selected through modifiers, order, etc.
func (_m *LearningPathItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LearningPathItem.
// Note that you need to call LearningPathItem.Unwrap() before calling this method if this LearningPathItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LearningPathItem) Update() *LearningPathItemUpdateOne {
	return NewLearningPathItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LearningPathItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LearningPathItem) Unwrap() *LearningPathItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LearningPathItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LearningPathItem) String() string {
	var builder strings.Builder
	builder.WriteString("LearningPathItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("learning_path_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LearningPathID))
	builder.WriteString(", ")
	builder.WriteString("content_node_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContentNodeID))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	if v := _m.SectionLabel; v != nil {
		builder.WriteString("section_label=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// LearningPathItems is a parsable slice of LearningPathItem.
type LearningPathItems []*LearningPathItem
