// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/learningpath"
)

// LearningPath is the model entity for the LearningPath schema.
type LearningPath struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TeacherID holds the value of the "teacher_id" field.
	TeacherID uuid.UUID `json:"teacher_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Level holds the value of the "level" field.
	Level *learningpath.Level `json:"level,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LearningPathQuery when eager-loading is set.
	Edges        LearningPathEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LearningPathEdges holds the relations/edges for other nodes in the graph.
type LearningPathEdges struct {
	// Instruments holds the value of the instruments edge.
	Instruments []*Instrument `json:"instruments,omitempty"`
	// LearningPathInstruments holds the value of the learning_path_instruments edge.
	LearningPathInstruments []*LearningPathInstrument `json:"learning_path_instruments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// InstrumentsOrErr returns the Instruments value or an error if the edge
// was not loaded in eager-loading.
func (e LearningPathEdges) InstrumentsOrErr() ([]*Instrument, error) {
	if e.loadedTypes[0] {
		return e.Instruments, nil
	}
	return nil, &NotLoadedError{edge: "instruments"}
}

// LearningPathInstrumentsOrErr returns the LearningPathInstruments value or an error if the edge
// was not loaded in eager-loading.
func (e LearningPathEdges) LearningPathInstrumentsOrErr() ([]*LearningPathInstrument, error) {
	if e.loadedTypes[1] {
		return e.LearningPathInstruments, nil
	}
	return nil, &NotLoadedError{edge: "learning_path_instruments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LearningPath) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case learningpath.FieldTitle, learningpath.FieldLevel:
			values[i] = new(sql.NullString)
		case learningpath.FieldUpdatedAt, learningpath.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case learningpath.FieldID, learningpath.FieldTeacherID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LearningPath fields.
func (_m *LearningPath) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case learningpath.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case learningpath.FieldTeacherID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field teacher_id", values[i])
			} else if value != nil {
				_m.TeacherID = *value
			}
		case learningpath.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case learningpath.FieldLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = new(learningpath.Level)
				*_m.Level = learningpath.Level(value.String)
			}
		case learningpath.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case learningpath.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LearningPath.
// This includes values selected through modifiers, order, etc.
func (_m *LearningPath) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInstruments queries the "instruments" edge of the LearningPath entity.
func (_m *LearningPath) QueryInstruments() *InstrumentQuery {
	return NewLearningPathClient(_m.config).QueryInstruments(_m)
}

// QueryLearningPathInstruments queries the "learning_path_instruments" edge of the LearningPath entity.
func (_m *LearningPath) QueryLearningPathInstruments() *LearningPathInstrumentQuery {
	return NewLearningPathClient(_m.config).QueryLearningPathInstruments(_m)
}

// Update returns a builder for updating this LearningPath.
// Note that you need to call LearningPath.Unwrap() before calling this method if this LearningPath
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LearningPath) Update() *LearningPathUpdateOne {
	return NewLearningPathClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LearningPath entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LearningPath) Unwrap() *LearningPath {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LearningPath is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LearningPath) String() string {
	var builder strings.Builder
	builder.WriteString("LearningPath(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("teacher_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeacherID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Level; v != nil {
		builder.WriteString("level=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LearningPaths is a parsable slice of LearningPath.
type LearningPaths []*LearningPath
