// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClerkUserID holds the string denoting the clerk_user_id field in the database.
	FieldClerkUserID = "clerk_user_id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldLocaleID holds the string denoting the locale_id field in the database.
	FieldLocaleID = "locale_id"
	// FieldRegisteredAt holds the string denoting the registered_at field in the database.
	FieldRegisteredAt = "registered_at"
	// EdgeLocale holds the string denoting the locale edge name in mutations.
	EdgeLocale = "locale"
	// Table holds the table name of the user in the database.
	Table = "users"
	// LocaleTable is the table that holds the locale relation/edge.
	LocaleTable = "users"
	// LocaleInverseTable is the table name for the Language entity.
	// It exists in this package in order to avoid circular dependency with the "language" package.
	LocaleInverseTable = "languages"
	// LocaleColumn is the table column denoting the locale relation/edge.
	LocaleColumn = "locale_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldClerkUserID,
	FieldRole,
	FieldDisplayName,
	FieldLocaleID,
	FieldRegisteredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultRegisteredAt holds the default value on creation for the "registered_at" field.
	DefaultRegisteredAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Role defines the type for the "role" enum field.
type Role string

// Role values.
const (
	RoleStudent Role = "student"
	RoleTeacher Role = "teacher"
	RoleAdmin   Role = "admin"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleStudent, RoleTeacher, RoleAdmin:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClerkUserID orders the results by the clerk_user_id field.
func ByClerkUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClerkUserID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByLocaleID orders the results by the locale_id field.
func ByLocaleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocaleID, opts...).ToFunc()
}

// ByRegisteredAt orders the results by the registered_at field.
func ByRegisteredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegisteredAt, opts...).ToFunc()
}

// ByLocaleField orders the results by locale field.
func ByLocaleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLocaleStep(), sql.OrderByField(field, opts...))
	}
}
func newLocaleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LocaleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, LocaleTable, LocaleColumn),
	)
}
