"""Builds core-domain's baseline_reference_data migration: every reference and
catalog row, in dependency order, right after the baseline_schema migration.

Each section comes from the generator that owns it, never from hand edits:
scripts/knowledge_map (the catalog instruments, their icons and the knowledge
map), scripts/diagram_catalog (the basic-guitar catalog) and
scripts/practice_drills (the drill catalog and the fretboard cells). The
languages and voices have no generator; they are carried over unchanged from
languages_and_voices.sql.

The chord catalog (scripts/chord_catalog) needs tables that came after the
schema baseline, so it is a second migration, chord_catalog_reference_data,
written right after the chord_catalog migration that creates them. Run
`atlas migrate hash` afterwards.

A drill threshold version may only take effect in the past if it is already
installed, so the drill thresholds the migration already installs are kept.
Building the baseline for the first time, pass --installed-from with the
migration that installed them until then.

Usage: python build.py [--specs ../../../motifpath-specs] [--installed-from <old drills migration>]
"""
import argparse
import datetime
import re
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[1]
for generator in ('knowledge_map', 'diagram_catalog', 'practice_drills', 'chord_catalog'):
    sys.path.insert(0, str(SCRIPTS / generator))

import catalog  # noqa: E402
import chord_catalog  # noqa: E402
import knowledge_map  # noqa: E402
import practice_drills  # noqa: E402

MIGRATIONS_DIR = SCRIPTS.parent / 'services/core-domain/internal/adapters/repo/ent/migrate/migrations'
CATALOG_OUTPUT = SCRIPTS.parent / 'catalog/basic-guitar-v1'
CHORD_OUTPUT = SCRIPTS.parent / 'catalog/chord-voicings-v1'
CARRIED = Path(__file__).resolve().parent / 'languages_and_voices.sql'

# The sections, in the order their rows depend on each other.
SECTIONS = [
    'languages-and-voices', 'catalog-instruments', 'instrument-icons', 'knowledge-map',
    'basic-guitar-catalog', 'practice-drills', 'fretboard-cells',
]
SCHEMA_BASELINE = re.compile(r'^(\d{14})_baseline_schema\.up\.sql$')
CHORD_TABLES = re.compile(r'^(\d{14})_chord_catalog\.up\.sql$')
HEADER = '-- Generated by scripts/reference_data/build.py. Never edit it by hand.\n'


def section_marker(name):
    return f'-- section: {name}\n'


def section(sql, name):
    """The text of the section name in a rendered migration."""
    marker = section_marker(name)
    if marker not in sql:
        raise ValueError(f'the migration has no {name} section')
    rest = sql.split(marker, 1)[1]
    return rest.split('-- section: ', 1)[0]


def render(specs, installed=frozenset(), today=None):
    """The reference data migration for the catalogs in specs. installed
    holds the ids of the drill threshold versions already installed; any
    other version must take effect today or later."""
    catalogs = Path(specs) / 'catalogs'
    graph = knowledge_map.load(catalogs / 'knowledge-map.yaml')
    drills = practice_drills.load(catalogs / 'practice-drills.yaml', installed, today)
    ranges = practice_drills.load_cells(catalogs / 'practice-drills.yaml', catalogs / 'knowledge-map.yaml')
    bodies = {
        'languages-and-voices': CARRIED.read_text(),
        'catalog-instruments': knowledge_map.render_instruments_sql(),
        'instrument-icons': knowledge_map.render_instrument_icons_sql(),
        'knowledge-map': knowledge_map.render_sql(graph),
        'basic-guitar-catalog': catalog.render_sql(catalog.generate()),
        'practice-drills': practice_drills.render_sql(drills),
        'fretboard-cells': practice_drills.render_cells_sql(ranges),
    }
    return HEADER + ''.join(section_marker(name) + bodies[name] for name in SECTIONS)


def following(migrations, pattern, name):
    """The name of the migration called name that applies one second after
    the single migration in migrations matching pattern."""
    stamps = [m.group(1) for p in Path(migrations).iterdir() if (m := pattern.match(p.name))]
    if len(stamps) != 1:
        raise ValueError(f'expected one migration matching {pattern.pattern} in {migrations}, found {len(stamps)}')
    return f'{int(stamps[0]) + 1}_{name}.up.sql'


def reference_data_file(migrations):
    """The reference data migration's name: one second after the schema
    baseline's, so it always applies right after it."""
    return following(migrations, SCHEMA_BASELINE, 'baseline_reference_data')


def write_chords(specs, migrations, chord_output):
    """Writes the chord catalog's migration right after the migration that
    creates its tables, and its reports to chord_output; returns its path."""
    path = Path(migrations) / following(migrations, CHORD_TABLES, 'chord_catalog_reference_data')
    generated = chord_catalog.generate(chord_catalog.load(Path(specs) / 'catalogs' / 'chord-voicings.yaml'))
    chord_catalog.write_outputs(generated, Path(chord_output))
    path.write_text(HEADER + chord_catalog.render_sql(generated))
    return path


def installed_thresholds(path, installed_from=None):
    """The ids of the drill threshold versions the migration at path already
    installs, plus those installed_from (an older migration) installs."""
    installed = set()
    if path.exists():
        installed |= practice_drills.installed_threshold_ids(section(path.read_text(), 'practice-drills'))
    if installed_from is not None:
        installed |= practice_drills.installed_threshold_ids(Path(installed_from).read_text())
    return installed


def write(specs, migrations, catalog_output, today=None, installed_from=None):
    """Writes the reference data migration to migrations and the basic-guitar
    catalog's reports to catalog_output, returning the migration's path."""
    path = Path(migrations) / reference_data_file(migrations)
    sql = render(specs, installed_thresholds(path, installed_from), today)
    catalog.write_outputs(catalog.generate(), Path(catalog_output))
    path.write_text(sql)
    return path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--specs', type=Path, default=SCRIPTS.parents[1] / 'motifpath-specs')
    parser.add_argument('--migrations', type=Path, default=MIGRATIONS_DIR)
    parser.add_argument('--catalog-output', type=Path, default=CATALOG_OUTPUT)
    parser.add_argument('--chord-output', type=Path, default=CHORD_OUTPUT)
    parser.add_argument('--installed-from', type=Path, help='an older migration whose drill thresholds are already installed')
    args = parser.parse_args()
    print(write(args.specs, args.migrations, args.catalog_output, datetime.date.today(), args.installed_from))
    print(write_chords(args.specs, args.migrations, args.chord_output))


if __name__ == '__main__':
    main()
