// Code generated by ent, DO NOT EDIT.

package diagramskill

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the diagramskill type in the database.
	Label = "diagram_skill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDiagramID holds the string denoting the diagram_id field in the database.
	FieldDiagramID = "diagram_id"
	// FieldSkillID holds the string denoting the skill_id field in the database.
	FieldSkillID = "skill_id"
	// FieldLinkedAt holds the string denoting the linked_at field in the database.
	FieldLinkedAt = "linked_at"
	// EdgeDiagram holds the string denoting the diagram edge name in mutations.
	EdgeDiagram = "diagram"
	// EdgeSkill holds the string denoting the skill edge name in mutations.
	EdgeSkill = "skill"
	// Table holds the table name of the diagramskill in the database.
	Table = "diagram_skills"
	// DiagramTable is the table that holds the diagram relation/edge.
	DiagramTable = "diagram_skills"
	// DiagramInverseTable is the table name for the Diagram entity.
	// It exists in this package in order to avoid circular dependency with the "diagram" package.
	DiagramInverseTable = "diagrams"
	// DiagramColumn is the table column denoting the diagram relation/edge.
	DiagramColumn = "diagram_id"
	// SkillTable is the table that holds the skill relation/edge.
	SkillTable = "diagram_skills"
	// SkillInverseTable is the table name for the Skill entity.
	// It exists in this package in order to avoid circular dependency with the "skill" package.
	SkillInverseTable = "skills"
	// SkillColumn is the table column denoting the skill relation/edge.
	SkillColumn = "skill_id"
)

// Columns holds all SQL columns for diagramskill fields.
var Columns = []string{
	FieldID,
	FieldDiagramID,
	FieldSkillID,
	FieldLinkedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLinkedAt holds the default value on creation for the "linked_at" field.
	DefaultLinkedAt func() time.Time
)

// OrderOption defines the ordering options for the DiagramSkill queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDiagramID orders the results by the diagram_id field.
func ByDiagramID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiagramID, opts...).ToFunc()
}

// BySkillID orders the results by the skill_id field.
func BySkillID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillID, opts...).ToFunc()
}

// ByLinkedAt orders the results by the linked_at field.
func ByLinkedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkedAt, opts...).ToFunc()
}

// ByDiagramField orders the results by diagram field.
func ByDiagramField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDiagramStep(), sql.OrderByField(field, opts...))
	}
}

// BySkillField orders the results by skill field.
func BySkillField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSkillStep(), sql.OrderByField(field, opts...))
	}
}
func newDiagramStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DiagramInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, DiagramTable, DiagramColumn),
	)
}
func newSkillStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SkillInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SkillTable, SkillColumn),
	)
}
