// Code generated by ent, DO NOT EDIT.

package contentnodeinstrument

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/motifpath/core-domain/internal/adapters/repo/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldLTE(FieldID, id))
}

// ContentNodeID applies equality check predicate on the "content_node_id" field. It's identical to ContentNodeIDEQ.
func ContentNodeID(v uuid.UUID) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldEQ(FieldContentNodeID, v))
}

// InstrumentID applies equality check predicate on the "instrument_id" field. It's identical to InstrumentIDEQ.
func InstrumentID(v uuid.UUID) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldEQ(FieldInstrumentID, v))
}

// LinkedAt applies equality check predicate on the "linked_at" field. It's identical to LinkedAtEQ.
func LinkedAt(v time.Time) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldEQ(FieldLinkedAt, v))
}

// ContentNodeIDEQ applies the EQ predicate on the "content_node_id" field.
func ContentNodeIDEQ(v uuid.UUID) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldEQ(FieldContentNodeID, v))
}

// ContentNodeIDNEQ applies the NEQ predicate on the "content_node_id" field.
func ContentNodeIDNEQ(v uuid.UUID) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldNEQ(FieldContentNodeID, v))
}

// ContentNodeIDIn applies the In predicate on the "content_node_id" field.
func ContentNodeIDIn(vs ...uuid.UUID) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldIn(FieldContentNodeID, vs...))
}

// ContentNodeIDNotIn applies the NotIn predicate on the "content_node_id" field.
func ContentNodeIDNotIn(vs ...uuid.UUID) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldNotIn(FieldContentNodeID, vs...))
}

// InstrumentIDEQ applies the EQ predicate on the "instrument_id" field.
func InstrumentIDEQ(v uuid.UUID) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldEQ(FieldInstrumentID, v))
}

// InstrumentIDNEQ applies the NEQ predicate on the "instrument_id" field.
func InstrumentIDNEQ(v uuid.UUID) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldNEQ(FieldInstrumentID, v))
}

// InstrumentIDIn applies the In predicate on the "instrument_id" field.
func InstrumentIDIn(vs ...uuid.UUID) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldIn(FieldInstrumentID, vs...))
}

// InstrumentIDNotIn applies the NotIn predicate on the "instrument_id" field.
func InstrumentIDNotIn(vs ...uuid.UUID) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldNotIn(FieldInstrumentID, vs...))
}

// LinkedAtEQ applies the EQ predicate on the "linked_at" field.
func LinkedAtEQ(v time.Time) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldEQ(FieldLinkedAt, v))
}

// LinkedAtNEQ applies the NEQ predicate on the "linked_at" field.
func LinkedAtNEQ(v time.Time) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldNEQ(FieldLinkedAt, v))
}

// LinkedAtIn applies the In predicate on the "linked_at" field.
func LinkedAtIn(vs ...time.Time) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldIn(FieldLinkedAt, vs...))
}

// LinkedAtNotIn applies the NotIn predicate on the "linked_at" field.
func LinkedAtNotIn(vs ...time.Time) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldNotIn(FieldLinkedAt, vs...))
}

// LinkedAtGT applies the GT predicate on the "linked_at" field.
func LinkedAtGT(v time.Time) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldGT(FieldLinkedAt, v))
}

// LinkedAtGTE applies the GTE predicate on the "linked_at" field.
func LinkedAtGTE(v time.Time) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldGTE(FieldLinkedAt, v))
}

// LinkedAtLT applies the LT predicate on the "linked_at" field.
func LinkedAtLT(v time.Time) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldLT(FieldLinkedAt, v))
}

// LinkedAtLTE applies the LTE predicate on the "linked_at" field.
func LinkedAtLTE(v time.Time) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.FieldLTE(FieldLinkedAt, v))
}

// HasContentNode applies the HasEdge predicate on the "content_node" edge.
func HasContentNode() predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ContentNodeTable, ContentNodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContentNodeWith applies the HasEdge predicate on the "content_node" edge with a given conditions (other predicates).
func HasContentNodeWith(preds ...predicate.ContentNode) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(func(s *sql.Selector) {
		step := newContentNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInstrument applies the HasEdge predicate on the "instrument" edge.
func HasInstrument() predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, InstrumentTable, InstrumentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstrumentWith applies the HasEdge predicate on the "instrument" edge with a given conditions (other predicates).
func HasInstrumentWith(preds ...predicate.Instrument) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(func(s *sql.Selector) {
		step := newInstrumentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContentNodeInstrument) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContentNodeInstrument) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContentNodeInstrument) predicate.ContentNodeInstrument {
	return predicate.ContentNodeInstrument(sql.NotPredicates(p))
}
